### ISSUE TITLE
Running medaka v0.10 installed from conda-forge crashes in prediction.py

### ISSUE THREAD

**Issue by kehey** [nanoporetech/medaka#100]
**Describe the bug**
Running medaka v0.10 installed from conda-forge crashes in prediction.py

**Logging**
Minimap step goes well. Tensorflow steps crash.

```
(medaka) root@59aa9d619f77:/# medaka_consensus -i /tmp/MLT_ont_plasmid_exp1/ont_raw/barcoding_manual/barcode01/fastq_runid_c8f1877aadbf756e56e15b381baa44150e84934f_0_0.fastq                                 -d /data/tmp/consensus/consensus.cs.fa                                 -o /data/tmp/medaka_consensus                                 -t 3                                 -m r941_min_high;
Checking program versions
This is medaka 0.10.0
Program    Version    Required   Pass
bgzip      1.9        1.9        True
minimap2   2.17       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
Aligning basecalls to draft
Removing previous index file /data/tmp/consensus/consensus.cs.fa.mmi
Constructing minimap index.
[M::mm_idx_gen::0.026*0.15] collected minimizers
[M::mm_idx_gen::0.028*0.26] sorted minimizers
[M::main::0.029*0.29] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.029*0.30] distinct minimizers: 3675 (99.92% are singletons); average occurrences: 1.001; average spacing: 5.276
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /data/tmp/consensus/consensus.cs.fa.mmi /data/tmp/consensus/consensus.cs.fa
[M::main] Real time: 0.067 sec; CPU: 0.010 sec; Peak RSS: 0.004 GB
[M::main::0.018*0.27] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.018*0.28] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.019*0.29] distinct minimizers: 3675 (99.92% are singletons); average occurrences: 1.001; average spacing: 5.276
[M::worker_pipeline::9.854*2.63] mapped 3487 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 3 -a /data/tmp/consensus/consensus.cs.fa.mmi /tmp/fastq_runid_c8f1877aadbf756e56e15b381baa44150e84934f_0_0.fastq
[M::main] Real time: 9.862 sec; CPU: 25.935 sec; Peak RSS: 0.564 GB
[bam_sort_core] merging from 0 files and 3 in-memory blocks...
Running medaka consensus
[13:18:37 - Predict] Processing region(s): pJDB3_consensus:0-19404
[13:18:37 - Predict] Setting tensorflow threads to 3.
Traceback (most recent call last):
  File "/opt/conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 434, in main
    args.func(args)
  File "/opt/conda/envs/medaka/lib/python3.6/site-packages/medaka/prediction.py", line 107, in predict
    K.set_session(tf.Session(
AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'
Failed to run medaka consensus.
```

Based on reports online for a similar error, I verified that when you fire up python and run the set.session, it works and tensorflow is set as backend:

```
(medaka) root@a9cb0bb894a2:/# python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras import backend as K
/opt/conda/envs/medaka/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
>>> K.set_session
<function set_session at 0x7f762c9252f0>
```

**Environment (if you do not have a GPU, write No GPU):**
 - OS:  Docker container https://hub.docker.com/r/continuumio/miniconda3/dockerfile, no GPU

**Additional context**

**Comment by SorenKarst** [comment]
I see the same error when running medaka v0.10 with miniconda3 and no GPU.

**Comment by cjw85** [comment]
I believe this is due to the dependencies in the conda package not being updated correctly. I will take a look.

**Comment by cjw85** [comment]
Requirements update in https://github.com/bioconda/bioconda-recipes/pull/18463

**Comment by cjw85** [comment]
The conda package has been rebuilt with the correct version of tensorflow, when creating a new conda environment you should see a line:
```medaka:               0.10.0-py36hbcae180_1      bioconda```
note the `_1` at the end of the package version. If you see `_0` that is the older package.

**Comment by kehey** [comment]
I'll check from my side and let you know but thanks!

**Comment by kehey** [comment]
It seems to have worked. But there is a curious difference in the stderr output from the previous version (docker file from https://hub.docker.com/r/ttubb/medaka/dockerfile) Last line of new version seems to be incomplete?

**Version from https://hub.docker.com/r/ttubb/medaka/dockerfile**

Ends with `[21:38:55 - Stitch] Processing pJDB3_racon_consensus:1.0-17657.0.`

**Version from https://hub.docker.com/r/ttubb/medaka/dockerfile**

Ends with `[12:45:43 - Stitch] Processing pLV5_racon_consensus:0-.`

--> Seems to be incomplete for the last coordinate? Full stderr below.

**Full versions**

**Version from https://hub.docker.com/r/ttubb/medaka/dockerfile**

```
Constructing minimap index.
[M::mm_idx_gen::0.031*0.10] collected minimizers
[M::mm_idx_gen::0.032*0.20] sorted minimizers
[M::main::0.034*0.24] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.034*0.25] distinct minimizers: 3260 (99.48% are singletons); average occurrences: 1.005; average spacing: 5.366
[M::main] Version: 2.11-r797
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /data/tmp/RB01/racon/medaka_consensus/consensus.fasta.mmi /data/tmp/RB01/racon/medaka_consensus/consensus.fasta
[M::main] Real time: 0.084 sec; CPU: 0.009 sec
[samfaipath] build FASTA index...
[M::main::0.038*0.12] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.038*0.12] mid_occ = 3
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.039*0.13] distinct minimizers: 3260 (99.48% are singletons); average occurrences: 1.005; average spacing: 5.366
[M::worker_pipeline::7.462*2.32] mapped 3487 sequences
[M::main] Version: 2.11-r797
[M::main] CMD: minimap2 -x map-ont --MD -t 3 -a /data/tmp/RB01/racon/medaka_consensus/consensus.fasta.mmi /tmp/MLT_ont_plasmid_exp1/ont_raw/barcoding_manual/barcode01/fastq_runid_c8f1877aadbf756e56e15b381baa44150e84934f_0_0.fastq
[M::main] Real time: 7.476 sec; CPU: 17.324 sec
[bam_sort_core] merging from 0 files and 3 in-memory blocks...
[21:38:42 - Predict] Processing region(s): pJDB3_racon_consensus:1.0-17657.0:0-17585
[21:38:42 - Predict] Setting tensorflow threads to 3.
[21:38:42 - Predict] Processing 1 long region(s) with batching.
[21:38:42 - ModelLoad] Building model (steps, features, classes): (10000, 10, 5)
[21:38:42 - ModelLoad] With cudnn: False
[21:38:43 - ModelLoad] Loading weights from /software/medaka-0.8.2/venv/lib/python3.6/site-packages/medaka-0.8.2-py3.6-linux-x86_64.egg/medaka/data/r941_min_high_model.hdf5
[21:38:44 - PWorker] Running inference for 0.0M draft bases.
[21:38:44 - Sampler] Initializing sampler for consensus of region pJDB3_racon_consensus:1.0-17657.0:0-17585.
[21:38:48 - Feature] Processed pJDB3_racon_consensus:1.0-17657.0:0.0-17584.0 (median depth 1389.0)
[21:38:48 - Sampler] Took 4.16s to make features.
[21:38:48 - Sampler] Pileup for pJDB3_racon_consensus:1.0-17657.0:0.0-17584.0 is of width 101408
[21:38:53 - PWorker] All done, 0 remainder regions.
[21:38:53 - Predict] Finished processing all regions.
[21:38:55 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
[21:38:55 - Stitch] Processing pJDB3_racon_consensus:1.0-17657.0.
```

**New build version**

```
Constructing minimap index.
[M::mm_idx_gen::0.077*0.05] collected minimizers
[M::mm_idx_gen::0.079*0.10] sorted minimizers
[M::main::0.081*0.12] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.081*0.12] distinct minimizers: 4076 (91.44% are singletons); average occurrences: 1.092; average spacing: 5.342
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /data/tmp/RB03/racon/consensus/pLV5.racon.consensus.fa.mmi /data/tmp/RB03/racon/consensus/pLV5.racon.consensus.fa
[M::main] Real time: 0.143 sec; CPU: 0.011 sec; Peak RSS: 0.004 GB
[M::main::0.019*0.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.020*0.25] mid_occ = 5
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.020*0.26] distinct minimizers: 4076 (91.44% are singletons); average occurrences: 1.092; average spacing: 5.342
[M::worker_pipeline::3.016*2.57] mapped 2411 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 3 -a /data/tmp/RB03/racon/consensus/pLV5.racon.consensus.fa.mmi /tmp/MLT_ont_plasmid_exp1/ont_raw/barcoding_manual/barcode03/fastq_runid_c8f1877aadbf756e56e15b381baa44150e84934f_0_0.fastq
[M::main] Real time: 3.022 sec; CPU: 7.754 sec; Peak RSS: 0.155 GB
[bam_sort_core] merging from 0 files and 3 in-memory blocks...
[12:45:29 - Predict] Processing region(s): pLV5_racon_consensus:0-23790
[12:45:29 - Predict] Setting tensorflow threads to 3.
[12:45:29 - Predict] Processing 1 long region(s) with batching.
[12:45:29 - Predict] Using model: /opt/conda/envs/medaka/lib/python3.6/site-packages/medaka/data/r941_min_high_model.hdf5.
[12:45:29 - ModelLoad] Building model with cudnn optimization: False
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-3
OMP: Info #156: KMP_AFFINITY: 4 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 2 cores/pkg x 2 threads/core (2 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 0 thread 1 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 thread 0 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 1 thread 1 
OMP: Info #250: KMP_AFFINITY: pid 81 tid 101 thread 0 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 81 tid 101 thread 1 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 81 tid 102 thread 2 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 81 tid 100 thread 3 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 81 tid 106 thread 4 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 81 tid 108 thread 6 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 81 tid 107 thread 5 bound to OS proc set 1
[12:45:30 - DLoader] Initializing data loader
[12:45:30 - PWorker] Running inference for 0.0M draft bases.
[12:45:30 - Sampler] Initializing sampler for consensus of region pLV5_racon_consensus:0-23790.
[12:45:31 - Feature] Processed pLV5_racon_consensus:0.0-23789.0 (median depth 444.0)
[12:45:31 - Sampler] Took 0.60s to make features.
OMP: Info #250: KMP_AFFINITY: pid 81 tid 112 thread 7 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 81 tid 113 thread 8 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 81 tid 114 thread 9 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 81 tid 115 thread 10 bound to OS proc set 2
[12:45:41 - PWorker] 99.0% Done (0.0/0.0 Mbases) in 10.4s
[12:45:41 - PWorker] All done, 0 remainder regions.
[12:45:41 - Predict] Finished processing all regions.
[12:45:43 - DataIndex] Loaded 1/1 (100.00%) sample files.
[12:45:43 - Stitch] Processing pLV5_racon_consensus:0-.
```

**Comment by cjw85** [comment]
The different reporting of the regions is a deliberate change between v0.8.2 and v0.10.0

**Comment by kehey** [comment]
Allright, then considered it fixed!

**Comment by astulaaa** [comment]
just create a new medaka environment and use this: conda install medaka=0.10.0=py36hbcae180_1
