### ISSUE TITLE
Error at installation

### ISSUE THREAD

**Issue by scogi** [nanoporetech/medaka#108]
Hi!

I am trying to install medaka, but i keep getting an error:

```
$pip3 install medaka
Collecting medaka
  Using cached https://files.pythonhosted.org/packages/b0/db/330679c509f6022c602af00351d0e3433ace0ece2df2795e00bd5ba68a7d/medaka-0.11.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy==1.16.1
  Using cached https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting parasail
  Using cached https://files.pythonhosted.org/packages/a1/51/dfacc4be8e29d5df99700b7255abeae81f5381ed6520c46c041a596b7e9d/parasail-1.1.19.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7muf3pfj/parasail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7muf3pfj/parasail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7muf3pfj/parasail/pip-egg-info
         cwd: /tmp/pip-install-7muf3pfj/parasail/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7muf3pfj/parasail/setup.py", line 18, in <module>
        from wheel.bdist_wheel import bdist_wheel as bdist_wheel_
    ModuleNotFoundError: No module named 'wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
System:
LSB Version: :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.7.1908 (Core)
Release: 7.7.1908
Canu 1.9
20 CPU cores, 80 GB of RAM , 4.6 TB of free disk space

Any hints what is going wrong? Thank you!

best regards
Stefan

**Comment by scogi** [comment]
Update:
We now installed the 'wheel' module, but now a new error comes:



$ python3.6 -m pip install medaka
```
Collecting medaka
  Using cached https://files.pythonhosted.org/packages/b0/db/330679c509f6022c602af00351d0e3433ace0ece2df2795e00bd5ba68a7d/medaka-0.11.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: cffi in /usr/local/lib64/python3.6/site-packages (from medaka) (1.13.2)
Requirement already satisfied: h5py==2.7.1 in /usr/local/lib64/python3.6/site-packages (from medaka) (2.7.1)
Requirement already satisfied: ont-fast5-api in /usr/local/lib/python3.6/site-packages (from medaka) (2.0.1)
Collecting parasail
  Using cached https://files.pythonhosted.org/packages/a1/51/dfacc4be8e29d5df99700b7255abeae81f5381ed6520c46c041a596b7e9d/parasail-1.1.19.tar.gz
Requirement already satisfied: tensorflow==1.14.0 in /usr/local/lib64/python3.6/site-packages (from medaka) (1.14.0)
Requirement already satisfied: mappy in /usr/local/lib64/python3.6/site-packages (from medaka) (2.17)
Requirement already satisfied: whatshap==0.18 in /usr/local/lib64/python3.6/site-packages (from medaka) (0.18)
Requirement already satisfied: biopython in /usr/local/lib64/python3.6/site-packages (from medaka) (1.74)
Requirement already satisfied: pysam==0.15.2 in /usr/local/lib64/python3.6/site-packages (from medaka) (0.15.2)
Requirement already satisfied: intervaltree in /usr/local/lib/python3.6/site-packages (from medaka) (3.0.2)
Requirement already satisfied: numpy==1.16.1 in /usr/local/lib64/python3.6/site-packages (from medaka) (1.16.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi->medaka) (2.19)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from h5py==2.7.1->medaka) (1.12.0)
Requirement already satisfied: progressbar33>=2.3.1 in /usr/local/lib/python3.6/site-packages (from ont-fast5-api->medaka) (2.4)
Requirement already satisfied: wheel in /usr/local/lib/python3.6/site-packages (from parasail->medaka) (0.33.6)
Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib64/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.0.8)
Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (0.3.2)
Requirement already satisfied: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.14.0)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib64/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.25.0)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (0.8.0)
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib64/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.11.2)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.1.0)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib64/python3.6/site-packages (from tensorflow==1.14.0->medaka) (3.11.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib64/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.1.0)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (0.8.1)
Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (0.1.8)
Requirement already satisfied: tensorboard<1.15.0,>=1.14.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.14.0->medaka) (1.14.0)
Requirement already satisfied: PyVCF in /usr/local/lib64/python3.6/site-packages (from whatshap==0.18->medaka) (0.6.8)
Requirement already satisfied: xopen>=0.5.0 in /usr/local/lib/python3.6/site-packages (from whatshap==0.18->medaka) (0.8.4)
Requirement already satisfied: pyfaidx>=0.5.5.2 in /usr/local/lib/python3.6/site-packages (from whatshap==0.18->medaka) (0.5.6)
Requirement already satisfied: networkx in /usr/local/lib/python3.6/site-packages (from whatshap==0.18->medaka) (2.4)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /usr/local/lib/python3.6/site-packages (from intervaltree->medaka) (2.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf>=3.6.1->tensorflow==1.14.0->medaka) (42.0.1)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib64/python3.6/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0->medaka) (0.16.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib64/python3.6/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0->medaka) (3.1.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/site-packages (from networkx->whatshap==0.18->medaka) (4.4.1)
Building wheels for collected packages: parasail
  Building wheel for parasail (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z49bzrr/parasail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z49bzrr/parasail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-60njr1ct --python-tag cp36
       cwd: /tmp/pip-install-6z49bzrr/parasail/
  Complete output (52 lines):
  running bdist_wheel
  parasail/libparasail.so not found, attempting to build
  Downloading latest parasail master
  Unzipping parasail master archive
  fixing executable bits after unzipping
  Unable to find parasail configure script
  Prepending /usr/bin to PATH
  PATH=/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/bin
  Running autoreconf -fi from ./parasail-master
  b'This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi'
  b'm4 (GNU M4) 1.4.16'
  autoconf not found
  automake not found
  libtoolize not found
  autoreconf not found
  Prepending /tmp/pip-install-6z49bzrr/parasail/autotools/bin to PATH
  PATH=/tmp/pip-install-6z49bzrr/parasail/autotools/bin:/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/bin
  Building autotools
  Downloading http://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
  Expanding m4-1.4.17.tar.gz
  configuring m4
  making and installing m4
  Downloading http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
  Expanding autoconf-2.69.tar.gz
  configuring autoconf
  making and installing autoconf
  Downloading http://ftp.gnu.org/gnu/automake/automake-1.15.1.tar.gz
  Expanding automake-1.15.1.tar.gz
  configuring automake
  making and installing automake
  b"  GEN      bin/automake\n  GEN      bin/aclocal\n  GEN      t/ax/shell-no-trail-bslash\n  GEN      doc/aclocal.1\n  GEN      t/ax/cc-no-c-o\n  GEN      runtest\n  GEN      doc/automake.1\n  GEN      lib/Automake/Config.pm\n  GEN      t/ax/test-defs.sh\n  GEN      doc/aclocal-1.15.1\n  GEN      doc/automake-1.15.1\nhelp2man: can't get `--help' info from automake-1.15\nTry `--no-discard-stderr' if option outputs to stderr\nmake: *** [doc/automake-1.15.1] Error 2\nmake: *** Waiting for unfinished jobs....\n"
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 463, in <module>
      install_requires=INSTALL_REQUIRES,
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 425, in run
      prepare_shared_lib()
    File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 419, in prepare_shared_lib
      build_parasail(libname)
    File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 306, in build_parasail
      build_autotools()
    File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 247, in build_autotools
      raise RuntimeError("make of {} failed".format(tool))
  RuntimeError: make of automake failed
  ----------------------------------------
  ERROR: Failed building wheel for parasail
  Running setup.py clean for parasail
Failed to build parasail
Installing collected packages: parasail, medaka
    Running setup.py install for parasail ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z49bzrr/parasail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z49bzrr/parasail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v8o_et2x/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-6z49bzrr/parasail/
    Complete output (50 lines):
    running install
    parasail/libparasail.so not found, attempting to build
    Archive 'parasail-master.zip' already downloaded
    Archive 'parasail-master.zip' already unzipped to /tmp/pip-install-6z49bzrr/parasail
    parasail archive executable permissions ok
    Unable to find parasail configure script
    Prepending /usr/bin to PATH
    PATH=/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/bin
    Running autoreconf -fi from ./parasail-master
    b'This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi'
    b'm4 (GNU M4) 1.4.16'
    autoconf not found
    automake not found
    libtoolize not found
    autoreconf not found
    Prepending /tmp/pip-install-6z49bzrr/parasail/autotools/bin to PATH
    PATH=/tmp/pip-install-6z49bzrr/parasail/autotools/bin:/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/bin
    Building autotools
    m4-1.4.17.tar.gz already exists! Using existing copy.
    m4-1.4.17 already exists! Using existing sources.
    /tmp/pip-install-6z49bzrr/parasail/autotools/bin/m4 already exists! Skipping build.
    autoconf-2.69.tar.gz already exists! Using existing copy.
    autoconf-2.69 already exists! Using existing sources.
    /tmp/pip-install-6z49bzrr/parasail/autotools/bin/autoconf already exists! Skipping build.
    automake-1.15.1.tar.gz already exists! Using existing copy.
    automake-1.15.1 already exists! Using existing sources.
    configuring automake
    making and installing automake
    b"  GEN      bin/automake\n  GEN      bin/aclocal\n  GEN      t/ax/shell-no-trail-bslash\n  GEN      t/ax/cc-no-c-o\n  GEN      runtest\n  GEN      lib/Automake/Config.pm\n  GEN      t/ax/test-defs.sh\n  GEN      doc/aclocal-1.15.1\n  GEN      doc/automake-1.15.1\nhelp2man: can't get `--help' info from automake-1.15\nTry `--no-discard-stderr' if option outputs to stderr\nmake: *** [doc/automake-1.15.1] Error 2\nmake: *** Waiting for unfinished jobs....\n"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 463, in <module>
        install_requires=INSTALL_REQUIRES,
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 436, in run
        prepare_shared_lib()
      File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 419, in prepare_shared_lib
        build_parasail(libname)
      File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 306, in build_parasail
        build_autotools()
      File "/tmp/pip-install-6z49bzrr/parasail/setup.py", line 247, in build_autotools
        raise RuntimeError("make of {} failed".format(tool))
    RuntimeError: make of automake failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z49bzrr/parasail/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z49bzrr/parasail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v8o_et2x/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by cjw85** [comment]
Hi @scogi 

Your latest issue is a result of not having the infrastructure available on your computer to compile the parasail aligner code. There is currently no pre-compiled package for this available on pypi. There is an outstanding pull request (https://github.com/jeffdaily/parasail-python/pull/43) to the developer of this library. We host a precompiled binary which you could install before trying to install medaka:

    wget https://ont-research.s3-eu-west-1.amazonaws.com/parasail-1.1.17-py2.py3-none-manylinux1_x86_64.whl
    pip install parasail-1.1.17-py2.py3-none-manylinux1_x86_64.whl
    pip install medaka

**Comment by scogi** [comment]
Worked. Thank you!
