### ISSUE TITLE
Conda installation issue on OSX

### ISSUE THREAD

**Issue by ksahlin** [nanoporetech/medaka#114]
Would you consider supporting this tool on mac systems? It fails when trying to install it on MacOS system (Mojave).

After conda installation (`conda create -n medaka -c conda-forge -c bioconda medaka`):
(This Numpy works fine otherwise so I'm guessing its not my numpy that is broken, as written below).
```
(medaka) Sahlins-Personal-Pro:kxs624$ medaka
Traceback (most recent call last):
  File "/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/medaka/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 7, in <module>
    import numpy as np
  File "/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /anaconda3/envs/medaka/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /anaconda3/envs/medaka/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so
  Reason: image not found
```

Best,
Kristoffer

**Comment by cjw85** [comment]
Hi @ksahlin 

This looks to be an issue with the conda numpy and openblas packages. I have successfully worked around it by installing medaka with a specific openblas package version:

    conda create -n medaka -c conda-forge -c bioconda medaka openblas==0.3.3

**Comment by ksahlin** [comment]
Wow, that worked right off the bat, thanks!

Just a suggestion: Given that we have observed the same installation issues on three different Macs, maybe the documentation could include your suggested fix under a separate header "Installation on Mac"?  

Thanks so much,
K

**Comment by cjw85** [comment]
I have amended the bionconda build to pin the version of openblas
https://github.com/bioconda/bioconda-recipes/pull/19226
