### ISSUE TITLE
medaka stopping on flye assembly

### ISSUE THREAD

**Issue by ramiroricardo** [nanoporetech/medaka#115]
Dear all,

I am trying to assemble a bacterial genome for which I have nanopore reads called with guppy in hac mode (guppy version was 3.1.5). I assembled using miniasm or flye and then polished with racon. For the miniasm assembly, I can run medaka with no problems. However, for the flye assembly, medaka is stopping after the error below. If anyone knows of a way to solve this, that would be great.

```
header_dict = bam.header.as_dict()
AttributeError: 'dict' object has no attribute 'as_dict'
Failed to run medaka consensus.
```

This happens independently of whether I run medaka after 1 or 4 racon runs.  I have installed medaka as a conda environment. The exact command I ran was: 

```
MEDAKAMODEL=r941_min_high_g303;
MEDAKADIR=temp/$(basename $OUTPUTFILE)/;
medaka_consensus -i $NANOPORE  -d $DRAFT -o $MEDAKADIR -t 2 -m $MEDAKAMODEL
```

The full output that I get is:

```
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version ofnumpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Checking program versions
This is medaka 0.11.0
Program    Version    Required   Pass
bgzip      1.9        1.9        True
minimap2   2.17       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
Aligning basecalls to draft
Removing previous index file /media/DATA/tdapa/TDA1000/results/assemblies/TDA1000_trimmed_flye_raconNPm4.fa.mmi
Constructing minimap index.
[M::mm_idx_gen::0.148*1.01] collected minimizers
[M::mm_idx_gen::0.207*1.56] sorted minimizers
[M::main::0.380*1.04] loaded/built the index for 4 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 4
[M::mm_idx_stat::0.390*1.04] distinct minimizers: 1145151 (96.84% are singletons); average occurrences: 1.042; average spacing: 5.349
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /media/DATA/tdapa/TDA1000/results/assemblies/TDA1000_trimmed_flye_raconNPm4.fa.mmi /media/DATA/tdapa/TDA1000/results/assemblies/TDA1000_trimmed_flye_raconNPm4.fa
[M::main] Real time: 0.394 sec; CPU: 0.409 sec; Peak RSS: 0.066 GB
[samfaipath] build FASTA index...
[M::main::0.250*0.18] loaded/built the index for 4 target sequence(s)
[M::mm_mapopt_update::0.267*0.23] mid_occ = 9
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 4
[M::mm_idx_stat::0.279*0.27] distinct minimizers: 1145151 (96.84% are singletons); average occurrences: 1.042; average spacing: 5.349
[M::worker_pipeline::71.965*2.07] mapped 104300 sequences
[M::worker_pipeline::146.444*1.83] mapped 104013 sequences
[M::worker_pipeline::147.411*1.83] mapped 8829 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 2 -a /media/DATA/tdapa/TDA1000/results/assemblies/TDA1000_trimmed_flye_raconNPm4.fa.mmi /media/DATA/tdapa/TDA1000/TDA1000_hac_trimmed.fastq
[M::main] Real time: 147.420 sec; CPU: 269.074 sec; Peak RSS: 2.796 GB
[bam_sort_core] merging from 2 files and 2 in-memory blocks...
Running medaka consensus
Traceback (most recent call last):
  File "/home/akonrad/.conda/envs/nanopore_polishing/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/medaka/medaka.py", line 444, inmain
    args = parser.parse_args()
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/akonrad/.conda/envs/nanopore_polishing/lib/python3.6/site-packages/medaka/medaka.py", line 72, in __call__
    header_dict = bam.header.as_dict()
AttributeError: 'dict' object has no attribute 'as_dict'
Failed to run medaka consensus.
```

**Comment by cjw85** [comment]
Hi @ramiroricardo,

This appears to be due to a change in the interface in [pysam](https://github.com/pysam-developers/pysam), and that the medaka conda package allows installation of newer versions of pysam than we develop with. I will change the medaka conda package to require the same fixed pysam we use.

**Comment by cjw85** [comment]
The conda package for medaka v0.11.1 should resolve this issue:
https://github.com/bioconda/bioconda-recipes/pull/19266

It should be available for download shortly. Please open a new issue if you have problems with the new version.
