### ISSUE TITLE
Too exaggerated  RAM using when conduct “medaka methylation guppy2sam”

### ISSUE THREAD

**Issue by DAVID2022** [nanoporetech/medaka#122]
**Describe the bug**
Dear friends,
I try to do methylation detection based on the result of guppy3.4.4(dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac_prom.cfg)
when i try to carry out "
medaka methylation guppy2sam  /data/guppy-modi/guppy-methpro-191225  REFERENCE..fasta --workers 3 --recursive | samtools sort -@ 8 | samtools view -b -@ 8 >methhac-200102.bam
"
I got an error message :

[13:19:17 - ModExtract] Found 4000 reads for /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_469.fast5.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/envs/medaka/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/medaka/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/root/anaconda3/envs/medaka/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/root/anaconda3/envs/medaka/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full

Traceback (most recent call last):
  File "/root/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 523, in main
    args.func(args)
  File "/root/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 104, in hdf_to_sam
    for res in executor.map(worker, fast5s):
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[bam_sort_core] merging from 112 files and 8 in-memory blocks...

and when I decrease the worker number to 1 and carry out 
"
medaka methylation guppy2sam  /data/guppy-modi/guppy-methpro-191225  REFERENCE..fasta --workers 1 --recursive | samtools sort -@ 8 | samtools view -b -@ 8 >methhac-200102.bam
"

I find that "medaka methylation guppy2sam" will use over 600GB RAM for just one "workers ", the using of RAM is too exaggerated and the speed of medaka methylation guppy2sam is too slow.
![image](https://user-images.githubusercontent.com/45761661/71900962-dc0fc600-3199-11ea-8788-0127c6298660.png)

Can you help to speed up my detection process?

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: CentOS 7.4 64bit
 - CPU model 32vCPUs | 940GB
 - Nvidia driver version none
 - CUDA version none
 - cuDNN version none

**Comment by DAVID2022** [comment]
![image](https://user-images.githubusercontent.com/45761661/71943128-88819480-31fa-11ea-8c0c-cd59fda6dcb8.png)
about 850GB now

**Comment by DAVID2022** [comment]
my process failed again and give me an error message :
[12:56:04 - ModExtract] Processing /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_316.fast5.
[12:57:12 - ModExtract] Found 4000 reads for /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_316.fast5.
[13:06:24 - ModExtract] Processing /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_160.fast5.
[13:07:30 - ModExtract] Found 4000 reads for /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_160.fast5.
[13:16:42 - ModExtract] Processing /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_14.fast5.
[13:17:49 - ModExtract] Found 4000 reads for /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_14.fast5.
[13:27:53 - ModExtract] Processing /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_309.fast5.
[13:29:00 - ModExtract] Found 4000 reads for /data/guppy-modi/guppy-methpro-191225/workspace/fast5_pass/PAD35475_f16186a3a9047464c4069d11a5b3dd7124934a1f_309.fast5.
Traceback (most recent call last):
  File "/root/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 523, in main
    args.func(args)
  File "/root/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 104, in hdf_to_sam
    for res in executor.map(worker, fast5s):
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/root/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[bam_sort_core] merging from 120 files and 8 in-memory blocks...

**Comment by ChloeDG** [comment]
Any word on this? I am having the same problem.

**Comment by cjw85** [comment]
Hi @ChloeDG @DAVID2022,

Firstly I apologise for the lack of a response here. This is on our radar as something that needs revisiting, which we will try to do in a forthcoming release.

**Comment by DAVID2022** [comment]
Thank you for your kind help!  Looking forward to your new version medaka!

**Comment by ChloeDG** [comment]
Looking forward to it!

**Comment by cjw85** [comment]
@DAVID2022 

Can you report the output of the following:

     python -c "import mappy; print(mappy.__version__)"

There is an [issue](https://github.com/lh3/minimap2/issues/445) in older versions of `mappy` that caused high memory usage.

In the first instance we will rearchitect `guppy2sam` to use less memory; currently each worker process loads its own instance of an alignment index.

**Comment by ChloeDG** [comment]
@DAVID2022 

Output for me is: 

2.17

**Comment by ChloeDG** [comment]
@cjw85 

Output for me is: 

2.17

**Comment by cjw85** [comment]
We have a fix for this which will appear in the next release within the next week or so.

**Comment by DAVID2022** [comment]
@cjw85 I insatll medaka with conda and the output of my server is:
2.17

**Comment by cjw85** [comment]
@DAVID2022 @ChloeDG,

v0.11.5 includes should resolve this issue.
