### ISSUE TITLE
ModExtract/mod_base NoneType error

### ISSUE THREAD

**Issue by brucemoran** [nanoporetech/medaka#132]
Hi, I have run (v0.11.3):

`medaka methylation guppy2sam guppy/workspace/fast5_pass fasta.fa.gz | samtools sort | samtools view -b > barcode01.medaka.meth.bam`

and got error below (incl. last line prior to error). 

How can I test what is causing this? Basecalls with `guppy_basecaller` (v3.4.4+a296acb), `--fast5_out` and `--post_out` specified. 

Any help appreciated.

Bruce

```
[10:26:58 - ModExtract] Found 4000 reads for guppy/workspace/20190412_0814_MN19466_FAK76875_fbafd47b/fast5_pass/FAK76875_771c290f65ddbb5963f30000dd10e54b480059fe_2.fast5.
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/site-packages/medaka/methdaka.py", line 81, in hdf_to_sam_worker
    mod_base = mod_base.view(dtype=MODTYPE)
AttributeError: 'NoneType' object has no attribute 'view'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/site-packages/medaka/medaka.py", line 523, in main
    args.func(args)
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/site-packages/medaka/methdaka.py", line 104, in hdf_to_sam
    for res in executor.map(worker, fast5s):
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/miniconda/envs/nanopore_gDNA_CNA/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'view'
```

**Comment by cjw85** [comment]
Hi @brucemoran,

As a result of https://github.com/nanoporetech/medaka/issues/122, the `guppy2sam` program was extensively rewritten. Could you try medaka v0.11.5 and report back. This is available in conda.

**Comment by brucemoran** [comment]
OK, changing version I get no errors, but the output is only BAM header.

Is there a case where this occurs?
