### ISSUE TITLE
program interuption after alignment

### ISSUE THREAD

**Issue by chklopp** [nanoporetech/medaka#16]
I try to polish a 1G genome using 70X of ONT reads. 

NPROC=$(nproc)
BASECALLS=reads.fastq.gz
DRAFT=assembly.fa
OUTDIR=medaka_consensus
medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC} -m r94

medaka performs the genome indexing and alignment. The bam and bai files are created in OUTDIR.
Then I get the following error 

Creating features
Using TensorFlow backend.
None
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Medaka/medaka-0.3.0/venv/bin/hp_compress", line 11, in <module>
    load_entry_point('medaka==0.3.0', 'console_scripts', 'hp_compress')()
  File "/usr/local/bioinfo/src/Medaka/medaka-0.3.0/venv/lib/python3.6/site-packages/medaka-0.3.0-py3.6.egg/medaka/compress.py", line 650, in main
    args.func(args)
  File "/usr/local/bioinfo/src/Medaka/medaka-0.3.0/venv/lib/python3.6/site-packages/medaka-0.3.0-py3.6.egg/medaka/compress.py", line 617, in choose_feature_func
    features(args)
  File "/usr/local/bioinfo/src/Medaka/medaka-0.3.0/venv/lib/python3.6/site-packages/medaka-0.3.0-py3.6.egg/medaka/compress.py", line 365, in features
    opt_str = '\n'.join(['{}: {}'.format(k,v) for k, v in fe_kwargs.items()])
AttributeError: 'NoneType' object has no attribute 'items'

How can I find what went wrong?

**Comment by cjw85** [comment]
Hi @chklopp,

It looks like you are using an old version of medaka (your log above indicates medaka-0.3.0). Can I ask that you first upgrade to the most recent version, currently 1.4.3. This contains many updates and performance improvements.

**Comment by chklopp** [comment]
Version 1.4.3 runs fine with the same command.

**Comment by chklopp** [comment]
The process ran until 

...
[03:05:22 - Stitch] Processing ctg254.
[03:05:29 - Stitch] Processing ctg255.
[03:05:36 - Stitch] Processing ctg256.
[03:05:47 - Stitch] Processing ctg257.
[03:05:59 - Stitch] Processing ctg258.
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Medaka/medaka-1.4.3/venv/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.4.3', 'console_scripts', 'medaka')()
  File "/usr/local/bioinfo/src/Medaka/medaka-1.4.3/venv/lib/python3.6/site-packages/medaka-0.4.3-py3.6-linux-x86_64.egg/medaka/medaka.py", line 170, in main
    args.func(args)
  File "/usr/local/bioinfo/src/Medaka/medaka-1.4.3/venv/lib/python3.6/site-packages/medaka-0.4.3-py3.6-linux-x86_64.egg/medaka/stitch.py", line 81, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions, model_yml=args.model_yml)
  File "/usr/local/bioinfo/src/Medaka/medaka-1.4.3/venv/lib/python3.6/site-packages/medaka-0.4.3-py3.6-linux-x86_64.egg/medaka/stitch.py", line 62, in stitch_from_probs
    end_1_ind, start_2_ind = get_sample_overlap(s1, s2)
  File "/usr/local/bioinfo/src/Medaka/medaka-1.4.3/venv/lib/python3.6/site-packages/medaka-0.4.3-py3.6-linux-x86_64.egg/medaka/common.py", line 487, in get_sample_overlap
    assert len(pos1_ovl) == len(pos2_ovl)
AssertionError

**Comment by cjw85** [comment]
Closing this issue, see #20 for new distinct error.
