### ISSUE TITLE
medaka_variants failes with Parameter -p

### ISSUE THREAD

**Issue by stephanflemming** [nanoporetech/medaka#161]
While trying the parameter -p of medaka_variant the following error appears. I am using the conda version 1.0.1.

```
This is WhatsHap 0.18 running under Python 3.6.10
Traceback (most recent call last):
  File "/home/stephan/anaconda3/envs/medaka2/bin/whatshap", line 12, in <module>
    sys.exit(main())
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/whatshap/phase.py", line 1114, in main
    run_whatshap(**vars(args))
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/whatshap/phase.py", line 580, in run_whatshap
    out_file=output, tag=tag)
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/whatshap/vcf.py", line 478, in __init__
    self._reader = vcf.Reader(filename=in_path)
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/vcf/parser.py", line 326, in _parse_metainfo
    key, val = parser.read_filter(line)
  File "/home/stephan/anaconda3/envs/medaka2/lib/python3.6/site-packages/vcf/parser.py", line 143, in read_filter
    "One of the FILTER lines is malformed: %s" % filter_string)
SyntaxError: One of the FILTER lines is malformed: ##FILTER=<ID=lowqual,Description="Set if not true: (((TYPE=\"snp\" | TYPE=\"mnp\") & (QUAL > 12)) | ((TYPE!=\"snp\" & TYPE!=\"mnp\") & (QUAL > 14)))">
* Failed to phase variants in round_1.vcf.
```

Find the stdout here: [log.txt](https://github.com/nanoporetech/medaka/files/4656840/log.txt)

**Comment by cjw85** [comment]
This should be fixed in version v1.0.2, we have removed escape characters that we troubling the vcf parser used in whatshap.
