### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'view'` in guppy2sam medaka v1.0.3 

### ISSUE THREAD

**Issue by yyoshiaki** [nanoporetech/medaka#187]
Hi, I updated medaka to v1.0.3 via conda, and now I have a problem with guppy2sam. Using [this example data](https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html), I tried this command.

```
medaka methylation guppy2sam basecalled \
--reference reference.fasta \
--recursive > meth.bam
```

and I got an error.

```
...
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 324, in _
invoke_callbacks
    callback(self)
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 241,
 in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not AttributeError
[14:48:25 - concurrent.futures] exception calling callback for <Future at 0x2ac3d9ebfd68 state=finished 
raised AttributeError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 175, in
 _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 133,
 in hdf_to_sam_worker
    mod_base = mod_base.view(dtype=MODTYPE)
AttributeError: 'NoneType' object has no attribute 'view'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 237,
 in _store
    results = future.result()
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 425, in r
esult
    return self.__get_result()
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 384, in _
_get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 324, in _
invoke_callbacks
    callback(self)
  File "/home/yyasumizu/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/methdaka.py", line 241,
 in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not AttributeError
```

When I use medaka v1.0.2, the output sam is somehow truncated though it worked well for the same data and medaka v1.0.2 several months ago. Could you please tell me how to cope with it?

Best,
Yoshiaki

**Comment by cjw85** [comment]
Hi @yyoshiaki,

I have just create a standalone software for this functionality in medaka which has some bug fixes. The functionality will be removed from medaka in a future release.

https://github.com/nanoporetech/fast5mod
