### ISSUE TITLE
TypeError: write() argument must be str, not BrokenProcessPool

### ISSUE THREAD

**Issue by replikation** [nanoporetech/medaka#190]
**Describe the bug**
hi, i get an error using `medaka methylation guppy2sam` (medaka version medaka:1.0.3 from bioconda) and I can't figure out what the issue is. It fails for me in creating the meth.bam file

 command:

````bash
        medaka methylation guppy2sam ${fast5}/workspace \
            --reference ${fasta} \
            --workers 1 --io_workers 1 --recursive |\
            samtools sort -@ ${task.cpus} | samtools view -b -@ ${task.cpus} > meth.bam
````

**Logging**
````bash
[08:47:58 - ModExtract] NOTE: Mod. base scores are output w.r.t the sequencing direction, not the aligned read orientation.
[08:47:58 - Extractor] Starting worker processes.
[08:47:58 - Extractor] Found 2 files to process.
[08:47:58 - ModExtract] Processing basecalling_results/workspace/FAK43478_25ade4b28ed49f8064ebcae8fc04f95ce85bb3aa_0.fast5.
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
[08:52:46 - concurrent.futures] exception calling callback for <Future at 0x7f8b05416978 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/medaka/methdaka.py", line 237, in _store
    results = future.result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/conda/lib/python3.6/site-packages/medaka/methdaka.py", line 241, in _store
    sys.stderr.write(e)
TypeError: write() argument must be str, not BrokenProcessPool
````

**Environment:**
 - Installation method conda within docker
 - Ubuntu 18.04
 - no GPU
- 64 GB RAM 

**Additional context**
links are referring to the files, like this:
````
basecalling_results -> /mnt/2TB_disk/methylation_tests/results/reads/basecalling_results/
````
shouldn't be the issue as medaka finds the files
fast5s are basecalled via:

````
        guppy_basecaller -r \
        --save_path basecalling_results --input_path ${dir} \
        --compress_fastq --fast5_out \
        --config dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg \
        --barcode_kits ${params.barcode} --device auto
````

**Comment by cjw85** [comment]
Hi @replikation,

The methylation functionality of medaka has been moved into a standalone software project here: https://github.com/nanoporetech/fast5mod

This project contains a few updates and bug fixes. If you have any problems with its use, please raise and Issue on that project; I will close this issue.

**Comment by replikation** [comment]
ad @cjw85 okay thanks, would be good to mention this here: https://nanoporetech.github.io/medaka/methylation.html

**Comment by cjw85** [comment]
Indeed, the next release of medaka will remove the functionality and references to it will be removed from the documentation; fast5mod was released to fix bugs without being dependent on a medaka release. Apologies for wasting your time.
