### ISSUE TITLE
KeyError: "sequence 'xxx' not present"

### ISSUE THREAD

**Issue by scogi** [nanoporetech/medaka#193]
**Describe the bug**
Hi,
I would like to call and phase variants using medaka_variant but it stops with the error
KeyError: "sequence 'BC_17-20_KCNQ2_chr20' not present"

Where BC_17-20_KCNQ2_chr20 is the name of the reference sequence. However, the file is in the same folder. 
Would be thankful for any advice. THank you! 
Stefan

**Logging**
`$ medaka_variant -f ./KCNQ2_BC_17_20.fasta -i barcode17.sorted.bam -o out1 -s r941_min_fast_g303 -d

++ Preparing data
- Checking program versions
Program    Version    Required   Pass     
bcftools   1.10.2     1.9        True     
bgzip      1.10.2     1.9        True     
minimap2   2.17       2.11       True     
samtools   1.10       1.9        True     
tabix      1.10.2     1.9        True     

++ Running first pass to haplotag reads.
+ Running consensus calling
- Running medaka consensus with /media/qf0297/data/data_np/2020/20200811_Janecke_haplotyping/analysis/KCNQ2_BC_17_20/barcode17.sorted.bam --model /home/qf0297/.conda/envs/medaka/lib/python3.6/site-packages/medaka/data/r941_min_fast_g303_model.hdf5 
[13:43:32 - Predict] Processing region(s): BC_17-20_KCNQ2_chr20:62066355-62071029:0-4675
[13:43:32 - Predict] Setting tensorflow threads to 1.
[13:43:32 - Predict] Processing 1 long region(s) with batching.
[13:43:32 - Predict] Using model: /home/qf0297/.conda/envs/medaka/lib/python3.6/site-packages/medaka/data/r941_min_fast_g303_model.hdf5.
[13:43:32 - ModelLoad] Building model with cudnn optimization: False
[13:43:33 - DLoader] Initializing data loader
[13:43:33 - PWorker] Running inference for 0.0M draft bases.
[13:43:33 - Sampler] Initializing sampler for consensus of region BC_17-20_KCNQ2_chr20:62066355-62071029:0-4675.
[13:43:33 - Feature] Processed BC_17-20_KCNQ2_chr20:62066355-62071029:0.0-4674.0 (median depth 1021.0)
[13:43:33 - Sampler] Took 0.74s to make features.
[13:43:40 - PWorker] All done, 0 remainder regions.
[13:43:40 - Predict] Finished processing all regions.
+ Running snp calling
- Running medaka snp
[13:43:42 - DataIndex] Loaded 1/1 (100.00%) sample files.
[13:43:42 - SNPs] Processing BC_17-20_KCNQ2_chr20:62066355-62071029.
Traceback (most recent call last):
  File "/home/qf0297/.conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/qf0297/.conda/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 643, in main
    args.func(args)
  File "/home/qf0297/.conda/envs/medaka/lib/python3.6/site-packages/medaka/variant.py", line 197, in snps_from_hdf
    reference=reg.ref_name).upper()
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence 'BC_17-20_KCNQ2_chr20' not present"
* Failed to call snps from consensus probabilities.`

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda
 - OS:Ubuntu 18.04
 - GPU model: No GPU

**Additional context**

**Comment by scogi** [comment]
Solved. The issue was that the reference sequence in the bam was named BC_17-20_KCNQ2_chr20:xxx-xxx (coming from the header of the fasta file used for alignment). Seemingly, medaka then searched only for the first part of the string and did not recognize the reference file correctly. Splitting it at the colon. Replacing all colons with an underscore and recreating the bam solved the issue.

**Comment by cjw85** [comment]
"Seemingly, medaka then searched only for the first part of the string and did not recognize the reference file correctly. Splitting it at the colon."

Yes, medaka has code that processes reference names, interpreting them as samtools-style region specifications.

**Comment by amir-r-v** [comment]
Hello everybody,
I am facing the same error KeyError: "sequence 'b'32871909-209b-4906-920e-05a2c48d1947'' not present"
Failed to stitch consensus chunks.
The problem is that I am trying to use the medaka as a part of a workflow called decona in a Conda environment.
I did not see any problem in the reference name but I don't know where the "b" (before the sequence name) in the error line comes from.
This is what I have done and the results:
(decona) wecopath@wecopath-XPS-15-9530:~/SEQ/amir2/guppy_hac_output/pass/extracted/1$ decona -l 1000 -m 6000 -q 10 -c 0.90 -n 50 -M -b db/small_database_aquarium.fasta 
Filtering data barcode83.fastq...
Data filtered with NanoFilt
Data not demultiplexed
total raw sequences = 1529
total filtered sequences = 1528
Fastq reads are being transformed to fasta
Transforming fastq to fasta Complete
Clustering reads...
Clustering barcode83/...
Clustering db/...
Clustering complete.
Aligning and making draft assembly of 118-10.fa...
[M::mm_idx_gen::0.001*2.20] collected minimizers
[M::mm_idx_gen::0.001*2.88] sorted minimizers
[M::main::0.001*2.85] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.001*2.80] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.001*2.76] distinct minimizers: 365 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.348
[M::worker_pipeline::0.012*3.43] mapped 118 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax map-ont -k15 -t 4 ref_118-10.fasta 118-10.fa
[M::main] Real time: 0.013 sec; CPU: 0.043 sec; Peak RSS: 0.004 GB
[racon::Polisher::initialize] loaded target sequences 0.000040 s
[racon::Polisher::initialize] loaded sequences 0.000876 s
[racon::Polisher::initialize] loaded overlaps 0.000750 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.000711 s
[racon::Polisher::initialize] transformed data into windows 0.000033 s
[racon::Polisher::polish] generated consensus 0.083964 s
[racon::Polisher::] total = 0.086550 s
Aligning and making draft assembly of 84-69.fa...
[M::mm_idx_gen::0.001*2.23] collected minimizers
[M::mm_idx_gen::0.001*2.60] sorted minimizers
[M::main::0.001*2.58] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*2.53] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*2.50] distinct minimizers: 351 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.573
[M::worker_pipeline::0.009*3.40] mapped 84 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax map-ont -k15 -t 4 ref_84-69.fasta 84-69.fa
[M::main] Real time: 0.009 sec; CPU: 0.031 sec; Peak RSS: 0.004 GB
[racon::Polisher::initialize] loaded target sequences 0.000082 s
[racon::Polisher::initialize] loaded sequences 0.000516 s
[racon::Polisher::initialize] loaded overlaps 0.000471 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.000496 s
[racon::Polisher::initialize] transformed data into windows 0.000021 s
[racon::Polisher::polish] generated consensus 0.042800 s
[racon::Polisher::] total = 0.044452 s
Done
Done
polishing 118-10.fa Racon sequence with Medaka...
Checking program versions
This is medaka 1.1.2
Program    Version    Required   Pass     
bcftools   1.17       1.9        True     
bgzip      1.17       1.9        True     
minimap2   2.17       2.11       True     
samtools   1.18       1.9        True     
tabix      1.17       1.9        True     
Aligning basecalls to draft
Removing previous index file /home/wecopath/SEQ/amir2/guppy_hac_output/pass/extracted/1/barcode83/multi-seq/polished_118-10.fasta.mmi
Removing previous index file /home/wecopath/SEQ/amir2/guppy_hac_output/pass/extracted/1/barcode83/multi-seq/polished_118-10.fasta.fai
Constructing minimap index.
[M::mm_idx_gen::0.002*1.89] collected minimizers
[M::mm_idx_gen::0.004*2.30] sorted minimizers
[M::main::0.007*1.85] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.007*1.83] distinct minimizers: 375 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.309
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /home/wecopath/SEQ/amir2/guppy_hac_output/pass/extracted/1/barcode83/multi-seq/polished_118-10.fasta.mmi /home/wecopath/SEQ/amir2/guppy_hac_output/pass/extracted/1/barcode83/multi-seq/polished_118-10.fasta
[M::main] Real time: 0.007 sec; CPU: 0.013 sec; Peak RSS: 0.003 GB
[M::main::0.002*1.70] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.002*1.66] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.002*1.63] distinct minimizers: 375 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.309
[M::worker_pipeline::0.023*3.27] mapped 118 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 4 -a -A 2 -B 4 -O 4,24 -E 2,1 /home/wecopath/SEQ/amir2/guppy_hac_output/pass/extracted/1/barcode83/multi-seq/polished_118-10.fasta.mmi /home/wecopath/SEQ/amir2/guppy_hac_output/pass/extracted/1/barcode83/multi-seq/118-10.fa
[M::main] Real time: 0.023 sec; CPU: 0.075 sec; Peak RSS: 0.005 GB
Running medaka consensus
[08:48:58 - Predict] Processing region(s): 32871909-209b-4906-920e-05a2c48d1947:0-1991
[08:48:58 - Predict] Using model: /home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[08:48:58 - Predict] Setting tensorflow threads to 4.
[08:48:58 - Predict] Processing 1 long region(s) with batching.
[08:48:58 - ModelStore] filepath /home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[08:48:58 - DLoader] Initializing data loader
[08:48:58 - PWorker] Running inference for 0.0M draft bases.
[08:48:58 - Sampler] Initializing sampler for consensus of region 32871909-209b-4906-920e-05a2c48d1947:0-1991.
[08:48:58 - Feature] Processed 32871909-209b-4906-920e-05a2c48d1947:0.0-1990.0 (median depth 118.0)
[08:48:58 - Sampler] Took 0.00s to make features.
[08:48:58 - Sampler] Region 32871909-209b-4906-920e-05a2c48d1947:0.0-1990.0 (3625 positions) is smaller than inference chunk length 10000, quarantining.
[08:48:58 - PWorker] All done, 1 remainder regions.
[08:48:58 - Predict] Processing 1 short region(s).
[08:48:58 - ModelStore] filepath /home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[08:48:59 - DLoader] Initializing data loader
[08:48:59 - PWorker] Running inference for 0.0M draft bases.
[08:48:59 - Sampler] Initializing sampler for consensus of region 32871909-209b-4906-920e-05a2c48d1947:0-1991.
[08:48:59 - Feature] Processed 32871909-209b-4906-920e-05a2c48d1947:0.0-1990.0 (median depth 118.0)
[08:48:59 - Sampler] Took 0.00s to make features.
[08:48:59 - PWorker] All done, 0 remainder regions.
[08:48:59 - Predict] Finished processing all regions.
Using medaka stitch to create consensus.
[08:49:00 - DataIndex] Loaded 1/1 (100.00%) sample files.
[08:49:00 - Stitch] Stitching regions: ['32871909-209b-4906-920e-05a2c48d1947:0-']
[08:49:00 - DataIndex] Loaded 1/1 (100.00%) sample files.
[08:49:00 - Stitch] Processing 32871909-209b-4906-920e-05a2c48d1947:0-.
[08:49:00 - Stitch] Used heuristic 0 times for 32871909-209b-4906-920e-05a2c48d1947:0-.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/stitch.py", line 133, in _stitcher
    return fill_gaps(contigs, draft)
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/stitch.py", line 117, in fill_gaps
    draft_seq = draft.fetch(ref_name)
  File "pysam/libcfaidx.pyx", line 301, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence 'b'32871909-209b-4906-920e-05a2c48d1947'' not present"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wecopath/miniconda3/envs/decona/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/medaka.py", line 669, in main
    args.func(args)
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/site-packages/medaka/stitch.py", line 152, in stitch
    for contigs, gap_tree in executor.map(worker, rgrps):
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/wecopath/miniconda3/envs/decona/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: "sequence 'b'32871909-209b-4906-920e-05a2c48d1947'' not present"
Failed to stitch consensus chunks.
Could you please kindly give me a clue regarding this issue?
