### ISSUE TITLE
Installing medaka from source errors when installed within singularity container image

### ISSUE THREAD

**Issue by KasperSkytte** [nanoporetech/medaka#219]
**Describe the bug**
When trying to install medaka from source (due to GPU support) within a singularity container image the installation fails at Makefile target `check_lfs`. By inspecting the `Makefile` and `setup.py` I assume this means it cannot find either `git-lfs` or the model files in the python virtual environment. I have installed `git-lfs` in every possible way now. `git-lfs` is available in `$PATH` (in `/usr/bin/`) and I have run the `git lfs install` before installing medaka. When not installing medaka within a container image (ie on the same host) I can install without issues (exact same commands).

**Logging**
I spared you the output from the `apt-get` commands and until `make install`, but left the commands run.
```
+ apt-get update -y
+ apt-get install -y --no-install-recommends --no-install-suggests \
+ bzip2 g++ zlib1g-dev libbz2-dev liblzma-dev libffi-dev libncurses5-dev \
+ libcurl4-gnutls-dev libssl-dev curl make cmake wget python3-all-dev \
+ virtualenv python3-virtualenv ca-certificates git-lfs
+ git clone https://github.com/nanoporetech/medaka.git
+ cd medaka
+ git checkout f125315
+ sed -i 's/tensorflow/tensorflow-gpu/' requirements.txt
+ make install
test -d venv || virtualenv venv --python=python3 --prompt "(medaka) "
Running virtualenv with interpreter /opt/miniconda/bin/python3
Using base prefix '/opt/miniconda'
/usr/lib/python3/dist-packages/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /medaka/venv/bin/python3
Also creating executable in /medaka/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
. ./venv/bin/activate && pip install pip --upgrade
Requirement already up-to-date: pip in ./venv/lib/python3.8/site-packages (20.2.4)
. ./venv/bin/activate && python -c "from setup import check_model_lfs; check_model_lfs()"
Bundling models: ['r103_min_high_g345', 'r103_min_high_g360', 'r103_prom_high_g360', 'r103_prom_snp_g3210', 'r103_prom_variant_g3210', 'r10_min_high_g303', 'r10_min_high_g340', 'r941_min_fast_g303', 'r941_min_high_g303', 'r941_min_high_g330', 'r941_min_high_g340_rle', 'r941_min_high_g344', 'r941_min_high_g351', 'r941_min_high_g360', 'r941_prom_fast_g303', 'r941_prom_high_g303', 'r941_prom_high_g330', 'r941_prom_high_g344', 'r941_prom_high_g360', 'r941_prom_high_g4011', 'r941_prom_snp_g303', 'r941_prom_snp_g322', 'r941_prom_snp_g360', 'r941_prom_variant_g303', 'r941_prom_variant_g322', 'r941_prom_variant_g360']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/medaka/setup.py", line 48, in check_model_lfs
    stdout = subprocess.check_output(['file', default_model])
  File "/opt/miniconda/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/miniconda/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/miniconda/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/miniconda/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
Makefile:127: recipe for target 'check_lfs' failed
make: *** [check_lfs] Error 1
FATAL:   While performing build: while running engine: exit status 2
Makefile:3: recipe for target 'main' failed
make: *** [main] Error 255
```

**Environment (if you do not have a GPU, write No GPU):**
 - installation method: source
 - OS: Ubuntu 18.04
 - GPU model: nvidia geforce RTX2080 super
 - Nvidia driver version: nvidia-driver-440
 - CUDA version: 10.2
 - cuDNN version: N/A

**Additional context**

**Comment by cjw85** [comment]
The error 
    FileNotFoundError: [Errno 2] No such file or directory: 'file'
looks like the command `file` isn't being found on the system when the setup function `check_model_lfs` is running. Perhaps you need to `apt install file`?

**Comment by KasperSkytte** [comment]
Thank you, that solved the issue, I could proceed after installing `file`. Tensorflow 2.2 required h5py version 2.10.0 though, so I had to also do a `sed -i 's/h5py/h5py==2.10.0/' requirements.txt` before running `make install`. Maybe you have to update `requirements.txt`?
