### ISSUE TITLE
Failed to stitch consensus chunks.

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/medaka#22]
Hi, 

When running medaka, the stitching step seems to run into some kind of exceptions with the assembly we have: 

```
[03:18:31 - Stitch] Processing ctg1641.
[03:18:34 - Stitch] Processing ctg1642.
[03:18:42 - Stitch] There is no overlap betwen ctg1642:32609.1-37277.1643 and ctg1642:37276.3367-41429.0
[03:18:43 - Stitch] ctg1642:37276.644-39589.1 ends before ctg1642:37276.3367-41429.0, skipping.
ctg127:259136.66-261946.5049 and ctg127:261945.13050-264482.0 do not overlap
ctg148:271139.1918-271157.3508 and ctg148:271156.11509-273932.0 do not overlap
ctg149:1355570.47-1356768.7744 and ctg149:1356767.15745-1362547.0 do not overlap
ctg1642:32609.1-37277.1643 and ctg1642:37276.3367-41429.0 do not overlap
Traceback (most recent call last):
 File "/local/genome/packages/anaconda3/latest/bin/medaka", line 11, in <module>
   sys.exit(main())
 File "/mnt/users/tinagr/.local/lib/python3.6/site-packages/medaka/medaka.py", line 213, in main
   args.func(args)
 File "/mnt/users/tinagr/.local/lib/python3.6/site-packages/medaka/stitch.py", line 80, in stitch
   joined = stitch_from_probs(args.inputs, regions=args.regions)
 File "/mnt/users/tinagr/.local/lib/python3.6/site-packages/medaka/stitch.py", line 71, in stitch_from_probs
   logger.info(msg.format(s1.name, s2.name))
AttributeError: 'NoneType' object has no attribute 'name'
Failed to stitch consensus chunks.
```

I thought its similar to #20 , but we are using version medaka 0.5.0 already. 

command used: 
```
DRAFT=wtdbg2-medakaPolish_p19-k0-L10k-AS3-s0p05-e3.ctg.fa
BASECALLS=1-fastp-guppyNewVer-Recall-bases/Cod.recalled.4kb.q7.50h.fastq.gz
OUTDIR=medaka_trial_j

medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t 25 -m 'r941_flip'
```
Thank you, 
Michel

**Comment by cjw85** [comment]
Hi @MichelMoser 

We are aware of some similar issues, and should have a fix shortly.

**Comment by cjw85** [comment]
Version v0.5.2 is now available on the [release page](https://github.com/nanoporetech/medaka/releases/tag/v0.5.2), or via [pypi](https://pypi.org/project/medaka/).

**Comment by MichelMoser** [comment]
Thank you very much, will test it.

**Comment by cgjosephlee** [comment]
Hi @cjw85 
We had same issue with OP using 0.5.0. We further tried 0.5.2 and there was another issue.
Both 0.5.0 and 0.5.2 stopped at the same contig.

```
$ medaka stitch consensus_probs.hdf consensus_ctg1414.fa --regions ctg1414
[15:27:20 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
[15:27:21 - Stitch] Ignoring start:end for 'ctg1414:None-None'.
[15:27:21 - Stitch] Processing ctg1414.
ctg1414:15595.2-20254.1538 and ctg1414:20253.1643-25384.0 do not overlap
[15:28:29 - Stitch] There is no overlap betwen ctg1414:15595.2-20254.1538 and ctg1414:20253.1643-25384.0
[15:28:30 - Stitch] ctg1414:20253.539-24661.1 ends before ctg1414:20253.1643-25384.0, skipping.
[15:28:30 - Stitch] There is no overlap betwen ctg1414:20253.1643-25384.0 and Unknown
Traceback (most recent call last):
  File "/home/hsinhan97/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/hsinhan97/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 213, in main
    args.func(args)
  File "/home/hsinhan97/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 83, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/home/hsinhan97/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 75, in stitch_from_probs
    start = get_pos(s2, 0)
  File "/home/hsinhan97/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 42, in <lambda>
    get_pos = lambda s, i: '{}.{}'.format(s.positions[i]['major'] + 1, s.positions[i]['minor'])
AttributeError: 'NoneType' object has no attribute 'positions'
```
ps. the `consensus_probs.hdf` was produced by 0.5.0, will it be a problem?

**Comment by cjw85** [comment]
@cgjosephlee,

There was an underlying issue which affected how `consensus_probs.hdf` was created: some sub-regions were being dropped. This has been fixed.

The issue had knock-on consequences for the `medaka stitch` command, which we tried to make more robust. In our haste we evidently did not catch all the corner cases to which the above bug could lead. (We need to add more testing around this code).

If it is not too onerous my suggestion would be to regenerate `consensus_probs.hdf` with version 0.5.2; this will fix the problem that `medaka stitch` is having at source.

**Comment by cgjosephlee** [comment]
@cjw85,
Thank you for the reply. We had rerun with 0.5.2 but unfortunately had no luck. But 0.4.3 gave us a successful run.

**Comment by rfinkers** [comment]
running into similar? problems with v0.6.2

utg12659:140077.1964-140100.1222 and utg12659:140099.1283-145573.0 do not overlap
[06:29:26 - Stitch] There is no overlap betwen utg12659:140077.1964-140100.1222 and utg12659:140099.1283-145573.0
[06:29:27 - Stitch] utg12659:140099.223-144811.1 ends before utg12659:140099.1283-145573.0, skipping.
[06:29:27 - Stitch] There is no overlap betwen utg12659:140099.1283-145573.0 and Unknown
Traceback (most recent call last):
  File "/media/bulk_01/users/finke002/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/media/bulk_01/users/finke002/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 261, in main
    args.func(args)
  File "/media/bulk_01/users/finke002/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 342, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/media/bulk_01/users/finke002/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 78, in stitch_from_probs
    start = get_pos(s2, 0)
  File "/media/bulk_01/users/finke002/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 45, in <lambda>
    get_pos = lambda s, i: '{}.{}'.format(s.positions[i]['major'] + 1, s.positions[i]['minor'])
AttributeError: 'NoneType' object has no attribute 'positions'
Failed to stitch consensus chunks.

**Comment by eernst** [comment]
I'm seeing the same error on three independent datasets with 0.6.2, default options except -m r941_flip235, 32 threads.

**Comment by cjw85** [comment]
Hi @rfinkers and @eernst 

I believe we have a fix for this case coming (hopefully) tomorrow.

**Comment by cjw85** [comment]
A v0.6.3 package is now available from github and pypi, a conda package is waiting for a resolution to an issue in bioconda (https://github.com/bioconda/bioconda-recipes/issues/14433). This resolves an issue where only a single consensus chunk is present in the probabilities HDF file.

Running `medaka stitch <output>/consensus_probs.hdf <output>/consensus.fasta` should be sufficient.

**Comment by rfinkers** [comment]
tnx, will try
