### ISSUE TITLE
RuntimeError: Filepath for '--bam' argument does not exist (10)

### ISSUE THREAD

**Issue by shaqpl** [nanoporetech/medaka#220]
**Describe the bug**
One day medaka just stopped working. I tried using old versions od medaka with hope that GPU is a problem but not, same error. Any sugestions? 

**Logging**
Traceback (most recent call last):
  File "/home/shaq/miniconda3/envs/medaka_old2/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/site-packages/medaka/medaka.py", line 568, in main
    args = parser.parse_args()
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/shaq/miniconda3/envs/medaka_old2/lib/python3.6/site-packages/medaka/medaka.py", line 97, in __call__
    self.dest, values)
RuntimeError: Filepath for '--bam' argument does not exist (10)

**Environment No GPU or with 1080ti**
 - Installation method  pypi (pip install) or  conda
 - OS: Ubuntu 18.04
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by owenwilkins** [comment]
also receiving this error, but bam fie is definitely there and path is correct. have also run from current directory of bam file and same error
