### ISSUE TITLE
choice of model for Guppy 4.0.14 

### ISSUE THREAD

**Issue by dcopetti** [nanoporetech/medaka#223]
Hello,
Not a bug here, just a question.

I would like to use `medaka `(1.1.1 or 1.1.2) to call SNPs (`medaka_variant`, small indels would be good too) from an alignment (PromethION reads called with Guppy 4.0.14). My goal is to phase SNPs and SVs in blocks as large as possible.
What model can I use, since I don't see the `_snp_` equivalent of `r941_prom_high_g4011`? What is the difference between `_snp_` and `_variant_`? do I need to run independently the SNP and SV search then?
Would the newest medaka have models for the Guppy 4.0.N series?

Also, I would like to focus on ~880 regions (of a 4 Gb assembly): what will work best between having all the regions in the -r parameter (difficult, or I could run 880 jobs, one for each region), or having a bam with only reads mapped to those regions? As an alternative, it would be convenient to be able to enter the regions for -r in a bed file. 
Thanks,

DarioDario

**Comment by cjw85** [comment]
medaka is not designed to find SVs, though it may incidentally pick up some small (10s of bases indels).

The `_snp` and `_variant` models are used internally by the `medaka_variant` workflow to produce respectively het SNP calls prior to phasing and computer a haplotype consensus sequences.

Multiple regions can be given as `medaka_variant ... -r "chr1:1000-10000 chr2-5000-20000"`. The program doesn't accept a BED file unfortunately so you will have to use some shell logic to massage a single string. The workflow first extracts the regions of interest from the BAM so there is no need to do this ahead of time.

**Comment by dcopetti** [comment]
Thanks,
I tried running
`medaka_variant ... -r 'OF1p3c_SSc_Bd_SSc_all_1:320000-520000 OF1p3c_SSc_Bd_SSc_all_1:770000-970000' -i file.bam`
and I get 
```[...]
++ Running first pass to haplotag reads.
+ Running consensus calling
- Running medaka consensus with rawall_G4_to_Rab_for_Whaps_880_slops.bam --model /home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/medaka/data/r941_prom_snp_g360_model.hdf5
[14:40:18 - Predict] Reducing threads to 2, anymore is a waste.
[14:40:18 - Predict] Setting tensorflow inter/intra-op threads to 2/1.
[14:40:18 - Predict] Processing region(s): OF1p3c_SSc_Bd_SSc_all_1:320000-520000 OF1p3c_SSc_Bd_SSc_all_1:770000-970000
[14:40:18 - Predict] Using model: /home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/medaka/data/r941_prom_snp_g360_model.hdf5.
[14:40:18 - Predict] Processing 2 long region(s) with batching.
[14:40:18 - ModelStore] filepath /home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/medaka/data/r941_prom_snp_g360_model.hdf5
[14:40:19 - DLoader] Initializing data loader
[14:40:19 - PWorker] Running inference for 0.4M draft bases.
[14:40:19 - Sampler] Initializing sampler for consensus of region OF1p3c_SSc_Bd_SSc_all_1:320000-520000.
[14:40:19 - Sampler] Initializing sampler for consensus of region OF1p3c_SSc_Bd_SSc_all_1:770000-970000.
[14:40:19 - Sampler] Took 0.04s to make features.
[14:40:19 - Feature] Pileup counts do not span requested region, requested OF1p3c_SSc_Bd_SSc_all_1:320000-520000, received 399853-465420.
[14:40:19 - Feature] Processed OF1p3c_SSc_Bd_SSc_all_1:399853.0-465420.0 (median depth 57.0)
[14:40:19 - Sampler] Took 0.50s to make features.
[14:40:25 - PWorker] All done, 0 remainder regions.
[14:40:25 - Predict] Finished processing all regions.
+ Running snp calling
- Running medaka snp
WARNING: This program can only process entire contigs, ignoring region start and end coordinates.
[14:40:26 - DataIndex] Loaded 1/1 (100.00%) sample files.
[14:40:26 - SNPs] Processing OF1p3c_SSc_Bd_SSc_all_1:0-.
/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/medaka/labels.py:381: RuntimeWarning: divide by zero encountered in log10
  q = -10 * np.log10(err)
[14:40:28 - SNPs] Processing OF1p3c_SSc_Bd_SSc_all_1:0-.
  VCF written to rtest/round_0_hap_mixed_unphased.vcf.
+ Phasing vcf
+ Indexing fasta
- Using existing output:  rtest//home/copettid/public/Flye_assemblies_Dario/Rabiosa_scaffolding/whatshap/scf1-10.fa.fai.
- Running whatshap phase for: round_0_hap_mixed_unphased.vcf > round_0_hap_mixed_phased.vcf.
This is WhatsHap 1.0 running under Python 3.8.6
Working on 1 samples from 1 family
Traceback (most recent call last):
  File "/home/copettid/miniconda3/envs/medaka1.1.3/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/whatshap/cli/phase.py", line 414, in run_whatshap
    for variant_table in timers.iterate("parse_vcf", vcf_reader):
  File "/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/whatshap/timer.py", line 51, in iterate
    for item in iterator:
  File "/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/whatshap/vcf.py", line 398, in __iter__
    yield self._process_single_chromosome(chromosome, records)
  File "/home/copettid/miniconda3/envs/medaka1.1.3/lib/python3.8/site-packages/whatshap/vcf.py", line 445, in _process_single_chromosome
    raise VcfNotSortedError(
whatshap.vcf.VcfNotSortedError: VCF not ordered: OF1p3c_SSc_Bd_SSc_all_1:465338 appears before OF1p3c_SSc_Bd_SSc_all_1:399998
* Failed to phase variants in round_0_hap_mixed_unphased.vcf.```


and the round_0_hap_mixed_unphased.vcf looks to be not phased:
```##fileformat=VCFv4.1
##medaka_version=1.1.3
##contig=<ID=OF1p3c_SSc_Bd_SSc_all_1,length=95092000>
##contig=<ID=OF1p3c_SSc_Bd_SSc_all_1,length=95092000>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Medaka genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Medaka genotype quality score">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
OF1p3c_SSc_Bd_SSc_all_1 399998  .       T       C       5.941   PASS            GT:GQ   0/1:6
OF1p3c_SSc_Bd_SSc_all_1 400024  .       A       G       11.108  PASS            GT:GQ   0/1:11
OF1p3c_SSc_Bd_SSc_all_1 400056  .       T       C       12.435  PASS            GT:GQ   0/1:12
OF1p3c_SSc_Bd_SSc_all_1 400300  .       T       C       5.53    PASS            GT:GQ   1/1:6
OF1p3c_SSc_Bd_SSc_all_1 400533  .       A       G       10.701  PASS            GT:GQ   1/1:11
OF1p3c_SSc_Bd_SSc_all_1 400554  .       A       G       3.081   PASS            GT:GQ   0/1:3
OF1p3c_SSc_Bd_SSc_all_1 400788  .       A       G       7.446   PASS            GT:GQ   0/1:7
OF1p3c_SSc_Bd_SSc_all_1 401019  .       T       C       16.108  PASS            GT:GQ   0/1:16
OF1p3c_SSc_Bd_SSc_all_1 401089  .       A       G       44.323  PASS            GT:GQ   0/1:44
[...]
OF1p3c_SSc_Bd_SSc_all_1 464552  .       T       C       4.26    PASS            GT:GQ   1/1:4
OF1p3c_SSc_Bd_SSc_all_1 464637  .       T       C       10.393  PASS            GT:GQ   0/1:10
OF1p3c_SSc_Bd_SSc_all_1 465047  .       T       C       22.306  PASS            GT:GQ   0/1:22
OF1p3c_SSc_Bd_SSc_all_1 465338  .       T       C       23.853  PASS            GT:GQ   1/1:24
OF1p3c_SSc_Bd_SSc_all_1 399998  .       T       C       5.941   PASS            GT:GQ   0/1:6
OF1p3c_SSc_Bd_SSc_all_1 400024  .       A       G       11.108  PASS            GT:GQ   0/1:11
OF1p3c_SSc_Bd_SSc_all_1 400056  .       T       C       12.435  PASS            GT:GQ   0/1:12
OF1p3c_SSc_Bd_SSc_all_1 400300  .       T       C       5.53    PASS            GT:GQ   1/1:6
OF1p3c_SSc_Bd_SSc_all_1 400533  .       A       G       10.701  PASS            GT:GQ   1/1:11
OF1p3c_SSc_Bd_SSc_all_1 400554  .       A       G       3.081   PASS            GT:GQ   0/1:3
OF1p3c_SSc_Bd_SSc_all_1 400788  .       A       G       7.446   PASS            GT:GQ   0/1:7
OF1p3c_SSc_Bd_SSc_all_1 401019  .       T       C       16.108  PASS            GT:GQ   0/1:16```
it actually looks like the lines are duplicated (also by `sort round_0_hap_mixed_unphased.vcf | uniq -c | more` all non-header lines are present twice)
I will run separately these jobs for now.

(in your comment above I think there is a typo in the second interval - the ":" is missing. If I try to run my command with that syntax, it dies earlier with `KeyError: 'Contig OF1p3c_SSc_Bd_SSc_all_1-770000-970000 is not one of the bam references.'`)
