### ISSUE TITLE
0.6.0-alpha.1 version ModuleNotFoundError

### ISSUE THREAD

**Issue by damientully** [nanoporetech/medaka#24]
Hi,

I am trying to run the 0.6.0-alpha.1 version of medaka to look at variant calling. I installed from source but upon running I get the following error:

```
Running medaka consensus /home/dct7/medaka/scripts/test.reads.sorted.bam
======================================

Traceback (most recent call last):
  File "/home/dct7/medaka/venv/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.6.0a1', 'console_scripts', 'medaka')()
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/medaka-0.6.0a1-py3.6.egg/medaka/medaka.py", line 11, in <module>
    from medaka.inference import train, predict
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/medaka-0.6.0a1-py3.6.egg/medaka/inference.py", line 22, in <module>
    from medaka.features import SampleGenerator
  File "/home/dct7/medaka/venv/lib/python3.6/site-packages/medaka-0.6.0a1-py3.6.egg/medaka/features.py", line 23, in <module>
    import libmedaka
ModuleNotFoundError: No module named 'libmedaka'
Failed to run medaka consensus.
``` 

Any suggestions?

Many thanks,
Damien

**Comment by cjw85** [comment]
Hi @damientully 

Thanks for trying our alpha release, and sorry that it has not installed smoothly.

We have noticed this. Something in the python build chain is becoming confused; on failing to build whatshap the build of the libmedaka module is also being neglected.

We have [asked](https://bitbucket.org/whatshap/whatshap/issues/178/update-pypi-release) the whatshap developers to create a new release, which will make this simpler.

Here's what I did this morning to get things working:

    # grab medaka and whatshap sources
    git clone git@github.com:nanoporetech/medaka.git
    git clone https://bitbucket.org/whatshap/whatshap
    cd medaka
    # remove whatshap as a requirement
    sed -i 's/git\+/#git\+/' requirements.txt
    make install
    source venv/bin/activate
    cd ../whatshap
    pip install pyvcf
    python setup.py install

I hope this gets you a working install, and look forward to seeing any variant calling results that you produce.

**Comment by damientully** [comment]
Hi @cjw85 

Thanks for your reply and those instructions. Seems to be working now!
Damien

**Comment by cjw85** [comment]
The `v0.6.0-alpha.2` now depends on `whatshap==0.18` and builds correctly.

It is available with pip, needing the `--pre` option to opt-in to prereleases:

    pip install --pre medaka
