### ISSUE TITLE
OSError: Unable to open file (unable to lock file...)

### ISSUE THREAD

**Issue by snayfach** [nanoporetech/medaka#240]
I've installed the program using conda and have run it to completion without errors on a small test dataset. The installation was on the login node of my institutes' computing cluster, which is the standard procedure. However, when run from a compute node the program crashes:

```
> medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC}

Checking program versions
This is medaka 1.2.1
Program    Version    Required   Pass
bcftools   1.10.2     1.9        True
bgzip      1.10.2     1.9        True
minimap2   2.17       2.11       True
samtools   1.10       1.9        True
tabix      1.10.2     1.9        True
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 675, in main
    args.func(args)
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 249, in is_rle_model
    print(is_rle_encoder(args.model))
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 256, in is_rle_encoder
    encoder = modelstore.get_meta('feature_encoder')
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 86, in get_meta
    with DataStore(self.filepath) as ds:
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 203, in __init__
    self.fh = h5py.File(self.filename, self.mode)
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/global/homes/s/snayfach/.conda/envs/medaka/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 524, error message = 'Unknown error 524')
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda
 - OS: SUSE Linux Enterprise Server 15
 - GPU model: no GPU
 - Nvidia driver version: unsure
 - CUDA version: unsure
 - cuDNN version: unsure

**Comment by snayfach** [comment]
Looking at closed issues, I found the solution was to use:
`export HDF5_USE_FILE_LOCKING='FALSE'`

This worked for me. So it seems this can be necessary when running on a compute cluster. Would suggest adding to the docs to save users time in the future.
