### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Kirk3gaard** [nanoporetech/medaka#242]
**Describe the bug**
When running the "medaka consensus" command on a metagenome assembly created with flye and polished with racon I get the error message "RuntimeError: can't start new thread". I have also experienced the problem when running running on CPUs and with the "medaka_consensus" command and default settings. Hope you can give me a hint how to fix this.
Command:
medaka consensus --debug calls_to_draft.bam contigs.hdf --model r941_prom_high_g4011 --batch 100

**Logging**
Full log here https://www.dropbox.com/s/tkuud917jeqm0uu/GPU_medaka_PROM-333979.err?dl=0
Error message here:
[23:05:19 - Sampler] Initializing sampler for consensus of region contig_5042:1299-3929.
Exception in thread Thread-10327:
Traceback (most recent call last):
  File "/apps/python3/3.8.5/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/apps/python3/3.8.5/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/prediction.py", line 331, in _fill_parallel
    samples, remain = fut.result()
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/prediction.py", line 342, in _run_region
    return data_gen.samples, data_gen._quarantined
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/features.py", line 736, in samples
    self._fill_features()
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/features.py", line 716, in _fill_features
    self._source = self.fencoder.bam_to_sample(
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/features.py", line 363, in bam_to_sample
    pileups = self._pileup_function(region, reads_bam)
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/features.py", line 446, in _pileup_function
    return pileup_counts(
  File "/apps/python3/3.8.5/lib/python3.8/site-packages/medaka/features.py", line 186, in pileup_counts
    results = executor.map(_process_region, regions)
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/_base.py", line 600, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/thread.py", line 188, in submit
    self._adjust_thread_count()
  File "/apps/python3/3.8.5/lib/python3.8/concurrent/futures/thread.py", line 213, in _adjust_thread_count
    t.start()
  File "/apps/python3/3.8.5/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

 - GPU model Tesla T4
 - Nvidia driver version (could not find this)
 - CUDA version 10.1.243
 - cuDNN version (could not find this)

**Additional context**

**Comment by cjw85** [comment]
Hi @Kirk3gaard,

Thanks for reporting this. We don't do much testing on Python 3.8 so I'm suspecting this might be the cause. Can you try running under Python 3.6 to check if you see similar issues?

**Comment by Kirk3gaard** [comment]
Hi @cjw85 
Ok I will see if I can convince my sys admin to install it with python 3.6.

**Comment by Kirk3gaard** [comment]
Hi @cjw85 
I got my sysadmin to install everything with python3.6 but medaka consensus stalls as it seems to open a lot of files and keep them open  (1.010.920 files). The assembly only has 28011 contigs so it seems like something fishy is going on here. Is there a way to limit medaka from opening this many files?

**Comment by Kirk3gaard** [comment]
I tried to run it on a different cluster with the same data and it works great. I therefore assume that this is something server specific rather than a medaka issue. Thanks for your input.
