### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by niederhuth** [nanoporetech/medaka#246]
During the 'stitch' step of medaka_consensus, medaka stops after processing most of the contigs and returns an error. I am running this using a conda installation and only a few days ago it worked without a problem on a different sample. I am using medaka 1.2.1 with python3.8. Thanks.

Here are the error messages I am recieving:

[13:08:37 - TrimOverlap] contig_19732:27.0-310.0 and contig_19732:521.0-4934.0 cannot be concatenated as there is no overlap and they do not abut.
[13:08:37 - TrimOverlap] contig_19732:521.0-4934.0 and contig_19732:5061.0-14583.0 cannot be concatenated as there is no overlap and they do not abut.
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/common.py", line 425, in trim_samples
    s1 = next(sample_gen)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/stitch.py", line 58, in stitch_from_probs
    for s, is_last_in_contig, heuristic in data_gen:
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/common.py", line 485, in trim_samples_to_region
    sample, last, heuristic = next(samples)
RuntimeError: generator raised StopIteration
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/niederhu/miniconda3/envs/assembly/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/medaka.py", line 675, in main
    args.func(args)
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/stitch.py", line 182, in stitch
    contigs, gt = fill_gaps(contigs, args.draft)
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/stitch.py", line 92, in fill_gaps
    for info, sequence_parts in contigs:
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/site-packages/medaka/stitch.py", line 133, in collapse_neighbours
    for contig in contigs:
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/mnt/home/niederhu/miniconda3/envs/assembly/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
RuntimeError: generator raised StopIteration

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: [e.g. Ubuntu 16.04]
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Hi @niederhuth,

This looks like it might be a new issue introduced when the `medaka stitch` sub-command was given multiprocessing abilities. Could you possibly try running:

    medaka stitch consensus_probs.hdf draft.fa consensus.fasta

where `consensus_probs.hdf` has been generate by the previous step of `medaka_consensus`, `draft.fa` is the input sequence you are attempting to correct with medaka, and `consensus.fasta` will be the output sequence file.

If this runs successfuly, try adding the `--threads 2` option to the above command. I suspect this will then fail
