### ISSUE TITLE
Stitching fails with IndexError

### ISSUE THREAD

**Issue by dustin-cram** [nanoporetech/medaka#250]
**Describe the bug**
While running medaka_consensus the error message below is produced during the 'medaka stitch' phase. 

**Logging**

```
...<snip>...
[13:42:38 - TrimOverlap] utg5723:1231440.0-1239450.0 and utg5723:1244901.0-1251950.0 cannot be concatenated as there is no overlap and they do not abut.
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 64, in stitch_from_probs
    (s.ref_name, start, s.positions[-1]['major']),
IndexError: index -1 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/ppl/cram/conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 675, in main
    args.func(args)
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 182, in stitch
    contigs, gt = fill_gaps(contigs, args.draft)
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 92, in fill_gaps
    for info, sequence_parts in contigs:
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 133, in collapse_neighbours
    for contig in contigs:
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/storage/ppl/cram/conda/envs/medaka/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
IndexError: index -1 is out of bounds for axis 0 with size 0

```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: medaka 1.2.1 via conda initially, but also tried 1.2.2rc1 via pip - same error
 - OS: Ubuntu 18.04
 - GPU Model:  No GPU
 

**Additional context**

**Comment by dustin-cram** [comment]
In case anybody else experiences this issue, I worked around it by using an older version of medaka stitch (1.1.3) on the consensus_probs.hdf produced by medaka 1.2.2.  I'm thinking this produces the same output that 1.2.2 would have, but just runs a bit slower?

**Comment by cjw85** [comment]
Hi @dustin-cram,

This is correct. The version of the stitch command in medaka 1.2.2 uses multiprocessing to improve performance. We appear to have introduced a few bugs in some data edge cases in this process. We believe we have fixed most of these in a pre-release version of medaka. Is it possible that you can share your `consensus_probs.hdf` file for us to perform further tests?

**Comment by dustin-cram** [comment]
Unfortunately the data is from client material and were are unable to share.  I will keep an eye on future releases.

**Comment by harmeet1990** [comment]
Had the same issue. Used medaka stitch (1.1.3) as a workaround.

**Comment by cjw85** [comment]
@harmeet1990,

Can you share an example consensus_probs.hdf file from a medaka output directory that leads to this error?

**Comment by harmeet1990** [comment]
> @harmeet1990,
> 
> Can you share an example consensus_probs.hdf file from a medaka output directory that leads to this error?

Sure but the .hdf files are quite big between 1.5 to 2.5 Gb. Can I upload them somewhere for you?

**Comment by cjw85** [comment]
You can email me at chris.wright@nanoporetech.com and I will send further instructions.

**Comment by cjw85** [comment]
Hi have files from @harmeet1990 and can reproduce the error. We will have a fix in due course.

**Comment by wjj666** [comment]
Hi @dustin-cram,
I had the same issue.
medaka_consensus works on test data.

But when I use medaka_consensus on 3G fasta file, it leads to the same error:
IndexError: index -1 is out of bounds for axis 0 with size 0
Failed to stitch consensus chunks.

medaka 1.2.5
installation method: conda create -n medaka -c conda-forge -c bioconda medaka

Could you please help me solve this problem?
