### ISSUE TITLE
This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

### ISSUE THREAD

**Issue by Sumsarium** [nanoporetech/medaka#256]
Hi @cjw85 ,

I am having a problem with medaka. Can't quite figure what might be wrong and got the same error in Ubuntu 18.04 LTS (RTX2080, CUDA version 11.2) and 20.04 LTS (RTX3070, CUDA version 11.2) 

Any suggestions? Any help would be much appreciated!

```
Checking program versions
This is medaka 1.2.2
Program    Version    Required   Pass     
bcftools   1.11       1.9        True     
bgzip      1.11       1.9        True     
minimap2   2.17       2.11       True     
samtools   1.11       1.9        True     
tabix      1.11       1.9        True     
Aligning basecalls to draft
Removing previous index file /home/rwo/Desktop/Assembly_3x/racon1_output.fasta.mmi
Removing previous index file /home/rwo/Desktop/Assembly_3x/racon1_output.fasta.fai
Constructing minimap index.
[M::mm_idx_gen::0.157*1.01] collected minimizers
[M::mm_idx_gen::0.210*1.50] sorted minimizers
[M::main::0.256*1.41] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.266*1.39] distinct minimizers: 1239059 (98.41% are singletons); average occurrences: 1.022; average spacing: 5.355
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /home/rwo/Desktop/Assembly_3x/racon1_output.fasta.mmi /home/rwo/Desktop/Assembly_3x/racon1_output.fasta
[M::main] Real time: 0.272 sec; CPU: 0.378 sec; Peak RSS: 0.067 GB
[M::main::0.054*1.02] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.068*1.01] mid_occ = 9
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.079*1.01] distinct minimizers: 1239059 (98.41% are singletons); average occurrences: 1.022; average spacing: 5.355
[M::worker_pipeline::7.806*10.36] mapped 56790 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 14 -a -A 2 -B 4 -O 4,24 -E 2,1 /home/rwo/Desktop/Assembly_3x/racon1_output.fasta.mmi /home/rwo/Desktop/Assembly_3x/input/allreads3.fastq
[M::main] Real time: 7.812 sec; CPU: 80.896 sec; Peak RSS: 1.036 GB
[bam_sort_core] merging from 0 files and 14 in-memory blocks...
Running medaka consensus
[22:31:10 - Predict] Reducing threads to 2, anymore is a waste.
[22:31:10 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.
[22:31:10 - Predict] Setting tensorflow inter/intra-op threads to 2/1.
[22:31:10 - Predict] Processing region(s): contig_1:0-6782674
[22:31:10 - Predict] Using model: /home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/data/r103_min_high_g345_model.hdf5.
[22:31:10 - Predict] Processing 7 long region(s) with batching.
[22:31:10 - ModelStore] filepath /home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/data/r103_min_high_g345_model.hdf5
[22:31:11 - ModelStore] ModelStore exception <class 'NotImplementedError'>
Traceback (most recent call last):
  File "/home/rwo/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 684, in main
    args.func(args)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/prediction.py", line 157, in predict
    model = model_store.load_model(time_steps=args.chunk_len)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 77, in load_model
    model = model_partial_function(time_steps=time_steps)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/models.py", line 146, in build_model
    model.add(Bidirectional(gru, input_shape=input_shape))
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 206, in add
    layer(x)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 530, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 643, in call
    y = self.forward_layer(forward_inputs,
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 663, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 409, in call
    inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 862, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 645, in get_initial_state
    init_state = get_initial_state_fn(
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 1953, in get_initial_state
    return _generate_zero_filled_state_for_cell(self, inputs, batch_size, dtype)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2968, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2986, in _generate_zero_filled_state
    return create_zeros(state_size)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2981, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2747, in wrapped
    tensor = fun(*args, **kwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2794, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2732, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/rwo/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 845, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_gru1/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
Failed to run medaka consensus.
```

Here is the output from conda list: 

```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_tflow_select             2.3.0                     eigen  
absl-py                   0.11.0           py38h578d9bd_0    conda-forge
aiohttp                   3.7.3            py38h497a2fe_1    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
bcftools                  1.11                 h7c999a4_0    bioconda
biopython                 1.78             py38h497a2fe_1    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.1              pyhd8ed1ab_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.4           py38ha65f79e_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cryptography              3.4.4            py38h3e25421_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
gast                      0.3.3                      py_0    conda-forge
google-auth               1.24.0             pyhd3deb0d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.35.0           py38hdd6454d_0    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
h5py                      2.10.0          nompi_py38h7442b35_105    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
htslib                    1.11                 hd3b49d5_1    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py38h578d9bd_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
isa-l                     2.30.0               h7f98852_1    conda-forge
k8                        0.2.5                he513fc3_0    bioconda
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libprotobuf               3.14.0               h780b84a_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mappy                     2.17             py38h197edbe_2    bioconda
markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
medaka                    1.2.2            py38h64b100c_0    bioconda
minimap2                  2.17                 hed695b0_3    bioconda
multidict                 5.1.0            py38h497a2fe_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.20.1           py38h18fd61f_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
ont-fast5-api             3.2.0                      py_0    bioconda
openssl                   1.1.1i               h7f98852_0    conda-forge
opt_einsum                3.3.0                      py_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
parasail-python           1.2.4            py38h8162308_0    bioconda
perl                      5.32.0               h36c2ea0_0    conda-forge
pigz                      2.5                  h27826a3_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
progressbar33             2.4                        py_0    conda-forge
protobuf                  3.14.0           py38h709712a_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyfaidx                   0.5.9.2            pyh3252c3a_0    bioconda
pyjwt                     2.0.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py38hbdc2ae9_1    bioconda
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pyspoa                    0.0.3            py38h6ed170a_1    bioconda
python                    3.8.6           hffdb5ce_5_cpython    conda-forge
python-edlib              1.3.8.post2      py38hed8969a_0    bioconda
python-isal               0.4.0            py38h497a2fe_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.7                pyhd3deb0d_0    conda-forge
samtools                  1.11                 h6270b1f_0    bioconda
scipy                     1.6.0            py38hb2138dd_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tar                       1.34                 ha1f6473_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.3.0           eigen_py38h71ff20e_0  
tensorflow-base           2.3.0           eigen_py38hb57a387_0  
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
whatshap                  1.0              py38hed8969a_1    bioconda
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py38h497a2fe_3    conda-forge
xopen                     1.1.0            py38h578d9bd_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.6.3            py38h497a2fe_1    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
```

**Comment by cjw85** [comment]
Hi Rasmus,

We've noticed this error occurs when using the Python 3.7 and Python 3.8 medaka packages from PyPI (pip install medaka). We've not observed this behaviour when medaka is installed via conda, though clearly you now have.

Medaka works fine if installed with Python 3.6 and pip. We've invesitgated this internally and found the issue appears to stem from differences in the Tensorflow packages for the different Python versions. We've found that the issue does not arise with newer versions of Tensorflow, and so in the next release of medaka we will update to Tensorflow 2.4.

For now, if you create your conda environment with Python 3.6, things should work more smoothly.

**Comment by Sumsarium** [comment]
Hi @cjw85,

Thanks for your fast reply and suggestion. I installed Python 3.6 (conda create -n medaka36 python=3.6 medaka) which, however, resulted in a different error. Do you know what is going on here? Any input would be much appreciated.

```
Traceback (most recent call last):
  File "/home/rwo/.conda/envs/medakap36/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/rwo/.conda/envs/medakap36/lib/python3.6/site-packages/medaka/medaka.py", line 5, in <module>
    import pysam
  File "/home/rwo/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/rwo/.conda/envs/medakap36/bin/../lib/libssl.so.1.1: symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference
Traceback (most recent call last):
  File "/home/rwo/.conda/envs/medakap36/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/rwo/.conda/envs/medakap36/lib/python3.6/site-packages/medaka/medaka.py", line 5, in <module>
    import pysam
  File "/home/rwo/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/rwo/.conda/envs/medakap36/bin/../lib/libssl.so.1.1: symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference
Traceback (most recent call last):
  File "/home/rwo/.conda/envs/medakap36/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/rwo/.conda/envs/medakap36/lib/python3.6/site-packages/medaka/medaka.py", line 5, in <module>
    import pysam
  File "/home/rwo/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/rwo/.conda/envs/medakap36/bin/../lib/libssl.so.1.1: symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference
```

**Comment by cjw85** [comment]
Unfortunately I do not know whats going on there. I currently have an environment built with:

```
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.6.*
    - medaka==1.2.1
    - minimap2==2.17
    - racon==1.4.13
    - tensorflow==2.2.*
```

That appears to work.

As an aside, we don't typically use conda ourselves and maintaining the conda package has been a bit of a nightmare.

**Comment by Sumsarium** [comment]
hmm perhaps my computer just needed a nap. Tried again with the python3.6 and now it's working so thank you! The solution was: `conda create -n medaka -c bioconda -c conda-forge python=3.6 medaka`

**Comment by cjw85** [comment]
We've eventually pinned this down to incompatibilities between some versions of tensorflow and numpy; it's not a Python version issue. The later tensorflow versions request numpy<1.20 and avoid the issues you've seen above; earlier versions of tensorflow make no special request for numpy versions and subsequently are susceptible to runtime errors. The things can work happily when medaka is installed with `pip` is that  PyPI does not server offending versions of numpy.

medaka from PyPI now explicitely required `tensorflow 2.2.2` which explicitely requests working numpy versions. The build on bioconda is currently failing (https://github.com/bioconda/bioconda-recipes/pull/27176), we might have to leave this to the community to help fix as we have little resource to do so at this time.
