### ISSUE TITLE
medaka_haploid_variant pysam error

### ISSUE THREAD

**Issue by Sudosundu** [nanoporetech/medaka#274]
Unable to get past this error in medaka_haploid_variant. medaka installed through conda 
medaka version1.2.1

`[10:22:30 - Predict] Setting tensorflow inter/intra-op threads to 2/1.
Traceback (most recent call last):
  File "/home/dr-rs-genome-station/miniconda3/envs/medaka/bin/medaka_haploid_variant", line 10, in <module>
    sys.exit(haploid_variant_cmdline())
  File "/home/dr-rs-genome-station/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 708, in haploid_variant_cmdline
    medaka.wrappers.haploid_variant(args)
  File "/home/dr-rs-genome-station/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/wrappers.py", line 119, in haploid_variant
    medaka.prediction.predict(args)
  File "/home/dr-rs-genome-station/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/prediction.py", line 114, in predict
    bam_regions = medaka.common.get_bam_regions(
  File "/home/dr-rs-genome-station/miniconda3/envs/medaka/lib/python3.8/site-packages/medaka/common.py", line 646, in get_bam_regions
    with pysam.AlignmentFile(bam) as bam_fh:
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 991, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
`

**Comment by lixiaopi1985** [comment]
@Sudosundu We encountered the same error. Did you solve this issue?

**Comment by Sudosundu** [comment]
I removed all the medaka packages and reinstalled using conda. It works now
