### ISSUE TITLE
medaka annotate index out of range

### ISSUE THREAD

**Issue by sengelen** [nanoporetech/medaka#277]
Hello,

**Describe the bug**

I run these commands :

medaka_haploid_variant reads.fastq ref.fasta -o outputdir --model r941_min_fast_g303
minimap2 ref.fasta reads.fastq -x map-ont -t 1 -a --secondary=no --MD -L | samtools sort --output-fmt BAM -o outputdir /reads_to_ref.bam -@ 1
medaka tools annotate outputdir/consensus_to_ref.vcf ref.fasta outpudir/reads_to_ref.bam outpudir/reads_to_ref.vcf --dpsp

medaka_haploid_variant and minimap2 works well but sometimes (it depends on the reads.fastq in input) I have this error with medaka tools annotate   :

```
[11:02:04 - Annotate vcf] Getting chrom coordinates
[11:02:04 - Annotate vcf] Chunking regions
[11:02:04 - Annotate vcf] Processing chunk with coordinates: 21727-26389
Traceback (most recent call last):
  File "/env/products/nanoporetech/2020.6.6/bin/medaka", line 11, in <module>
    load_entry_point('medaka==1.2.2', 'console_scripts', 'medaka')()
  File "/env/products/nanoporetech/2020.6.6/lib/python3.7/site-packages/medaka/medaka.py", line 684, in main
    args.func(args)
  File "/env/products/nanoporetech/2020.6.6/lib/python3.7/site-packages/medaka/vcf.py", line 1197, in annotate_vcf_n_reads
    count = merged_counts[plp_index]
IndexError: list index out of range
```

And it seems that the last line of the output file is not correctly annotated (lot of 0) :

```
##fileformat=VCFv4.1
##medaka_version=1.2.2
##contig=<ID=NC_045512.2>
##medaka_version=1.2.2
##contig=<ID=NC_045512.2,length=29903>
##INFO=<ID=DP,Number=1,Type=Integer,Description="Depth of reads at pos">
##INFO=<ID=DPS,Number=2,Type=Integer,Description="Depth of reads at pos by strand (fwd, rev)">
##INFO=<ID=DPSP,Number=1,Type=Integer,Description="Depth of reads spanning pos +-25">
##INFO=<ID=SR,Number=.,Type=Integer,Description="Depth of spanning reads by strand which best align to each allele (ref fwd, ref rev, alt1 fwd, alt1 rev, etc.)">
##INFO=<ID=AR,Number=2,Type=Integer,Description="Depth of ambiguous spanning reads by strand which align equally well to all alleles (fwd, rev)">
##INFO=<ID=SC,Number=.,Type=Integer,Description="Total alignment score to each allele of spanning reads by strand (ref fwd, ref rev, alt1 fwd, alt1 rev, etc.) aligned with parasail match 5, mismatch -4,
open 5, extend 3">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
NC_045512.2     21728   .       T       A       .       .       AR=0,0;DP=2;DPS=1,1;DPSP=2;SC=238,228,247,219;SR=0,1,1,0        GT      1
NC_045512.2     21765   .       TACA    T       .       .       AR=0,0;DP=2;DPS=1,1;DPSP=2;SC=220,270,229,244;SR=0,1,1,0        GT      1
NC_045512.2     21769   .       TGT     T       .       .       AR=0,0;DP=2;DPS=1,1;DPSP=2;SC=215,265,221,247;SR=0,1,1,0        GT      1
NC_045512.2     21879   .       TT      T       .       .       AR=0,0;DP=2;DPS=1,1;DPSP=2;SC=250,255,255,245;SR=0,1,1,0        GT      1
NC_045512.2     21902   .       A       AA      .       .       AR=0,0;DP=2;DPS=1,1;DPSP=1;SC=255,0,250,0;SR=1,0,0,0    GT      1
NC_045512.2     21993   .       ATTA    A       .       .       AR=0,0;DP=1;DPS=1,0;DPSP=1;SC=244,0,255,0;SR=0,0,1,0    GT      1
NC_045512.2     22027   .       T       A       .       .       AR=0,0;DP=1;DPS=1,0;DPSP=0;SC=0,0,0,0;SR=0,0,0,0        GT      1
NC_045512.2     23063   .       A       T       .       .       AR=12,5;DP=541;DPS=272,269;DPSP=541;SC=62749,63172,63945,64401;SR=58,63,202,201 GT      1
NC_045512.2     23271   .       C       A       .       .       AR=9,6;DP=541;DPS=272,269;DPSP=511;SC=60310,59592,61729,61013;SR=45,44,204,203  GT      1
NC_045512.2     23403   .       A       G       .       .       AR=10,31;DP=499;DPS=253,246;DPSP=498;SC=58478,57676,60407,59360;SR=14,13,229,201        GT      1
NC_045512.2     23604   .       C       A       .       .       AR=105,119;DP=6129;DPS=3127,3002;DPSP=6071;SC=719523,683967,735642,700807;SR=594,488,2396,2369  GT      1
NC_045512.2     23709   .       C       T       .       .       AR=69,26;DP=6054;DPS=3084,2970;DPSP=6028;SC=712937,694506,728525,711265;SR=635,531,2370,2397    GT      1
NC_045512.2     24506   .       T       G       .       .       AR=124,269;DP=5351;DPS=2732,2619;DPSP=5351;SC=639898,615647,653119,627440;SR=565,512,2043,1838  GT      1
NC_045512.2     24734   .       C       A       .       .       AR=19,96;DP=4867;DPS=2466,2401;DPSP=4842;SC=574747,541535,587932,553280;SR=480,483,1953,1811    GT      1
NC_045512.2     26382   .       T       A       .       .       AR=0,0;DP=84;DPS=40,44;DPSP=0;SC=0,0,0,0;SR=0,0,0,0     GT      1
```

Thank you 

**Environment **
 - Installation from github 
 - OS: CentOS Linux release 7.9.2009 (Core)
 - no GPU

**Comment by cjw85** [comment]
This issue has been fixed in more recent versions than the version 1.2.2 indicated in your error message.

**Comment by sengelen** [comment]
Ok thank you
