### ISSUE TITLE
Error with medaka tools annotate

### ISSUE THREAD

**Issue by studyfranco** [nanoporetech/medaka#278]
Hello,

I have two error:
- I have a genome with multiple interest region like chromosome with this command "medaka tools annotate out/consensus_to_ref.vcf genome/hg38.fa.gz out/reads_to_ref.bam out/reads_to_ref.vcf --dpsp". And I obtain this error:
[12:14:44 - Annotate vcf] Getting chrom coordinates                                                                                                                         
[12:14:44 - Annotate vcf] Chunking regions
Traceback (most recent call last):
  File "/home/franco/.conda/envs/Nanopore/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/franco/.conda/envs/Nanopore/lib/python3.6/site-packages/medaka/medaka.py", line 684, in main
    args.func(args)
  File "/home/franco/.conda/envs/Nanopore/lib/python3.6/site-packages/medaka/vcf.py", line 1143, in annotate_vcf_n_reads
    if region_chunks.size else chunks
AttributeError: 'list' object has no attribute 'size'

- I have a genome with one interest region like chromosome with this command "medaka tools annotate out/consensus_to_ref.vcf genome/hg38Chr1.fa.gz out/reads_to_ref.bam out/reads_to_ref.vcf --dpsp". This error are for a particular dataset with some variations, and I obtain this error:
[12:05:14 - Annotate vcf] Getting chrom coordinates                                                                                                                         
[12:05:14 - Annotate vcf] Chunking regions
[12:05:14 - Annotate vcf] Processing chunk with coordinates: 21727-26389
Traceback (most recent call last):
  File "/home/franco/.conda/envs/Nanopore/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/franco/.conda/envs/Nanopore/lib/python3.6/site-packages/medaka/medaka.py", line 684, in main
    args.func(args)
  File "/home/franco/.conda/envs/Nanopore/lib/python3.6/site-packages/medaka/vcf.py", line 1197, in annotate_vcf_n_reads
    count = merged_counts[plp_index]
IndexError: list index out of range

**Environment:**
 - All are from a conda env with medaka in 1.2.3
 - OS: Debian 10
 - No GPU use

Best regards,
studyfranco

**Comment by cjw85** [comment]
This errors are fixed in later versions of medaka. Unfortunately the bioconda build for medaka is currently broken and will need help from the community to fix.

https://github.com/bioconda/bioconda-recipes/pull/27176
