### ISSUE TITLE
Failed to stitch consensus chunks

### ISSUE THREAD

**Issue by wjj666** [nanoporetech/medaka#281]
**Describe the bug**
Hi, I have installed the newest version of medaka v1.2.5 with conda: conda create -n medaka -c conda-forge -c bioconda medaka.

The medaka_consensus command works well on test data (small basecalls and draft). 

But when I use medaka_consensus on 120G basecalls and 3G draft, it leads to this error.

**Logging**
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "../software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 64, in stitch_from_probs
    (s.ref_name, start, s.positions[-1]['major']),
IndexError: index -1 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../software/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "../software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 684, in main
    args.func(args)
  File "../software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 185, in stitch
    contigs, gt = fill_gaps(contigs, args.draft)
  File "../software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 92, in fill_gaps
    for info, sequence_parts in contigs:
  File "../software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/stitch.py", line 136, in collapse_neighbours
    for contig in contigs:
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "../software/anaconda3/envs/medaka/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
IndexError: index -1 is out of bounds for axis 0 with size 0
Failed to stitch consensus chunks.

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda create -n medaka -c conda-forge -c bioconda medaka
 - OS: CentOS 8.2  (64-bit)
 - CPU
 
Could you please help me solve this problem? Thank you very much.

**Comment by cjw85** [comment]
Hi @wjj666,

Is it possible for you to share the `.hdf` file(s) and reference sequence that are used as input to the `medaka stitch` subcommand?

**Comment by wjj666** [comment]
> Hi @wjj666,
> 
> Is it possible for you to share the `.hdf` file(s) and reference sequence that are used as input to the `medaka stitch` subcommand?

Hi @cjw85, here is the download links for consensus .hdf file and draft .fasta file:

consensus .hdf file: https://drive.google.com/file/d/1-0QqcfPxmgvT0VxdCqq6O7ne7LFJ5ezi/view?usp=sharing
draft .fasta file: https://drive.google.com/file/d/1-0GViLuMyQ0e1z_VGAb3q2RzIcu5tJMo/view?usp=sharing

Thank you.

**Comment by cjw85** [comment]
Thank you for these files. I have rewritten the section of code which I believe is responsible for the issue and will use your data as a test set.

**Comment by wjj666** [comment]
> Thank you for these files. I have rewritten the section of code which I believe is responsible for the issue and will use your data as a test set.

I really appreciate it.

**Comment by cjw85** [comment]
Hi @wjj666,

I reproduced your error with v1.2.5 and the rewritten code fixes the issue. We will try to make a new release later today.

**Comment by wjj666** [comment]
> Hi @wjj666,
> 
> I reproduced your error with v1.2.5 and the rewritten code fixes the issue. We will try to make a new release later today.

Thank so so so much!

**Comment by cjw85** [comment]
v1.2.6 has been released and should be available shortly from bioconda. (https://github.com/bioconda/bioconda-recipes/pull/27739)
