### ISSUE TITLE
Installation failure with pip (MacOS)

### ISSUE THREAD

**Issue by ryotag** [nanoporetech/medaka#283]
Thank you for developing this nice tool!
I'm trying to install Medaka on MacOS (10.13.6).
I could successfully install Medaka using `conda create -n medaka -c conda-forge -c bioconda medaka`, but as pointed out here #268, the installed version is medaka 1.0.3.
Therefore, I used the following command to install the up-to-date version:
```
virtualenv medaka --python=python3 --prompt "(medaka) "
. medaka/bin/activate
pip install medaka
```

I got the following error while running the above command.
```
Building wheels for collected packages: whatshap
  Building wheel for whatshap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ryotag/Desktop/Analysis/medaka/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-w0_5mmsf/whatshap_66a10d1b85c84d1b80e13c2d96ac5c27/setup.py'"'"'; __file__='"'"'/private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-w0_5mmsf/whatshap_66a10d1b85c84d1b80e13c2d96ac5c27/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-wheel-ct3chgk4
       cwd: /private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-w0_5mmsf/whatshap_66a10d1b85c84d1b80e13c2d96ac5c27/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/phase.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/vcf.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/haplotag.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/verification.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/variants.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/bam.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/timer.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/graph.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/genotype.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/pedigree.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/coverage.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/hapcut2vcf.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/testhelpers.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/utils.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/stats.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/args.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/math.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/compare.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/__main__.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  copying whatshap/unphase.py -> build/lib.macosx-10.7-x86_64-3.6/whatshap
  running build_ext
  building 'whatshap.core' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/whatshap
  creating build/temp.macosx-10.7-x86_64-3.6/src
  creating build/temp.macosx-10.7-x86_64-3.6/src/hapchat
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -UNDEBUG -I/Users/ryotag/Desktop/Analysis/medaka/include -I/anaconda3/include/python3.6m -c whatshap/core.cpp -o build/temp.macosx-10.7-x86_64-3.6/whatshap/core.o -std=c++11 -Werror=return-type
  In file included from whatshap/core.cpp:644:
  whatshap/../src/read.h:6:10: fatal error: 'unordered_set' file not found
  #include <unordered_set>
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for whatshap
  Running setup.py clean for whatshap
Failed to build whatshap
```
Please let me know if you have any ideas.

Thank you,

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [pypi (pip install)]
 - OS: [macOS High Sierra version 10.13.6]
 - medaka version [NA]
 - GPU model [NA]

**Comment by cjw85** [comment]
Hi,

This looks like an error compiling WhatsHap on your macOS version rather than a medaka version per se. Looking around there might be various things to be done in order to get Whatshap to compile (the WhatsHap developers appear to run tests against later versions of macOS).

I can suggest two ways forward here. First you could figure out how to get Whatshap to compile and install independently of medaka. Once installed the medaka installation will proceed. Alternatively, you could install medaka from the source code but editing the requirements.txt file to omit WhatsHap as a dependency. WhatsHap is used only in the diploid variant calling workflow, so it is safe to remove if you are not interested in that.

**Comment by ryotag** [comment]
Thanks for quick response and suggestion!
I tried the second option (deleted the whatshap line from requirements.txt), because I'm analyzing bacterial genomes.

However, `$ make install` returned the following error.

```
test -d venv || python3 -m venv venv --prompt "medaka"
. ./venv/bin/activate && pip install pip --upgrade
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.0.1
# setuptools 53.0.0 trips up on whatshap deps
. ./venv/bin/activate && pip install setuptools==52.0.0
Collecting setuptools==52.0.0
  Downloading setuptools-52.0.0-py3-none-any.whl (784 kB)
     |████████████████████████████████| 784 kB 1.4 MB/s 
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
Successfully installed setuptools-52.0.0
. ./venv/bin/activate && python -c "from setup import check_model_lfs; check_model_lfs()"
Bundling models: ['r103_min_high_g345', 'r103_min_high_g360', 'r103_prom_high_g360', 'r103_prom_snp_g3210', 'r103_prom_variant_g3210', 'r10_min_high_g303', 'r10_min_high_g340', 'r941_min_fast_g303', 'r941_min_high_g303', 'r941_min_high_g330', 'r941_min_high_g340_rle', 'r941_min_high_g344', 'r941_min_high_g351', 'r941_min_high_g360', 'r941_prom_fast_g303', 'r941_prom_high_g303', 'r941_prom_high_g330', 'r941_prom_high_g344', 'r941_prom_high_g360', 'r941_prom_high_g4011', 'r941_prom_snp_g303', 'r941_prom_snp_g322', 'r941_prom_snp_g360', 'r941_prom_variant_g303', 'r941_prom_variant_g322', 'r941_prom_variant_g360']

Model files appear to be git lfs stubs. Please refer to README.md
for instructions regarding git lfs. If you obtained medaka through
a method other than cloning the repository from github, please raise
an issue on github.com/nanoporetech/medaka.
make: *** [check_lfs] Error 1
```
I found #178 mentioning git lfs, but it's installed in my PC.

```
$brew install git-lfs
Warning: git-lfs 2.13.3 is already installed and up-to-date.
To reinstall 2.13.3, run:
  brew reinstall git-lfs
```
Maybe there are other libraries needed as specified in the installation instruction? (not sure which ones are needed for installation for MacOS though)

>Before installing medaka it may be required to install some prerequisite libraries, best installed by a package manager. On Ubuntu theses are:
bzip2 g++ zlib1g-dev libbz2-dev liblzma-dev libffi-dev libncurses5-dev
libcurl4-gnutls-dev libssl-dev curl make cmake wget python3-all-dev
python-virtualenv

**Comment by cjw85** [comment]
This sounds like git-lfs isn't installed quite correctly or hasn't been initialised. I believe I've had trouble in the past with the brew installation of git-lfs. What happens when you run:

    git lfs install

As advised here: https://git-lfs.github.com/? On my mac I think I simply downloaded the binary from: https://github.com/git-lfs/git-lfs/releases/tag/v2.13.3 and followed the instructions in the archive.

**Comment by ryotag** [comment]
It got the followings
```
$ git lfs install
Updated git hooks.
Git LFS initialized.
```
Again, `make install` returned the same error.

I also tried
>simply downloaded the binary from: https://github.com/git-lfs/git-lfs/releases/tag/v2.13.3

and installed git lfs with `./install.sh`, but `make install` returned the same error.

Probably I should try the first option (get Whatshap to compile and install independently of medaka)...

**Comment by cjw85** [comment]
After running `git lfs install` I think you will likely have to reclone the repository or run `git lfs pull` to replace the lfs stubs with the actual files needed. I would keep trying with this route, getting Whatshap to compile is likely going to be more difficult.

**Comment by ryotag** [comment]
Without running `git lfs pull`, I somehow successfully finished this stage after several tries (I don't know why)
However, I got the following error
```
ERROR: Could not find a version that satisfies the requirement pyspoa>=0.0.3
ERROR: No matching distribution found for pyspoa>=0.0.3
```
Can I edit requirements.txt just like I removed the whatshap line?

**Comment by cjw85** [comment]
Yes, pyspoa is only required for some fringe use cases. @iiSeymour can you push a sdist for pyspoa (or some Mac wheels?).

**Comment by ryotag** [comment]
I deleted the pyspoa and whatshap lines from requirements.txt, and it seems installation succeeded.
However, medaka is not working correctly...
```
Traceback (most recent call last):
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/bin/medaka", line 33, in <module>
    sys.exit(load_entry_point('medaka==1.2.6', 'console_scripts', 'medaka')())
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/bin/medaka", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/medaka-1.2.6-py3.6-macosx-10.7-x86_64.egg/medaka/medaka.py", line 9, in <module>
    import medaka.features
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/medaka-1.2.6-py3.6-macosx-10.7-x86_64.egg/medaka/features.py", line 17, in <module>
    import medaka.labels
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/medaka-1.2.6-py3.6-macosx-10.7-x86_64.egg/medaka/labels.py", line 14, in <module>
    import medaka.rle
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/medaka-1.2.6-py3.6-macosx-10.7-x86_64.egg/medaka/rle.py", line 16, in <module>
    import medaka.smolecule
  File "/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/medaka-1.2.6-py3.6-macosx-10.7-x86_64.egg/medaka/smolecule.py", line 14, in <module>
    import spoa
ModuleNotFoundError: No module named 'spoa'
```

Is it relevant to installation without pyspoa?

**Comment by iiSeymour** [comment]
Wheels for Intel Macs are available for Python 3.5 to 3.8 already. @ryotag are you using Python 3.9 and/or a new M1 Mac?

**Comment by ryotag** [comment]
I'm using Python 3.6.8 and not using a new M1 Mac.
Could you tell me what I do to avoid this error?

**Comment by iiSeymour** [comment]
@ryotag I've just published a source distribution to PyPI so I'm hoping you will be able to build for 10.13.6.

**Comment by ryotag** [comment]
The followings are what I did.
```
git clone https://github.com/nanoporetech/medaka.git
cd medaka
vi medaka #this is to remove whatshap line. I did not remove pyspoa line. (I hope I'm doing the right thing)
make install
```
and I got the following error
```
.
.
.
Using legacy 'setup.py install' for pyspoa, since package 'wheel' is not installed.
Installing collected packages: urllib3, pyasn1, idna, chardet, certifi, zipp, typing-extensions, six, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, importlib-metadata, google-auth, wheel, werkzeug, tensorboard-plugin-wit, pyparsing, protobuf, numpy, markdown, grpcio, google-auth-oauthlib, absl-py, wrapt, termcolor, tensorflow-estimator, tensorboard, sortedcontainers, pycparser, pybind11, progressbar33, packaging, opt-einsum, keras-preprocessing, h5py, google-pasta, gast, astunparse, tensorflow, pyspoa, pysam, parasail, ont-fast5-api, mappy, intervaltree, edlib, cffi, biopython
    Running setup.py install for pyspoa ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ryotag/Desktop/Analysis/medaka/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-kzmj8ljy/pyspoa_759fd343383b4964bc183b1dc9882210/setup.py'"'"'; __file__='"'"'/private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-kzmj8ljy/pyspoa_759fd343383b4964bc183b1dc9882210/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-record-gzca_7r2/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ryotag/Desktop/Analysis/medaka/venv/include/site/python3.6/pyspoa
         cwd: /private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-kzmj8ljy/pyspoa_759fd343383b4964bc183b1dc9882210/
    Complete output (19 lines):
    running install
    running build
    running build_ext
    creating var
    creating var/folders
    creating var/folders/nn
    creating var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn
    creating var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/Users/ryotag/Desktop/Analysis/medaka/venv/include -I/anaconda3/include/python3.6m -c /var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/tmp3e_h6dzp.cpp -o var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/tmp3e_h6dzp.o -std=c++14
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/Users/ryotag/Desktop/Analysis/medaka/venv/include -I/anaconda3/include/python3.6m -c /var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/tmp_npttpn6.cpp -o var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/tmp_npttpn6.o -fvisibility=hidden
    building 'spoa' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -Isrc/include/spoa -Isrc/vendor/cereal/include -I/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/pybind11/include -I/Users/ryotag/Desktop/Analysis/medaka/venv/lib/python3.6/site-packages/pybind11/include -I/Users/ryotag/Desktop/Analysis/medaka/venv/include -I/anaconda3/include/python3.6m -c pyspoa.cpp -o build/temp.macosx-10.7-x86_64-3.6/pyspoa.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="0.0.6" -std=c++14 -fvisibility=hidden
    pyspoa.cpp:1:10: fatal error: 'spoa.hpp' file not found
    #include "spoa.hpp"
             ^~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ryotag/Desktop/Analysis/medaka/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-kzmj8ljy/pyspoa_759fd343383b4964bc183b1dc9882210/setup.py'"'"'; __file__='"'"'/private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-install-kzmj8ljy/pyspoa_759fd343383b4964bc183b1dc9882210/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/nn/64c78gbj1r13q5slzm81ycjr0000gn/T/pip-record-gzca_7r2/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ryotag/Desktop/Analysis/medaka/venv/include/site/python3.6/pyspoa Check the logs for full command output.
make: *** [install] Error 1
```

**Comment by iiSeymour** [comment]
Can you try again @ryotag, the `sdist` wasn't packaged correctly yesterday but I just published `v0.0.8` which should be.

**Comment by ryotag** [comment]
I could successfully install Medaka version 1.2.6 on my Mac!
I could also successfully run medaka_consensus on my bacterial genome assemblies.
Thank you very much for your kind supports!

**Comment by iiSeymour** [comment]
Good to hear @ryotag!
