### ISSUE TITLE
'RuntimeError: Unable to copy object' when parallelizing 

### ISSUE THREAD

**Issue by danielle-khost** [nanoporetech/medaka#294]
**Describe the bug**
Runtime error ("RuntimeError: Unable to copy object (destination object already exists) when attempting to run medaka consensus

**Logging**

```
[19:54:57 - Predict] Reducing threads to 2, anymore is a waste.
[19:54:57 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.
[19:54:57 - Predict] Setting tensorflow inter/intra-op threads to 2/1.
[19:54:57 - Predict] Processing region(s): (Note: omitted contig list)

[19:54:57 - Predict] Using model: /n/home04/dkhost/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/data/r941_prom_high_g360_model.hdf5.
[19:54:57 - MdlStore] ModelStore exception <class 'RuntimeError'>
Traceback (most recent call last):
  File "/n/home04/dkhost/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/n/home04/dkhost/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 688, in main
    args.func(args)
  File "/n/home04/dkhost/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/prediction.py", line 127, in predict
    model_store.copy_meta(args.output)
  File "/n/home04/dkhost/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 92, in copy_meta
    return ds.copy_meta(other)
  File "/n/home04/dkhost/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 251, in copy_meta
    self.fh.copy(
  File "/n/home04/dkhost/anaconda3/envs/medaka/lib/python3.8/site-packages/h5py/_hl/group.py", line 494, in copy
    h5o.copy(source.id, self._e(source_path), dest.id, self._e(dest_path),
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 217, in h5py.h5o.copy
RuntimeError: Unable to copy object (destination object already exists)

```
**Environment (if you do not have a GPU, write No GPU):**
 (Tried both with and without GPU)
OS: CentOS Linux 7
Install: conda
CPU: Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz
GPU: Nvidia Tesla
Nvidia driver: v 396.26
CUDA version: 9
cuDNN version: 7.0 (?)

**Additional context**
Hi there, I'm attempting to polish some large genomes (6.6 Gb and 1 Gb) using medaka and have been running into some cryptic errors. I attempted to run the complete pipeline with 'medaka_consensus' but as it was taking prohibitively long I tried splitting them up into batches (~4000 contigs per batch) and running 'medaka consensus' to parallelize, where I get the above error. I am using medaka 1.3.2 with python 3.8. I've tried various fixes:

-unthreaded and threaded (--threads 8)
-on a slurm computing cluster vs on a local high RAM machine, which is where this error log is from but it is the same error the cluster (tho with an older version of medaka)
-with and without specifying the basecalling model

All these result in the same error. Weirdly I don't get the error when running 'medaka_consensus', which seems to load in the contigs just fine, tho it does seem to stall on small contigs? I have been able to run medaka_consensus on a smaller test genome successfully, and I have run it several times in the past without issues. Any advice would be appreciated! 

-Danielle

**Comment by cjw85** [comment]
Hi @danielle-khost,

This looks like the program is trying to write to a pre-existing output file. I suspect that this might be because your individual parallel jobs are writing to the same output location (specifically the .hdf file). You will need to make sure each job is writing to a unique location.

Either that or you have files left over from a previous run?

**Comment by danielle-khost** [comment]
Ahh perfect, that was it! I had some old leftover files buried that I totally missed, thank you so much!
