### ISSUE TITLE
ValueError: no index available for pileup

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/medaka#295]
Hi,
I installed `fast5mod` via conda and I tried to use [fast5mod](https://github.com/nanoporetech/fast5mod) with the command below:
```
fast5_path=/fastscratch/test
ref_dir=/fastscratch/c-panz
output_dir=/fastscratch/test

fast5mod call $output_dir/testmeth.bam $ref_dir/hg38.fasta $output_dir/meth.chr1.tsv --meth cpg --regions chr1
```
I got the error saying 
```
[21:30:33 - Mextract] Processing /fastscratch/test/testmeth.bam.
[21:30:33 - Mextract] Calling methylation at cpg sites.
[E::idx_find_and_load] Could not retrieve index file for '/fastscratch/test/testmeth.bam'
[E::idx_find_and_load] Could not retrieve index file for '/fastscratch/test/testmeth.bam'
[21:30:33 - Mextract] Processing region: chr1:0-248956422.
[21:30:36 - Mextract] Searching for motif 'CG'.
Traceback (most recent call last):
  File "/projects/Anaconda3/bin/fast5mod", line 8, in <module>
    sys.exit(main())
  File "/projects/lAnaconda3/lib/python3.7/site-packages/fast5mod/fast5mod.py", line 107, in main
    args.func(args)
  File "/projects/Anaconda3/lib/python3.7/site-packages/fast5mod/programs.py", line 481, in call_methylation
    region.ref_name, region.start, region.end)
  File "pysam/libcalignmentfile.pyx", line 1331, in pysam.libcalignmentfile.AlignmentFile.pileup
ValueError: no index available for pileup
```
Do you know how can I solve the problem? I checked the pysam and there is an issue https://github.com/pysam-developers/pysam/issues/915, but the author claimed it should be solved in the latest version.

Also, I found you mentioned that we have to do call methylation by chromosome in https://github.com/nanoporetech/medaka/issues/177#issuecomment-645404886, so does fast5mod support whole-genome methylation calling right now?

Thank you so much for your help!

**Comment by PanZiwei** [comment]
I solved the problem by generating the index using samtools.
