### ISSUE TITLE
Medaka smolecule no attribute bam_chunk

### ISSUE THREAD

**Issue by gordonrix** [nanoporetech/medaka#300]
Unclear to me if this is a bug or if I am just doing something wrong, but attempting to use smolecule to generate a consensus sequence with an example fasta file that has three sequences. The output consensus should be identical to the first sequence, as the 2nd and 3rd sequences each have a single contrived SNP at different positions:

 \`\`\`
>UMI-0_02594e7d-dedb-49f9-8d4b-2b73042f3baf-CGTGTATTTTCTTAGACCAAAGCAATGGATAAG runid=7f55872faf4bbd3a5ac96f2bfe6b8ad7ffc81c15 sampleid=sample1 read=969919 ch=69 start_time=2021-01-15T13:05:11Z
GGATCCGATACAACTTCGTATCGTGTAGAGACTGCGTAGGCGTGTATTTTCTTAACATAG
GAAGATCTGAAACAAAAAAGATTATTAACTTTTTGGAAATATCAGAAAAATGTAGAAACA
TGTGATAAGCTCATAGACATGTAAAGTCGACATGAAGGCACACTTCCGGTCCGTACGGTG
GCCAGCACGTGCCGGAAATCCTGATGCCAACTCTGGAAGAACTGGAAGCTGCGTACGAAG
AAATCATGAAAGATGAGTCTTTCTGGAAAGAATTCAATGACCTGCTGCGCGATTATGCGG
GTCGTCCGACTCCGCTATTACTTCGCACGTCGTCTGTCCGAGAAATACGGTGCTCGCATC
TATCTGAAACAGCGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATC
GGCCAGGTTCTGCTGGCAAGGAAGATGGGCAAGACCCGTATCATTGCTGAAACGGGTGCT
GGTCAGCACGGCGTAGCAACTGCTACCGCAGCAGCGCTGTTCGGTATGGAATGTGTAATC
TATATGGGCGAAAGACACGATCCGCCAGAAACCGAACGTTGAACGTATGGAAACTGCTGG
GTGCTAAAGTTGTACCGGTAAAATCCGGTAGCCGTACCCTGAAAGACGCAATTGACGAAG
CTCTGCGTGACTGGATTACCAACCTGCAGACCACCTATTACGTGATCGGCTCTGTGGTTG
GTCCGCATCCATATCCGATTATCGTACGTAACTTCCCAAAAGGTTATCGGCGAAGAGACC
AAGAAGCGGATTCTGGAGAAGAAGGCCGTCTGCCGGACTACATCGTTGCGTGCGTGGGTG
GTGGTTCTAACGCTGCCCGGTATCTTCTATCCGTTTATCGATTCTGGTGTAGAAGCTGAT
CGGCGTGAAGCCGGTGGCGAGATCTGACCGGTAAACATGCGGCTTCTCTGCTGAAGATAA
AATCGGCTACCTGCACAGTTCTAAGACGTTCGTTCTACAGCGGGATGACTGGGGTCAAGT
TCAGGTGACGCACTCGTCTCCTCTGGCCTGGACTACTCCGGTGTCGGTCCGGAACACGCC
TATTGGCGTGAGACCGATGGTAAAGTGTAGCCACGATGCTGTGACCGATGAAGAAGCTCT
GGACGCATTCATCGAACTGTCTCGCCCTGGAGGCATCATCCCAGCCCTGGAGTCTTCTCA
CGCACTGGCTTATCTGAAGAAGATCAACATCAAGGGTAAAGTTGTGGTGGTTAATCTGTC
TGGTCGTGGTGACAAGGATCTGGAATCTGTACTGAACCACCCGTATGTTCGCGAACGCAT
CCGCCTCGAGCATCATCATCATCATCATTAAGAGCTCCGCGTCTTTGCTGTGAGCATGCT
TTTCGCCGGAGTCAATTAGGTCATACGACCAAAGCAATGGATAAGCACTCGCACTGACTC
GATCACTGTTCTTGTATCGGTACC
>UMI-0_e24f2692-fa20-4e57-9f72-a437e9573efb-CGTGTATTTTCTTAGACCAAAGCAATGGATAAG runid=7f55872faf4bbd3a5ac96f2bfe6b8ad7ffc81c15 sampleid=sample1 read=919776 ch=92 start_time=2021-01-15T12:47:13Z
GGATCCGATACAACTTCGTATCGTGTAGAGACTGCGTAGGCGTGTATTTTCTTAACATAG
GAAGATCTGAAACAAAAAAGATTATTAACTTTTTGGAAATATCAGAAAAATGTAGAAACA
TGTGATAAGCTCATAGACATGTAAAGTCGACATGAAGGCACACTTCCGGTCCGTACGGTG
GCCAGCACGTGCCGGAAATCCTGATGCCAACTCTGGAAGAACTGGAAGCTGCGTACGAAG
AAATCATGAAAGATGAGTCTTTCTGGAAAGAATTCAATGACCTGCTGCGCGATTATGCGG
GTCGTCCGACTCCGCTATTACTTCGCACGTCGTCTGTCCGAGAAATACGGTGCTCGCATC
TATCTGAAACAGCGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATC
GGCCAGGTTCTGCTGGCAAGGAAGATGGGCAAGACCCGTATCATTGCTGAAACGGGTGCT
GGTCAGCACGGCGTAGCAACTGCTACCGCAGCAGCGCTGTTCGGTATGGAATGTGTAATC
TATATGGGCGAAAGACACGATCCGCCAGAAACCGAACGTTGAACGTATGGATACTGCTGG
GTGCTAAAGTTGTACCGGTAAAATCCGGTAGCCGTACCCTGAAAGACGCAATTGACGAAG
CTCTGCGTGACTGGATTACCAACCTGCAGACCACCTATTACGTGATCGGCTCTGTGGTTG
GTCCGCATCCATATCCGATTATCGTACGTAACTTCCCAAAAGGTTATCGGCGAAGAGACC
AAGAAGCGGATTCTGGAGAAGAAGGCCGTCTGCCGGACTACATCGTTGCGTGCGTGGGTG
GTGGTTCTAACGCTGCCCGGTATCTTCTATCCGTTTATCGATTCTGGTGTAGAAGCTGAT
CGGCGTGAAGCCGGTGGCGAGATCTGACCGGTAAACATGCGGCTTCTCTGCTGAAGATAA
AATCGGCTACCTGCACAGTTCTAAGACGTTCGTTCTACAGCGGGATGACTGGGGTCAAGT
TCAGGTGACGCACTCGTCTCCTCTGGCCTGGACTACTCCGGTGTCGGTCCGGAACACGCC
TATTGGCGTGAGACCGATGGTAAAGTGTAGCCACGATGCTGTGACCGATGAAGAAGCTCT
GGACGCATTCATCGAACTGTCTCGCCCTGGAGGCATCATCCCAGCCCTGGAGTCTTCTCA
CGCACTGGCTTATCTGAAGAAGATCAACATCAAGGGTAAAGTTGTGGTGGTTAATCTGTC
TGGTCGTGGTGACAAGGATCTGGAATCTGTACTGAACCACCCGTATGTTCGCGAACGCAT
CCGCCTCGAGCATCATCATCATCATCATTAAGAGCTCCGCGTCTTTGCTGTGAGCATGCT
TTTCGCCGGAGTCAATTAGGTCATACGACCAAAGCAATGGATAAGCACTCGCACTGACTC
GATCACTGTTCTTGTATCGGTACC
>UMI-0_a1acfda1-c015-45e3-be0f-baf5fc9f7c58-CGTGTATTTTCTTAGACCAAAGCAATGGATAAG runid=7f55872faf4bbd3a5ac96f2bfe6b8ad7ffc81c15 sampleid=sample1 read=1041158 ch=117 start_time=2021-01-15T13:05:14Z
GGATCCGATACAACTTCGTATCGTGTAGAGACTGCGTAGGCGTGTATTTTCTTAACATAG
GAAGATCTGAAACAAAAAAGATTATTAACTTTTTGGAAATATCAGAAAAATGTAGAAACA
TGTGATAAGCTCATAGACATGTAAAGTCGACATGAAGGCACACTTCCGGTCCGTACGGTG
GCCAGCACGTGCCGGAAATCCTGATGCCAACTCTGGAAGAACTGGAAGCTGCGTACGAAG
AAATCATGAAAGATGAGTCTTTCTGGAAAGAATTCAATGACCTGCTGCGCGATTATGCGG
GTCGTCCGACTCCGCTATTACTTCGCACGTCGTCTGTCCGAGAAATACGGTGCTCGCATC
TATCTGAAACAGCGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATC
GGCCAGGTTCTGCTGGCAAGGAAGATGGGCAAGACCCGTATCATTGCTGAAACGGGTGCT
GGTCAGCACGGCGTAGCAACTGCTACCGCAGCAGCGCTGTTCGGTATGGAATGTGTAATC
TATATGGGCGAAAGACACGATCCACCAGAAACCGAACGTTGAACGTATGGAAACTGCTGG
GTGCTAAAGTTGTACCGGTAAAATCCGGTAGCCGTACCCTGAAAGACGCAATTGACGAAG
CTCTGCGTGACTGGATTACCAACCTGCAGACCACCTATTACGTGATCGGCTCTGTGGTTG
GTCCGCATCCATATCCGATTATCGTACGTAACTTCCCAAAAGGTTATCGGCGAAGAGACC
AAGAAGCGGATTCTGGAGAAGAAGGCCGTCTGCCGGACTACATCGTTGCGTGCGTGGGTG
GTGGTTCTAACGCTGCCCGGTATCTTCTATCCGTTTATCGATTCTGGTGTAGAAGCTGAT
CGGCGTGAAGCCGGTGGCGAGATCTGACCGGTAAACATGCGGCTTCTCTGCTGAAGATAA
AATCGGCTACCTGCACAGTTCTAAGACGTTCGTTCTACAGCGGGATGACTGGGGTCAAGT
TCAGGTGACGCACTCGTCTCCTCTGGCCTGGACTACTCCGGTGTCGGTCCGGAACACGCC
TATTGGCGTGAGACCGATGGTAAAGTGTAGCCACGATGCTGTGACCGATGAAGAAGCTCT
GGACGCATTCATCGAACTGTCTCGCCCTGGAGGCATCATCCCAGCCCTGGAGTCTTCTCA
CGCACTGGCTTATCTGAAGAAGATCAACATCAAGGGTAAAGTTGTGGTGGTTAATCTGTC
TGGTCGTGGTGACAAGGATCTGGAATCTGTACTGAACCACCCGTATGTTCGCGAACGCAT
CCGCCTCGAGCATCATCATCATCATCATTAAGAGCTCCGCGTCTTTGCTGTGAGCATGCT
TTTCGCCGGAGTCAATTAGGTCATACGACCAAAGCAATGGATAAGCACTCGCACTGACTC
GATCACTGTTCTTGTATCGGTACC
 \`\`\`

When I run the following command using all the default options:

 \`\`\`
medaka smolecule out reads.fasta
 \`\`\`

I get an attributeError related to the spoa centroid BAM file:

 \`\`\`
[11:49:12 - Smolecule] Given one input file, subreads are assumed to be grouped by read.
[11:49:12 - Smolecule] Running spoa pre-medaka consensus for all reads.
[11:49:12 - Smolecule] Writing medaka input bam for 1 reads.
[11:49:12 - Smolecule] Running medaka consensus.
[11:49:12 - Predict] Setting tensorflow inter/intra-op threads to 1/1.
[11:49:12 - Predict] Processing region(s): UMI-0:0-1464
[11:49:12 - Predict] Using model: /home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[11:49:12 - MdlStore] ModelStore exception <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/popos/miniconda3/envs/maple/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/medaka.py", line 688, in main
    args.func(args)
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/smolecule.py", line 443, in main
    medaka.prediction.predict(args)
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/prediction.py", line 147, in predict
    if region.size > args.bam_chunk:
AttributeError: 'Namespace' object has no attribute 'bam_chunk'
 \`\`\`

Environment:
- Fresh install via conda, version 1.3.2
- OS: Pop!_OS 20.04 LTS (basically Ubuntu 20.04 LTS)
- No GPU

**Comment by cjw85** [comment]
Apologies @gordonrix, I believe this is an known but that we have yet to fix. We should have a fix later in the week

**Comment by gordonrix** [comment]
Ok great! Please let me know when it's out. Also if things change and it ends up taking longer, could you let me know a potential workaround?

Thanks!

**Comment by cjw85** [comment]
@gordonrix,

There is something you can do to patch this until we've released a fix. In the file:

```/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/smolecule.py```

in the `main()` function you will see this block:

```
    # arg parser does not supply these
    args.tag_name = None
    args.tag_value = None
    args.tag_keep_missing = False
    args.RG = None
    args.regions = None
    args.draft = None
```

To the end of that, if you add `args.bam_chunk` = int(1e6)`, I believe the program will run.

**Comment by gordonrix** [comment]
Thanks! now it looks like another argument is missing. Running the same as above but with that line added gives:

```
[14:16:21 - Smolecule] Given one input file, subreads are assumed to be grouped by read.
[14:16:21 - Smolecule] Running spoa pre-medaka consensus for all reads.
[14:16:22 - Smolecule] Writing medaka input bam for 1 reads.
[14:16:22 - Smolecule] Running medaka consensus.
[14:16:22 - Predict] Setting tensorflow inter/intra-op threads to 1/1.
[14:16:22 - Predict] Processing region(s): UMI-0:0-1464
[14:16:22 - Predict] Using model: /home/popos/miniconda3/envs/medaka_test/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[14:16:22 - Predict] Processing 1 long region(s) with batching.
[14:16:22 - MdlStore] filepath /home/popos/miniconda3/envs/medaka_test/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[14:16:22 - MdlStore] ModelStore exception <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/popos/miniconda3/envs/medaka_test/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/popos/miniconda3/envs/medaka_test/lib/python3.8/site-packages/medaka/medaka.py", line 688, in main
    args.func(args)
  File "/home/popos/miniconda3/envs/medaka_test/lib/python3.8/site-packages/medaka/smolecule.py", line 444, in main
    medaka.prediction.predict(args)
  File "/home/popos/miniconda3/envs/medaka_test/lib/python3.8/site-packages/medaka/prediction.py", line 168, in predict
    bam_workers=args.bam_workers)
AttributeError: 'Namespace' object has no attribute 'bam_workers'
```

**Comment by gordonrix** [comment]
Works now, thanks so much.
