### ISSUE TITLE
Difficult-to-parse error message from running medaka smolecule on single file at stitch step

### ISSUE THREAD

**Issue by gordonrix** [nanoporetech/medaka#301]
I am running medaka smolecule on a single file that contains reads grouped together like so:

```
>UMI-578_f1ebcdc7-62f2-4d66-b0f5-0790dcb58fb0_CGCTGCCACGTGTCATCGCGTTAAAT UMI=CGCTGCCACGTGTCATCGCGTTAAAT
(read 1)
>UMI-578_03a3059c-eee2-464c-97c9-2a743fe9366f_CGCTGCCACGTGTCATCGCGTTAAAT UMI=CGCTGCCACGTGTCATCGCGTTAAAT
(read 2)
>UMI-578_b8d63cde-2b22-4e6f-95f4-6960142cbd69_CGCTGCCACGTGTCATCGCGTTAAAT UMI=CGCTGCCACGTGTCATCGCGTTAAAT
(read 3)
>UMI-579_de29dab7-6fb4-4f72-beff-5371e592a33a_ATTCGTCTTAGTGGACCGTTCTGGCC UMI=ATTCGTCTTAGTGGACCGTTCTGGCC
(read 1)
>UMI-579_7f10085a-f5e0-44b9-a4b5-bab389f5f990_ATTCGTCTTAGTGGACCGTTCTGGCC UMI=ATTCGTCTTAGTGGACCGTTCTGGCC
(read 2)
>UMI-579_6246d246-e10a-444a-a4e4-8dff60f392aa_ATTCGTCTTAGTGGACCGTTCTGGCC UMI=ATTCGTCTTAGTGGACCGTTCTGGCC
(read 3)
>UMI-579_55896231-efb2-4a1d-808a-8a9d00207e7c_ATTCGTCTTAGTGGACCGTTCTGGCC UMI=ATTCGTCTTAGTGGACCGTTCTGGCC
(read 4)
```

Using the command:

```
medaka smolecule --threads 4 --depth 3 --model r941_min_high_g360 --chunk_ovlp 0 outDir in.fasta
```

in.fasta contains ~10,000 reads that are grouped together by UMIs, which correspond to amplicon sequencing of a pool of different variants of the same gene. Thus, the different consensus sequences that I'd like to get out shouldn't be stitched together, which is why I set --chunk_ovlp to 0. This helped avoid some error with stitch with some smaller test data, but now this is failing in some obscure way with this larger dataset. Here is what appears in the beginning:

```[11:57:19 - root] The path sequences/UMI/ie4-P30_medaka exists. Results will be overwritten.
[11:57:19 - Smolecule] Given one input file, subreads are assumed to be grouped by read.
[11:57:19 - Smolecule] Running spoa pre-medaka consensus for all reads.
[12:20:14 - Smolecule] Writing medaka input bam for 10474 reads.
[12:20:21 - Smolecule] Running medaka consensus.
[12:20:21 - Predict] Reducing threads to 2, anymore is a waste.
[12:20:21 - Predict] It looks like you are running medaka without a GPU and attempted to set a high number of threads. We have scaled this down to an optimal number. If you wish to improve performance please see https://nanoporetech.github.io/medaka/installation.html#improving-parallelism.
[12:20:21 - Predict] Setting tensorflow inter/intra-op threads to 2/1.
[12:20:21 - Predict] Processing region(s): UMI-558:0-1482 UMI-447:0-1494 UMI-293:0-1480 UMI-24:0-1483 UMI-687:0-1469
```

It then lists all of the different UMI groups and starts processing them:

```
[12:20:21 - Predict] Using model: /home/redwood/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[12:20:21 - Predict] Processing 10474 long region(s) with batching.
[12:20:21 - MdlStore] filepath /home/redwood/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[12:20:21 - Sampler] Initializing sampler for consensus of region UMI-558:0-1482.
[12:20:21 - Sampler] Initializing sampler for consensus of region UMI-447:0-1494.
[12:20:21 - PWorker] Running inference for 15.2M draft bases.
[12:20:22 - Feature] Processed UMI-558:0.0-1481.0 (median depth 94.0)
[12:20:22 - Sampler] Took 0.28s to make features.
[12:20:22 - Sampler] Initializing sampler for consensus of region UMI-293:0-1480.
[12:20:22 - Feature] Processed UMI-447:0.0-1493.0 (median depth 93.0)
[12:20:22 - Sampler] Took 0.36s to make features.
[12:20:22 - Sampler] Initializing sampler for consensus of region UMI-24:0-1483.
[12:20:22 - Feature] Processed UMI-293:0.0-1479.0 (median depth 112.0)
[12:20:22 - Sampler] Took 0.10s to make features.
[12:20:22 - Sampler] Initializing sampler for consensus of region UMI-687:0-1469
```

After finishing making the consensus sequences, I get this obscure error message:

```
[11:16:15 - Feature] Processed UMI-40183:0.0-1421.0 (median depth 3.0)
[11:16:15 - Sampler] Took 0.12s to make features.
[11:16:15 - Feature] Processed UMI-40242:0.0-1434.0 (median depth 3.0)
[11:16:15 - Sampler] Took 0.12s to make features.
[11:16:16 - PWorker] Batches in cache: 2.
[11:16:17 - PWorker] 100.0% Done (15.2/15.2 Mbases) in 1043.1s
[11:16:17 - PWorker] Processed 225 batches
[11:16:17 - PWorker] All done, 0 remainder regions.
[11:16:17 - Predict] Finished processing all regions.
[11:16:17 - Smolecule] Running medaka stitch.
[11:16:17 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:18 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:18 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:18 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:18 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:19 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:19 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:19 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:19 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:19 - DataIndx] Loaded 1/1 (100.00%) sample files.
[11:16:19 - DataIndx] Loaded 1/1 (100.00%) sample files.
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::system_error'
std::system_error'
  what():  Invalid argument
  what():  Invalid argument
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/concurrent/futures/process.py", line 394, in _queue_management_worker
    work_item.future.set_exception(bpe)
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/concurrent/futures/_base.py", line 539, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
concurrent.futures._base.InvalidStateError: CANCELLED: <Future at 0x7fb6b13e6700 state=cancelled>
Traceback (most recent call last):
  File "/home/redwood/miniconda3/envs/maple/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/medaka.py", line 702, in main
    args.func(args)
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/smolecule.py", line 464, in main
    medaka.stitch.stitch(args)
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/stitch.py", line 205, in stitch
    for (rname, start, stop), seq_parts in contigs:
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/stitch.py", line 135, in collapse_neighbours
    for contig in contigs:
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/redwood/miniconda3/envs/maple/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

I'm currently attempting to just switch to processing the data as single files, but using this setup would be preferable as it is less obscure to a user. I'd also like to know if theres something I need to do to enable GPU usage, as the machine I'm using does have a GPU with CUDA installed that it should be able to utilize.

Thanks!

**Comment by cjw85** [comment]
You should not set `--chunk_ovlp 0`, this controls how the consensus calculation is chunked through the pileup of for a given set of reads.

To use a GPU you will need to ensure you have the correct NVidia driver, CUDA version, and cuDNN version to support tensorflow version 2.2.2. I believe that information is listed here: https://www.tensorflow.org/install/source#gpu

The error you've observed looks to be something first going awry with `spoa`, this portion:
```
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::system_error'
std::system_error'
  what():  Invalid argument
  what():  Invalid argument
 ```
or the message is not coming from medaka itself. I suspect this is having a knock on effect for medaka hence the following messy error.

**Comment by gordonrix** [comment]
Thanks for the quick reply. Can you elaborate on what I should set chunk_ovlp to? My reads technically don't have any overlap at all as they are reads of distinct molecules that are not being used to stitch together a larger consensus sequence. I may be misunderstanding what this parameter is for though.

**Comment by gordonrix** [comment]
I've implemented a workaround in which I split all the UMI groups into separate fasta files and process them separately. I suspect it would be faster to use GPU and run it all on one file, and would like to test that at some point, but for now I'm happy to close this if you'd give me some guidance on the --chunk_ovlp option :)

**Comment by cjw85** [comment]
You should leave the `--chunk_ovlp` option as the default value. There is a performance benefit to setting a smaller value, but this can lead to a decrease in accuracy.
