### ISSUE TITLE
'medaka smolecule --method racon' fails when provided with 6 sequences

### ISSUE THREAD

**Issue by gordonrix** [nanoporetech/medaka#302]
command:
```medaka smolecule --method racon out reads.fasta```

When reads.fasta contains 5 sequences, the command is successful:

```
[20:10:44 - Smolecule] Given one input file, subreads are assumed to be grouped by read.
[20:10:44 - Smolecule] Running racon pre-medaka consensus for all reads.
[20:10:44 - Smolecule] Writing medaka input bam for 1 reads.
[20:10:44 - Smolecule] Running medaka consensus.
[20:10:44 - Predict] Setting tensorflow inter/intra-op threads to 1/1.
[20:10:44 - Predict] Processing region(s): UMI-0:0-1453
[20:10:44 - Predict] Using model: /home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[20:10:44 - Predict] Processing 1 long region(s) with batching.
[20:10:44 - MdlStore] filepath /home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5
[20:10:45 - Sampler] Initializing sampler for consensus of region UMI-0:0-1453.
[20:10:45 - PWorker] Running inference for 0.0M draft bases.
[20:10:45 - Feature] Processed UMI-0:0.0-1452.0 (median depth 8.0)
[20:10:45 - Sampler] Took 0.05s to make features.
[20:10:46 - PWorker] Processed 1 batches
[20:10:46 - PWorker] All done, 0 remainder regions.
[20:10:46 - Predict] Finished processing all regions.
[20:10:46 - Smolecule] Running medaka stitch.
[20:10:46 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:10:46 - DataIndx] Loaded 1/1 (100.00%) sample files.
[20:10:46 - Smolecule] Single-molecule consensus sequences written to out/consensus.fasta.
[20:10:46 - Smolecule] POA time: 0s, medaka time: 2s
```

However when 6 sequences are present:
```
>UMI-0_70b5a032-552d-4753-bc66-eaba22886c97_TTATAGTCCGGCATCCTGTGATGAGT UMI=TTATAGTCCGGCATCCTGTGATGAGT
TCGGTGTCTTTGTGTTAACCAACTTCCGTGTAGGGAGCCGTAGGTTATAGTCCGGCAGAT
GACCTATGCATAGGAAGGTCTATACGAAACAAAAAGATTAATAACTTTCAAATATCAGAA
AAATGTAGAAACATGTGATAAGCTCATAGACATGTAAAGTCGACATGAAAGGCTGCTTCG
ATTCATTGCGGTGGCCAGTACGTGCCGGAAATCTGATACCCGGCTCTGGAAGAACTGGAA
GCTGCGTGCCGAAGAAATCATGAAAGATGAGTCTTTCTGGAAAGATTCAATGACCTGCTG
CGCGATTATGCGGGTCGTCCGACTCCGCTATTACTCGCGTCGCCTGTCCGAGAAAAATAC
GGTGCTCGCATCTATCTGAAGCGTATGAAGACCTGCTGCATACTGGTGCGCATAAAATCA
ATAACGCTATCGGCCGGGTTCTGCTGGCAAAGAAGGTGGGCAGGCTCGTATCATTGCTGA
AACGGGTGCTGGTCAACACGGCGTAGCAACTGCTGCCGCAGCAGCGCTGTTCGGTATGGA
ATGTAATAGCCAATCATCTATGGGCGAAGAAGACACGATCCGCCAAGAAACCGAACGTTG
AACGTATGAAACTGCTGGGTGCTAAAGTTGTACCGGTAAAATCCGGTAGCCGTACCCTGA
AAGACGCAATTAACGAAGCTCTGCGTGGCTGGATTACCAACCTGCAGACCACCTATTACG
TAATCGGCTCTGTGGTTGGTCCACTATATCCGATTATCGTACGTAACTTCCAAGGTTATC
GAAGAGACCAAGAAAGCAGATTCTGGAGAAAGAAGGCCGTCTGGCCGGACTACATCGTTG
CGTGCGTGGGTGGTGGCTCTAACGCTGCCGGTATCTTCTATCCGTTTATCGATTCTGGTG
TGAAGCTGATCGGCGTAAAGCCGGTGGCGAGGTCTGGAAACCGGTAAACGTAGAAGCTAT
CTGCTGGAAGGTAAAATCGGCTACTGCGGTTCCTGAACGCGTTCGTTCTGCAGGATGACT
GGGGTCAAGTTCAGGTGACGCACTCCCGTCTCCGCTGGCCTGGACTACTCCGGTGTCGGT
CCGGAACACGCCTATTACGGCGTGAGACCGGTAAAGTGCTGTACTGTGACCGATGAAGAA
GCTCTGGACGCATTCATCGAACTGTCTCGCCTGGAAGGCATCATCCCAACCCTGGAGTCT
TCTCACGCACCTGGCTTATCTGAAGATCAACATCAAGAGATGCAAGTTGTGGTGGTTAAT
CTGTCTGGTCGCATTGGTGACAAGGATCTGGAATCTGTACTGAACCACCCGTATGTTCGC
GAACGCATCCGCCTCAGTATCATCATCATCATCATTAAGAGCTCGCCTTAAATCTGTGCG
CATGCTTTTTCGCCGGGGTGAGTGGGTCATACTCCTGTGATGAGTCACTCGCACTGACTC
GATGTTCTTGGTT
>UMI-0_3dff9819-551e-49f4-bf62-e3618388a359_TTATAGTCCGGCATCCTGTGATGAGT UMI=TTATAGTCCGGCATCCTGTGATGAGT
TTATGTCTGTGTTAACCAACTTCCGTGTAGAGACTGCGCAGGTTATAGTCCGGCAGATGA
CCTATACATAGGAAGATCTATAGAAACAAAAAGATTAATAACTTTCAAATATCAGAAAAA
TGTAGAAACATGTGATAAGCTCATAGACATGTAAAGTCGACATGAAAGGCTATCGGTCCG
TACGGTGGCCAGTACGTGCCGGAAACTGATGCCGGCTCTGGAAGAACTGGAAGCTGCGTA
CGAAGAAATCATGAAAGATGAGTCTTCTGGAAAGAATTCAATGACCTGCTGCGCGATTAT
GCGGGTCGTCGATTTCCGCTGTACTCCCACGTCGCCTGTCCGAGAAATACGGTGCTCGCA
TCTATCTGAAACGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATCG
GCCAGGTTGCCCTGCTGGCAAAGAAGGTGGGCAAGACTCGTATCATTGCTGAAACGGGTG
CTGGTCAGCACGGCGTAGCAATTGCCGCCGCAGCAGCGCTGTTCGGTATGGAATGTGTAA
TCTATATGGGCGAAGAAGACACGATCCGCCAGAAACCGAACGTTGAACGTATGAAACCGT
TGGGTGCTAAAGTTGTACCGGTAAATCCAGCCGTACCCTGAAAGACGCAATTAACGAAGC
TCTGCGTGACTGGATTACCAACCTGCAGACCACCCATTACGTGATCGGCTCTGTGGTTGG
TCCGCACCCATATCCGATTATCGTACGTAACTTCCAAAAGGTTATCGGCGAAGAGACCAA
AGGAAGCAGATTCTGGAGAAAGAAGGCCGTCTGCCGGACTACATCGTTGCGTGCGTGGGT
GGTGGCTCTAACGCTGCCGGTATCTTCTATCCGTTTATCGATCCTGGTGTGAAGTTGATC
GGCGTAGAAGCCGGTGGCGAAGGTCTGGAAACCGGTAAACATGCGGCTTCTCTGCTGTGC
CCGTAAAATTGTGGCTACCTGCACGGTTCTAAGACGTTCGTTCTGCAGGATGACTGGGGT
CAAGTTCAGGTGACGCACTCCGTTCTGCTGGCCTGGACTACCTGGTGTCGGTCCGAACAC
GCCTATTGGCGTGAGACCGGTAAAGTGCTGTACGATGTGCTGCGGGGACCGATGAAGAAG
CTCTGGACGCATTCATCGAACTGTCTCGCCTGGAAGGCATCATCCCAGCCCTGGAGTCTT
CTCACGCACTGGCTTATCTGAAGAAGATCAACATCAAGGGTAAAGTTGTGGTGGTTAATC
TGTCTTGGTCGTCGTGGTGACAAGGATCTGGAATCTGTACTGAACCACCCGTATGTTCGC
GAACGCATCCGCCTCGAGTATCATCATCATCATCATTAAGAGCTCATATGTAAATCTGTG
CGCATGCTTTTTCGCCGGAGTCAATTAGGTCATACTCCTGTGATGAGTCACTGCACTGAC
TCGATGTTCTTGGTTA
>UMI-0_40560588-84a4-433e-b791-0ad5e8e0a182_TTATAGTCCGGCATCCTGTGATGAGT UMI=TTATAGTCCGGCATCCTGTGATGAGT
GTCTTTGTGTTAACCAACTTCCGTGTAGAGACTGCAGGTTATAGTCCGGCAGATGACCTA
TATGATAGAAGATCGGTAGAAACAAAAGATTAATAACTTTCAAATATCAGAAAAATGTAG
AAACACAGATAAGCTCATAGACATGTAAAGTCGACATGAAAGGCTACTTCGGTCCGTATT
GCGGCCAGTACGTGCCGGAAATCCTGATGCCGGCTCTGGAAGAATGGCTATGCGGATGAA
GAAATCATGAAAGATGAGTCCTCTCGGCAGAATCAATGACCTGTTGCGCGATTATGTGCG
GTCGTCCGACTCGCTGTACTCCGGCACGTCGCCTGTCCGAGAAATACGGTGTCTCGTATC
GGTCTGAACGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATCGCGC
TGAATTCTGCTGGCAAAGAAGGGTGGCAAGACTCGTATCATTGCTGAAACGTGCTGGTCA
CACGGCGTAGCAACTGCCGCAGCGCTGTTCGGTATGGAATGCGTAATCTTATACGGGCGA
AGAAGACACGATCCGCCAGAAACCGAACGTTGAAACGCAAGAAACCGCTGGGTGTTAAAG
TTGCACTGAAATCCGGTAAAGCCGTACCCTGAAAGACGCAATTAACGCTTGCGTGACTGG
ATTACCAACCCAGGCAGACCACCTATTACGTGATCGGTTTCAGGTTGGTCCGACCCATAT
CCGATTATCGCACGTAACTTCCAAAAGGCGATTTATGAAGAGGAACGAAGAAGCAGATTC
TGAGAAAGAAGGCTGCCCGTCGGACTACACGTTGCGTGGGTGGTGGCTCTAACGCTGCCG
GTATCTTCATCCGTCGACGACTTAAGAAGCTGATCGGCGTAGAAGCCGGTGGTGGCGAAG
GTCTGGAAACGGTAAACATGCGGCTTCTCTGCTGGAAGGTAAAATCGGCTACCTGCACGG
TTCTAAGACGTTCGTTCTGCAGGATGACTGGGGTCGTTCAGGTGACGCACCCGTCTCCGC
TGGCCTGACTACTCCGGTGTCGGTCCGGAACACGCCTATTGGCGTGGAGACCGGTAAAAG
CGGTTGTACGATGCTGTGACCGATGAAGAAGCTCTGGACGCAGGTCTTATCGAACTGTCT
CGCCGGAAGGCATCATCTCCAGCCTGGAGTCTTCTCACGCACTGGCTTATCTGAAGAAGA
TCAACATCAAGTGGTAAAGTTGTGGTGGTTAATCTGAGTCTGGTCGTGCATAAGGATCTT
GGAATCTAGAGCTGAACCACCTGTATGTCGCGAACGCATCCGCCTTCGAGTATCATCATC
ATCATTAAGAGCTCATAAATCTGTGCGCATGTTGCCGGAGTCAATTAGGTCATACTCCTG
TGATGAGTCACTGCACTCGACTCGATGTTCTTGGTT
>UMI-0_5b726a89-92ba-4903-a8fa-62b7a27e7a60_TTATAGTCCGGCATCCTGTGATGAGT UMI=TTATAGTCCGGCATCCTGTGATGAGT
TTGTGTTAACCAACTTCCGTGTAGAGACTGCGTAGGTTATAGTCCGGCAGATGACCTATA
CATGGGAAGATCTATAGAAACAAAAAGATTAACTTTCAAATATCAGAAAAATGTAGGAAA
CATGTGATAAGCTCATAGACATGTAAAGTCGACGCCGAAAGGCTACTTCGGTCCGTACGG
TGGCCAGTACGTGCCGGAAATCCTGAAATGCCGGCTCTGGAAGAACTGGAAGCTGCGTAC
GAAAGAAATCATGAAGATGAGTCTTTCTGGAAGAATTCAATGACCTGCTGCGCGATGCGG
GTCGTCCGACTCCGCTGTACTCCACACGTCGCCTGTCCGAGAAATACGGTGCTCGCATCT
ATCTGAAACGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATCGGCC
AGGTTCTGCTGGCAAAAGGTGGGCAAGACTCGTATCATTGCTGAAGCAGGTGCTGGTCAG
CACGGCGTAGCAACTGCTGCCGCAGCAGCGCTGTTCGGTATGGAATGTGTAATCTATATG
GGCGAAGAAGGCTTTGATCCGCCAGAAACCGAACGTTGAACGTATGAAACTGCTGGGTGC
TAAAGTTGTACCGGTAAAATCCGGTAGCCGTACCCTGAAAGACACTGATAACGAAGCTCT
GCGTGACTGGATTACCAACCTGCAGACCACCTATTACGTGATCGGCTCTGGCCGTTGAGT
CCCGCCCTTATATCCGATTATCGTACGTAACTTCCAAAGGTTATCGGCGAAGAGACCAAG
AAGCAGATTCTGGAGAAGAGGCCGTCTGCCGGACCATCGTTGCGTGCGTGGGTGGTGGCT
CTAACGCTGCCGGTATCTTCTATCCGTTTATCGATTCTGGTGTGAAGCTGATCGGCGTAG
AAGCCGGTGGCGAAGGTCTGGAAACCGGTAACATGCGGCCTTCTCTGCTGGAGAAGGTAA
AATCGGCTACCTGCGGTTCTAAGACGTTCGTTCTGCAGGATGACTGGGGTCAGGATTCAG
GTGACGCACTCCGTCTCCGCTGGCCTGAGCTACTCCGGTGTCGGTCCGGAACACGCCTAT
TGGCGTGAGACCGGTAAAGTGCTGTACGATGCTGTGACCGATGAAGAAGCTCTGGACGCA
TTCATCGAACTGTCTCGCCTGGAAGGCATCATCCCAACCCTGGAGTCTTCTCACTGGCTT
ATCTGAAGATCAACATCAAGGGTAAAGTTGTGGTGGTTAATCTGTCTGGTCGTGGTGACA
AGGATCTGGAATCTGTACTGAACCACCGTATGTTCGCGAACGCATCGCCTCAGTATCATC
ATCATCATCATTAAGAGCTCATATGTAAATCTGTGCGCATGCTTTTTCGCCGGAGTCAAT
TAGGTCATACTCCTGTGATGAGTCTCGCACTGACTCGATGTTCTTGGTT
>UMI-0_169dd949-f1fd-4bb1-a2c0-2b4d1593684a_TTATAGTCCGGCATCCTGTGATGAGT UMI=TTATAGTCCGGCATCCTGTGATGAGT
TTAACCAACTTCCGTGTAGAACTGCGTAGGTTATAGTCCGGCAGATGACCTATACATAGG
AAGATCTATAGAAACAAAAAGATTAATAACTTTTCAAATATCCAATGTAGAAACATGTGA
TAAGCTCATAGACATGTAAAGTCGACATGAAAGGCTACTTCGGTCATTACGATGGCAGTA
CGTGCCGGAAATCCTGATACGGCTCTGGAAGAGTGGAGAAGCTGCGTACGAAAAGCAGAT
GAGTCTTTCTGGAAAGAATTCAGCCTGCTGCGCGATTATGCGGGTCCGACTCCAGCATGC
TCCTGCACGTCGCCTGTCCGAGAAATACGGTGCTTTCGCATCTATCTGAAACGTGAACCT
GCTGCATACTGGTGCGCATAAAATCAATAACGCTATCGGCCAGGTTCTGCTGGCAAAGAG
ATTGGGCAAGACTCTGTATCAGACTTGCTGAAACAGGTGCTGGTCGCACGGCGTAGCAAC
TGCTGCCACAGCAGCGCTGTTCGATATGTTCGTGCTTAATCTATGGGCGAAAGACACGAT
CCGCCGAAACCGAGCATTGAACGTATGAAACTGCTGGGTGCTAAAAGTTGCCGGTAAAAT
CCGAGCGGCGTACCAGAAGACGCAATTAACGAAGCTCTGCGTGACTGGATTACCAACCTG
CAAGACCACTGTCCGTGATCGGCTCTGTGTGGTCCGCCTTATCCGATTATCGTACGTAAC
TTCCAAAAGGTTATCGAAGAGACCAGAAAGCAAAGATTCTGGAGAAGAGGCCGTCTGCCG
GACTACATCATTGCGTGCGTGTGGTGGCTCTAACGCTGCCGGTATCTTCTATCCGTTTAT
CGATTCTGGTGAAGCTGATCGGCGGCGAAGCCGGTGGCGAAGGTCTGGAAACCGGTAGCA
GCGGCTTCTCTGCTGGAAAGTAAAATCGGCTACCTGCACGGTTCTAAGACGTTCGTTCTG
CAGGATGACTGGGGTCAAGTTCGGGTGACGCACACTCGTCTCCGCTGGCCTGGACTACTC
CGGTGTCGGTCCGGAACACGCCTATTGGCGTGAGACCAGGCAAGTGCTGTGTACGATGCT
GTGACCGATGAAGAAGCTCTGGACGCATTCATCAATTTGTCTCGCCTGGAAGGCATCATC
CCAGCCCTGGAGTCTTCTCACCTGCTGGCTTATCTGAAGATCAACATCAAGGGTAAAGTT
GTGGTGGTTAATCTGTCTGGTCGTGGTGACAAGGATCTGGAATCTGTACTGAACCACCCG
TATGTTCGCGAACGCATCACCTCGATATCATCATCATCATCATTAAAACCATATGTAAAT
CCGTATGCTTTTTCATAGTCAATTAGGTCATACTCCTGTGATGAGTCACTCGCACTGACT
CGATGGTTT
>UMI-0_38615452-7b9c-45db-b4fc-7dd1b708c831_TTATAGTCCGGCATCCTGTGATGAGT UMI=TTATAGTCCGGCATCCTGTGATGAGT
AATTCAACTTCCGTGTAGAGACTGCGTAGGTTATAGTCCGGCAGATGACCTATACATAGG
AAGATCTATAGAAACAAAAAGATTAATAACTTTCAAATATCAGAAAAATGTAGAAACATG
CGATAAGCTCATAGACAATGAAGTCGACATGAAAGGCTACTTCGGTCCGTACGGTGGCCA
GTACGTGCCGGAAATCCTGATGCCGGCTCTGGAAGAACTGGAAGCTGCGTACGAAGAAAT
CATGAAAGATGAGTCTTTCTGGAAAGAACGAACACTCGCTGCGCGATTATGCGGTCGTCC
GACTCCGCTGTACTCCGCACGTCGCCTGTCTGAGAAATACGAAAGCTGCATCTATCTGAA
ACGTGAAGACCTGCTGCATACTGGTGCGCATAAAATCAATAACGCTATCGGCCAGGTTCT
GCTGGCAAAGAAGGTGGGCAAGACTCGTATCATTGTTGAAACGGGTGCTGGTCAGCACGG
CGTAGCAACTGTTGCCGCGCAGCGCCGTTTCGGTATGGAATGTGTAATCTATATGGGCGA
AGAAGACACGATCCGCCAGAAACCGAACGTTGAACGTATGAAACTGCTGGTGCTAAAGTT
GTACCGGTAAAATCCGGTAGCCGTACCCTGAAATTATCGCAATTAACGAAGCCTGCGACT
GGATTACCAACCTGCAGACCACCTATTACGTGATCGGCTCTTGTGGTTGGTCCGCACCCG
TTATCCGATTATCGTACGTAACTTCCAAAAGGTTATCGGCGAAGAGACCAAGAAGCAGAT
CGAGAAAGAAGGCCGTCTCAAGCCGGACTACATCGTTGCGTGCGTGGGTGGTGCCTTAAT
GCTGCTGCATTTCACCTGTTTATCGATTCTGGTGTGAAGCTGATCGGCGTAGAAGCTGGT
GGCGAAGGTCTGGAAACCGGTAGAACATGCGGCTTCTCTGCTGGAAGGTAAATCGTTATC
GCACGGTTCTAAGACGTTCGTTCTGCAGGATGACTGGGGTCAAGTTCAGTGACGCACCCG
TCTCCGCTGGCCTGACTACTCCGGTGTCGGTCCGAACACGCCGCTGGCGTGAGACCGGTA
AAGTGCTGTACGATGCTGTGACCGATGAAGAAGCTCTGGACGCATTCATCGAACTGTCTC
GCCTGGAAGGCATCATCCCAGCCCTGAGTCTTCTCACGCACTGGCTTATCAGTTAGCATC
ACAACATCAAGGGTAAAGTTGTGGTGGTTAATCTGTCTGGTCGTGGTGACAAGGATCTGG
AATCTGTACTGAACCACCTGTATGTTCGCGAACGTATCCGCCTCTGAGTATCATCATCAT
CATCATTAAGAGCTCATATGTAAATCTGCATGCTTTTTCGCCGGAGTCAATTAGGTCATA
CTCCTGTGATGAGTCACTTCGCACTGACTCGATGTTCTTGTT
```

Running the same command gives the following error:

```
[20:14:06 - Smolecule] Given one input file, subreads are assumed to be grouped by read.
[20:14:06 - Smolecule] Running racon pre-medaka consensus for all reads.
[20:14:06 - POAManager] sequence item 1: expected str instance, list found
[20:14:06 - Smolecule] Writing medaka input bam for 0 reads.
[20:14:06 - Smolecule] Running medaka consensus.
[20:14:06 - Predict] Setting tensorflow inter/intra-op threads to 1/1.
Traceback (most recent call last):
  File "/home/popos/miniconda3/envs/maple/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/medaka.py", line 702, in main
    args.func(args)
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/smolecule.py", line 455, in main
    medaka.prediction.predict(args)
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/prediction.py", line 119, in predict
    bam_regions = medaka.common.get_bam_regions(
  File "/home/popos/miniconda3/envs/maple/lib/python3.8/site-packages/medaka/common.py", line 652, in get_bam_regions
    with pysam.AlignmentFile(bam) as bam_fh:
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 991, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
```

**Environment (if you do not have a GPU, write No GPU):**
- medaka version 1.3.3
- installation via conda
- OS: Ubuntu 20
- No GPU

Running the command the default method spoa does not produce an error. Also note, there does seem to be some sort of stochasticity going on that is very difficult to isolate. A similar set of 8 sequences succeeds while adding a 9th fails. Spent too long trying to figure out the exact nature of the issue, hoping you'll be able to.

Thanks!

**Comment by cjw85** [comment]
Hi @gordonrix,

The smolecule subcommand is a bit unloved. I don't believe we use it with the racon option and stick to the spoa version. There is some performance overheard to this, though equally using racon can introduce errors.

Can you provide an example of a set of reads that fails when more are added?
