### ISSUE TITLE
Medaka 1.4.1 stitch error

### ISSUE THREAD

**Issue by Sumsarium** [nanoporetech/medaka#310]
After installing medaka 1.4.1 i get a medaka stitch error. 

I run this command:
```
medaka_consensus \
-t $threads \
-i $files \
-d $draft \
-m $model \
-b 80 \
-o $output/medaka_round1
```

and get this error (after installing 1.4.1):
  
```
[18:06:36 - DataIndx] Loaded 1/1 (100.00%) sample files.
[18:06:36 - DataIndx] Loaded 1/1 (100.00%) sample files.
[18:06:36 - DataIndx] Loaded 1/1 (100.00%) sample files.
[18:06:36 - DataIndx] Loaded 1/1 (100.00%) sample files.
Traceback (most recent call last):
  File "/usr/local/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/medaka/medaka.py", line 702, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/medaka/stitch.py", line 195, in stitch
    contigs, gt = fill_gaps(contigs, args.draft)
  File "/usr/local/lib/python3.8/dist-packages/medaka/stitch.py", line 120, in fill_gaps
    (ref_name, 0, contig_lengths[ref_name]), pieces))
KeyError: b'contig_1'
```

Any input would be much appreciated. Thanks in advance.

**Environment :**
 - Installation method: both pypi and conda both tested
 - OS: Ubuntu 20.04
 - medaka version 1.4.1
 - GPU: RTX 3070
 - Nvidia driver version: 460.80
 - CUDA version: 11.2
 - cuDNN version: 10.1, V10.1.243

**Comment by cjw85** [comment]
Hi Rasmus,

This looks like an issue with h5py/hdflib. Could you run `pip freeze` and `conda list` as appropriate for you installs to report back the package versions of everything in your environments?

**Comment by Sumsarium** [comment]
Sure. From `conda list`:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_tflow_select             2.3.0                       mkl  
absl-py                   0.12.0             pyhd8ed1ab_0    conda-forge
aiohttp                   3.7.4            py38h497a2fe_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
bcftools                  1.12                 h45bccc9_1    bioconda
biopython                 1.79             py38h497a2fe_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
click                     8.0.1            py38h578d9bd_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
gast                      0.3.3                      py_0    conda-forge
google-auth               1.30.0             pyh44b312d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.38.0           py38hdd6454d_0    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
h5py                      2.10.0          nompi_py38h9915d05_106    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
htslib                    1.12                 h9093b5e_1    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        4.4.0            py38h578d9bd_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
isa-l                     2.30.0               ha770c72_4    conda-forge
k8                        0.2.5                h9a82719_1    bioconda
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libprotobuf               3.17.2               h780b84a_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mappy                     2.17             py38h390ddb8_3    bioconda
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
medaka                    1.4.1            py38h130def0_0    bioconda
minimap2                  2.20                 h5bf99c6_0    bioconda
multidict                 5.1.0            py38h497a2fe_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.5           py38h18fd61f_1    conda-forge
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
ont-fast5-api             3.3.0                      py_0    bioconda
openssl                   1.1.1k               h7f98852_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
parasail-python           1.2.4            py38h8e3bb3f_1    bioconda
perl                      5.32.0               h36c2ea0_0    conda-forge
pigz                      2.6                  h27826a3_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
progressbar33             2.4                        py_0    conda-forge
protobuf                  3.17.2           py38h709712a_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyfaidx                   0.5.9.5            pyh3252c3a_0    bioconda
pyjwt                     2.1.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py38hf7546f9_3    bioconda
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pyspoa                    0.0.3            py38hc37a69a_2    bioconda
python                    3.8.10          h49503c6_1_cpython    conda-forge
python-edlib              1.3.8.post2      py38h8c62d01_1    bioconda
python-isal               0.10.0           py38h497a2fe_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
racon                     1.4.20               h9a82719_1    bioconda
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
samtools                  1.12                 h9aed4be_1    bioconda
scipy                     1.6.3            py38h7b17777_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tar                       1.34                 ha1f6473_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.2.0           mkl_py38h6d3daf0_0  
tensorflow-base           2.2.0           mkl_py38h5059a2d_0  
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
whatshap                  1.1              py38h8c62d01_1    bioconda
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py38h497a2fe_3    conda-forge
xopen                     1.1.0            py38h578d9bd_2    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.6.3            py38h497a2fe_1    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

**Comment by cjw85** [comment]
Hmm, I cannot reproduce your error and for the most part my conda environment is the same as yours:

```
$ diff rasmus me
< decorator                 4.4.2                      py_0    conda-forge
---
> decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
29c27
< google-auth               1.30.1             pyhd3eb1b0_0
---
> google-auth               1.30.0             pyh44b312d_0    conda-forge
39c37
< intervaltree              3.1.0                      py_0
---
> intervaltree              3.0.2                      py_0    conda-forge
49c47
< libedit                   3.1.20210216         h27cfd23_1
---
> libedit                   3.1.20191231         he28a2e2_2    conda-forge
70c68
< networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
---
> networkx                  2.5                        py_0    conda-forge
84c82
< pyasn1-modules            0.2.8                      py_0
---
> pyasn1-modules            0.2.7                      py_0    conda-forge
104c102
< setuptools                52.0.0           py38h06a4308_0
---
> setuptools                49.6.0           py38h578d9bd_3    conda-forge
109c107
< tensorboard               2.5.0                      py_0
---
> tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
113c111
< tensorflow-estimator      2.5.0              pyh7b7c402_0
---
> tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
115,117c113,115
< tk                        8.6.10               hed695b0_1    conda-forge
< typing-extensions         3.10.0.0             hd8ed1ab_0    conda-forge
< typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
---
> tk                        8.6.10               h21135ba_1    conda-forge
> typing-extensions         3.7.4.3                       0    conda-forge
> typing_extensions         3.7.4.3                    py_0    conda-forge
```

The PyPI package also runs and gives me expected outputs.

**Comment by Sumsarium** [comment]
I can now confirm that it works on  another node, i.e. it´s a local issue. I am clossing the issue. I thank you for your time. Much appreciated!

**Comment by Phhere** [comment]
Our solution to this issue was to decodethe byte string to a ascii string in this line:
https://github.com/nanoporetech/medaka/blob/master/medaka/stitch.py#L92
```python
ref_name, start, stop = info
ref_name = ref_name.decode("utf-8") 
```
