### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_gru1/strided_slice:0) to a numpy array.

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/medaka#313]
**Describe the bug**
medaka consensus failing with python error

**Logging**
```
Command output:
  Checking program versions
  This is medaka 1.4.3
  Program    Version    Required   Pass
  bcftools   1.12       1.11       True
  bgzip      1.12       1.11       True
  minimap2   2.20       2.11       True
  samtools   1.12       1.11       True
  tabix      1.12       1.11       True
  Aligning basecalls to draft
  Removing previous index file /data/2021-07-01_kewell_p9424/work/48/21b1f44e95e0e135070316226b0e5a/P9424.contigs.racon.fasta.mmi
  Removing previous index file /data/2021-07-01_kewell_p9424/work/48/21b1f44e95e0e135070316226b0e5a/P9424.contigs.racon.fasta.fai
  Running medaka consensus
  Failed to run medaka consensus.

Command error:
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/medaka.py", line 707, in main
      args.func(args)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/prediction.py", line 160, in predict
      model = model_store.load_model(time_steps=args.chunk_len)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/datastore.py", line 159, in load_model
      self.model = model_partial_function(time_steps=time_steps)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/models.py", line 146, in build_model
      model.add(Bidirectional(gru, input_shape=input_shape))
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
      result = method(self, *args, **kwargs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 198, in add
      layer(x)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/wrappers.py", line 531, in __call__
      return super(Bidirectional, self).__call__(inputs, **kwargs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
      outputs = call_fn(cast_inputs, *args, **kwargs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/wrappers.py", line 645, in call
      initial_state=forward_state, **kwargs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 654, in __call__
      return super(RNN, self).__call__(inputs, **kwargs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
      outputs = call_fn(cast_inputs, *args, **kwargs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 408, in call
      inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 848, in _process_inputs
      initial_state = self.get_initial_state(inputs)
    File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 637, in get_initial_state
          inputs=None, batch_size=batch_size, dtype=dtype)
    
    NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_gru1/strided_slice:0) to a numpy array.
```
**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: pip install
 - OS: [e.g. Ubuntu 20.04]
 - medaka version: 1.4.3
 - GPU model: NO GPU

**Comment by JWDebler** [comment]
I updated tensorflow and now get a different error:

```
[04:29:22 - DataIndx] Loaded 1/1 (100.00%) sample files.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/medaka.py", line 707, in main
    args.func(args)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/stitch.py", line 195, in stitch
    contigs, gt = fill_gaps(contigs, args.draft)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/medaka/stitch.py", line 120, in fill_gaps
    (ref_name, 0, contig_lengths[ref_name]), pieces))
KeyError: b'tig00000019'
Failed to stitch consensus chunks.
```

**Comment by JWDebler** [comment]
Installed it into a fresh conda environment and there it works.
