### ISSUE TITLE
haploid2diploid failing because of unsorted vcf

### ISSUE THREAD

**Issue by rekham1077** [nanoporetech/medaka#324]
Hello, 

I keep getting an error message when running medaka_variant. I have tried increasing memory as I saw a similar issue posted where that helped but that does not seem to be the problem here.

Error message is below, I would appreciate any help.

 VCF written to medaka_variant/round_1_hap_2.vcf.
+ Merging vcfs to diploid vcf
- Running medaka haploid2diploid
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 707, in main
    args.func(args)
  File "/home/ec2-user/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 925, in haploid2diploid
    convertor = Haploid2DiploidConverter(args.vcf1, args.vcf2, args.ref_fasta,
  File "/home/ec2-user/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 853, in __init__
    vcf.index()  # create tree
  File "/home/ec2-user/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 613, in index
    for variant in self._parse():
  File "/home/ec2-user/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/vcf.py", line 594, in _parse
    raise IOError(
OSError: .vcf is unsorted at index #77088.
* Failed to run medaka haploid2diploid.

**Comment by cjw85** [comment]
Hi @rekham1077 

Thanks for reporting this. Our current recommendation for diploid calling is to use [clair3](https://github.com/HKU-BAL/Clair3) which typically produces better results than the workflow implemented within medaka.

**Comment by rekham1077** [comment]
@cjw85 Okay, thanks I will try that. I do have mostly diploid samples, so clair3 should work. However, I also have some tetraploid yeast strains that I would like to perform variant calling on - do you have a recommendation for that?

**Comment by cjw85** [comment]
We have never looked past ploidy-2; I'm not aware of any community efforts that attempt to call higher ploidies.

**Comment by cjw85** [comment]
Closing this issue, as the functionality used is now deprecated.
