### ISSUE TITLE
CPU incompatibility - allow older version of tensorflow

### ISSUE THREAD

**Issue by asthara10** [nanoporetech/medaka#327]
Hi,

I am using medaka inside a Docker container in a Virtual Machine. 
When I try to obtain a consensus with `medaka consensus` I obtain the error "Illegal instruction (core dumped)".
After researching through the internet, I arrived to the conclusion that the CPU in the virtual machine is not compatible with the current tensorflow version and downgraded it to the first version that I could find to work (1.2.1) as seen in this [issue](https://github.com/tensorflow/tfjs/issues/2631) 

The problem is that medaka requires tensorflow v2.2.2, and now I am getting the following error:
```
Traceback (most recent call last):
  File "/medaka/venv/bin/medaka", line 8, in <module>
    sys.exit(main())
  File "/medaka/venv/lib/python3.6/site-packages/medaka/medaka.py", line 669, in main
    args.func(args)
  File "/medaka/venv/lib/python3.6/site-packages/medaka/prediction.py", line 89, in predict
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'
```

Is there any workaround that I could use to get this issue fixed?

Thank you in advance for your help.

The CPU specifications from `/proc/cpuinfo`
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 1999.998
cache size	: 16384 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm
bogomips	: 3999.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

I need to use medaka v1.1.3, but the error is the same when I install the latest version 1.4.3.
I installed medaka with pip3.

The Linux version is:
`Linux 3e2277c7c5e2 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by cjw85** [comment]
There is no workaround for this issue.

Can I ask why you are trying to use medaka from within a Docker container from within a virtual machine. Would a simpler setup not suffice? Medaka is available as both a vanilla Python package from PyPI and a conda package from bioconda.

**Comment by asthara10** [comment]
Hi @cjw85, thank you for your reply.

In this case, medaka is part of a web toot that I am developing, and it's containerized with docker for portability. I am actually considering the possibility to install all programs inside the virtual machine directly, which will ease the installation, but I am afraid that the problem of the CPU incompatibility will persist. The virtual machine is where we host all our web applications.

**Comment by cjw85** [comment]
If it is a hard requirement to use the VM you have available, then you will need to compile the tensorflow Python package yourself such that it is compiled with an instruction set compatible with the VM. Instructions for doing this can be found in the tensorflow documentation.

**Comment by darachm** [comment]
@asthara10 I just ran into this and am trying to figure it out

I noticed a while back that tensorflow didn't run on my ancient bioinformatics server. Apparently this is because of AVX instructions after tensorflow 1.6 ( https://www.tensorflow.org/install/source ). So, what I did was compile it inside a Singularity container on my old computer https://github.com/darachm/containers/blob/main/tensorflow/Singularity.tensorflow-v2.5.0-compiled . That *totally works for tensorflow* but *does not work* for medaka, as I built upon that container to install medaka. So I believe the problem may be more complex than just compiling tensorflow, but I will update y'all if I find a solution to this.

My error is:

    /usr/local/bin/medaka_consensus: line 16: 4185124 Illegal instruction     (core dumped) medaka tools list_models

I am now wondering if other medaka dependencies must be compiled from scratch for old computer compatibility : ( ...

**Comment by darachm** [comment]
I was able to build and test medaka, compiling from source, in a Singularity container.
I did have to also:
- install the ubuntu packages `python3-virtualenv` _and_ `python3-venv`
- install `git-lfs` and then run `git lfs install` command before the medaka git pull
- since the `make install` doesn't, well, install, I think installed the egg using

And the result is

    /usr/local/bin/medaka_consensus: line 16: 48317 Illegal instruction     (core dumped) medaka tools list_models

Running just

    /usr/local/bin/medaka tools list_models

gets me

    Illegal instruction (core dumped)

So.... looks like the new instructions are in _multiple_ *places*. This is looking like a lot of fun, to hunt for binaries

**Comment by asthara10** [comment]
Hi @darachm, 

I was struggling for a while with the compilation from source of both tensorflow and medaka. In the end, I gave up and contacted my IT service to find a solution for running the programs on a different machine.

I would be curious to know if you manage to find a solution!

**Comment by darachm** [comment]
Nothing yet... FYI this is an old one, a [Xeon X5570, 2009-vintage](https://ark.intel.com/content/www/us/en/ark/products/37111/intel-xeon-processor-x5570-8m-cache-2-93-ghz-6-40-gt-s-intel-qpi.html). Old servers are cheap and have a lot of RAM!

- rebuilt the container on this-machine-compiled Tensorflow 2.2.0 image - still "Illegal instruction" when trying to `medaka tools list_models`
- used singularity to convert/launch from the docker container recommended on the README - still "Illegal instruction"

This is my development box, so maybe I'll need to figure out the piping with another polisher and then just hope that medaka runs fine on the big final computers. ¯\_(ツ)_/¯
