### ISSUE TITLE
running medaka on gridion, tensorflow-gpu not compatible with GPU

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/medaka#33]
I removed TensorFlow and installed the GPU version but when running medaka_consensus I get a crash (below).

I installed medaka (0.6.0-py36h2b5150b_0) and tensorflow-gpu (1.12.0-h0d30ee6_0) using miniconda in a py3 conda env but do not dare to install CUDA software by fear of interfering with the original ONT software on the GridION.

Is there a way to run medaka with GPU on my gridION (2xGeForce GTX 1080 Ti) or should I use only cpu's?

Thanks

```
...
Running medaka consensus
Using TensorFlow backend.
[13:01:54 - Predict] Processing region(s): tig00000001:0-1469063 tig00000003:0-25183 tig00000005:0-1053078 tig00000009:0-1042324 tig00000012:0-24609 tig00000014:0-988579 tig00000016:0-875005 tig00000019:0-1047544 tig00000022:0-873730 tig00000027:0-920396 tig00000031:0-676909 tig00000035:0-748747 tig00000037:0-764060 tig00000039:0-209276 tig00000042:0-653884 tig00000058:0-692998 tig00000059:0-772142 tig00000062:0-816770 tig00000066:0-553488 tig00000067:0-580323 tig00000068:0-530610 tig00000077:0-409975 tig00000079:0-417209 tig00000080:0-429052 tig00000082:0-357446 tig00000093:0-308749 tig00000095:0-36675 tig00000098:0-265607 tig00000102:0-200009 tig00000105:0-261715 tig00000109:0-104085 tig00000112:0-36029 tig00000114:0-40744 tig00000117:0-27693 tig00000119:0-179847 tig00000150:0-12418 tig00000156:0-23170 tig00000159:0-16860 tig00000161:0-1825 tig00000170:0-3380 tig00000172:0-58317 tig00000191:0-1836 tig00000202:0-15093 tig00000210:0-9564 tig00000213:0-16630 tig00000276:0-3889 tig00000286:0-560358 tig00000287:0-68667 tig00000288:0-462709 tig00000289:0-13786 tig00000290:0-581156 tig00000291:0-208241 tig00007300:0-12563 tig00007301:0-1285605 tig00007302:0-954263 tig00007303:0-16559 tig00007304:0-795945 tig00007305:0-35880 tig00007306:0-30213 tig00007307:0-38796 tig00007308:0-6443 tig00007309:0-4305 tig00007310:0-24086 tig00007311:0-20001
/opt/miniconda3/envs/py3/lib/python3.6/site-packages/medaka/datastore.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return {g: yaml.load(self.fh[g][()]) for g in groups if g in self.fh}
[13:01:54 - Predict] Setting tensorflow threads to 8.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py3/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/py3/lib/python3.6/site-packages/medaka/medaka.py", line 261, in main
    args.func(args)
  File "/opt/miniconda3/envs/py3/lib/python3.6/site-packages/medaka/inference.py", line 535, in predict
    inter_op_parallelism_threads=args.threads)
  File "/opt/miniconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/opt/miniconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
Failed to run medaka consensus.
```

**Comment by cjw85** [comment]
Hi @splaisan,

Installing medaka onto a GridION is currently not supported. More generally medaka using CPU only is generally sufficiently performant.

**Comment by splaisan** [comment]
Thanks
Will do with cpu then.
Best
