### ISSUE TITLE
error in medaka snp: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by ogrecio** [nanoporetech/medaka#344]
I installed medaka using miniconda (conda create -n medaka -c conda-forge -c bioconda medaka)

I need to get variants from a fastq file. I have a reference genome. I run mini_align to get the bam files 
`mini_align -i sample.fastq -r $referenceGenome -m r941_min_high_g360 -p calls_to_draft.bam -t 2`
Found minimap files.
[M::main::21.550*0.47] loaded/built the index for 32 target sequence(s)
[M::mm_mapopt_update::23.372*0.52] mid_occ = 709
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 32
[M::mm_idx_stat::24.137*0.53] distinct minimizers: 97021653 (40.92% are singletons); average occurrences: 5.157; average spacing: 5.340; total length: 2671711444
[M::worker_pipeline::1039.793*0.96] mapped 92535 sequences
[M::worker_pipeline::2013.747*0.97] mapped 93015 sequences
[M::worker_pipeline::2827.772*0.97] mapped 77362 sequences
[M::main] Version: 2.23-r1111
[M::main] CMD: minimap2 -x map-ont --MD -t 1 -a -A 2 -B 4 -O 4,24 -E 2,1 /mnt/lustre/scratch//home/csic/mgr/ogr/ReferenceGenomes/genome.fa.mmi /mnt/lustre/scratch/home/csic/mgr/ogr/sample.fastq
[M::main] Real time: 2828.296 sec; CPU: 2744.363 sec; Peak RSS: 8.955 GB
[bam_sort_core] merging from 3 files and 1 in-memory blocks...

and then the medaka snp to extracts snp variants, and I got the following error.

`medaka snp $referenceGenome reads.bam outfile
`[16:26:27 - DataIndx] No sample_registry in reads.bam
Traceback (most recent call last):
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 707, in main
    args.func(args)
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/variant.py", line 125, in snps_from_hdf
    index = medaka.datastore.DataIndex(args.inputs)
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 379, in __init__
    self.metadata = self._load_metadata()
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 417, in _load_metadata
    with DataStore(first_file) as ds:
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 208, in __init__
    self.fh = h5py.File(self.filename, self.mode)
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

Any help?

medaka --version
medaka 1.5.0

Linux version: Linux version 3.10.0-862.14.4.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Sep 21 09:07:21 UTC 2018

**Comment by cjw85** [comment]
For haploid variant calling see the [Usage](https://github.com/nanoporetech/medaka#usage) section of the README. For diploid calling we recommend use of [clair3](https://github.com/HKU-BAL/Clair3) which is used in our [wf-human-snp](https://github.com/epi2me-labs/wf-human-snp) workflow.

You issue above stems from providing an alignment BAM file to a program expecting neural network outputs. The correct workflow is outlined in the `medaka_haploid_variant` script if you want to run in isolation the several commands required.

**Comment by ogrecio** [comment]
Hi,
thanks for your response.
I understand then that the input must be in fastq format. Correct?
I tried that as:
`medaka snp $referenceGenome sample.fastq outfile
`
and didn't work either
```

[23:21:06 - DataIndx] No sample_registry in /mnt/lustre/scratch/home/csic/mgr/ogr/lowpass/inputFiles/barcode02.trimm.fastq
Traceback (most recent call last):
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 707, in main
    args.func(args)
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/variant.py", line 125, in snps_from_hdf
    index = medaka.datastore.DataIndex(args.inputs)
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 379, in __init__
    self.metadata = self._load_metadata()
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 417, in _load_metadata
    with DataStore(first_file) as ds:
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/medaka/datastore.py", line 208, in __init__
    self.fh = h5py.File(self.filename, self.mode)
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/mnt/lustre/scratch/home/csic/mgr/ogr/programs/conda/envs/medaka/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

```
I was checking clair3 but not working. I need to perform diploid variant calling in a cow genome. Sequencing was done in a gridION.

**Comment by cjw85** [comment]
Support for diploid variant calling with medaka is deprecated and the convenience scripts implementing a workflow have been removed. We recommend clair3 for this task.

The program you are attempting to run requires the output from the `medaka consensus` command run with a SNP calling model. Again I would not advise using this and instead use clair3.

**Comment by CDC1688** [comment]
I am using previous release of Medaka for diploid variant calling, according to the official release benchmark,  the F1 score was much higher than clair3. any reason for recommending clair3 ?

**Comment by cjw85** [comment]
The current version of Clair3 has superior performance for indel calling.
