### ISSUE TITLE
Unable to execute Medaka

### ISSUE THREAD

**Issue by bioramg** [nanoporetech/medaka#360]
Hello,
I am trying to polish the ONT assembly with Illumina reads. When I try to execute, I am getting an error
I installed medaka using bioconda tool 
Command:
medaka_consensus -i /home/Illumina_PE.fastq -r /home/ont_draft.fasta -m r941_min_high_g303

Traceback (most recent call last):
  File "/home/anaconda3/envs/medaka/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 12, in <module>
    import medaka.features
  File "/home/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/features.py", line 17, in <module>
    import medaka.labels
  File "/home/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/labels.py", line 14, in <module>
    import medaka.rle
  File "/home/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/rle.py", line 12, in <module>
    from ont_fast5_api.fast5_interface import get_fast5_file
ModuleNotFoundError: No module named 'ont_fast5_api.fast5_interface'

Please suggest.

**Comment by cjw85** [comment]
Hi @bioramg,

Two things here:
1) This appears that you have not successfully followed the installation instructions as `ont_fast5_interface` is declared as a dependency so should be installed
2) medaka is designed for the correction of ONT assemblies with ONT longreads. It will not work to correct an assembly with Illumina data.

Finally, it helps us greatly in diagnosing issues if you use fill in the issue template on Github, providing all the requested information.
