### ISSUE TITLE
Medaka Variant apparent Error

### ISSUE THREAD

**Issue by nhartwic** [nanoporetech/medaka#38]
I'm currently testing the medaka variant pipeline and seem to have encountered an error. I've copied the tail of the stderr below...

[23:36:46 - Sampler] Initializing sampler for consensus or region Consensus_Consensus_Consensus_ctg586:0-59347.
[23:36:48 - Feature] Pileup counts do not span requested region, requested Consensus_Consensus_Consensus_ctg586:0-59347, received 0-59345.
[23:36:48 - Feature] Processed Consensus_Consensus_Consensus_ctg586:0.0-59346.0 (median depth 42.0)
[23:36:48 - Sampler] Took 1.21s to make features.
[23:36:48 - Sampler] Initializing sampler for consensus or region Consensus_Consensus_Consensus_ctg587:0-57289.
[23:36:48 - Feature] Could not process sample with bam_to_sample_c, using python code instead.
(index 0 is out of bounds for axis 0 with size 0).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/site-packages/medaka/common.py", line 446, in gen_to_queue
    for item in generator:
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/site-packages/medaka/common.py", line 477, in grouper
    batch.append(next(gen))
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/site-packages/medaka/inference.py", line 478, in sample_gen
    yield from data_gen.samples
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/site-packages/medaka/features.py", line 607, in samples
    self._fill_features()
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/site-packages/medaka/features.py", line 592, in _fill_features
    self.bam, self.region, self.rle_ref, self.read_fraction)
  File "/home/nhartwic/.conda/envs/new_medaka/lib/python3.6/site-packages/medaka/features.py", line 316, in bam_to_sample
    raise NotImplementedError("Filtering alignments by tag is not supported in python code.")
NotImplementedError: Filtering alignments by tag is not supported in python code.

[23:38:02 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221342.7s
[23:39:47 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221447.4s
[23:41:34 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221554.1s
[23:43:20 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221660.9s
[23:45:07 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221767.1s
[23:46:58 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221878.1s
[23:48:47 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 221987.6s
[23:50:36 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 222096.1s
[23:52:23 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 222203.6s
[23:54:10 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 222310.1s
[23:55:55 - PWorker] 100.0% Done (2809.2/2809.2 Mbases) in 222415.4s

The medaka variant process still seems to be running, though it hasn't produced any output in over 12 hours and seems to be hung.

Any plans to support filtering alignments by tag in python code? What causes medaka to use a pythonic implementation for this contig? Is it just length? Is there any way I could modify my data set to run medaka variant?

**Comment by cjw85** [comment]
Falling back to a python implementation should not be occurring under normal use (its a bit of legacy code which needs updating). Unfortunately the fall through is masking the true error here. Can you share your input `.bam` and reference `.fasta`?

**Comment by nhartwic** [comment]
Sure. The bam file is approximately 116 gigs. How would you recommend I send it to you?

**Comment by cjw85** [comment]
Sorry for the tardy reply,

I could not find your contact details, if you email support@nanoporetech.com referencing this issue, we can set up an upload.

**Comment by nhartwic** [comment]
Email sent. Sorry for the late response here.

**Comment by cjw85** [comment]
I'm going to close this issue due to lack of activity. The code has changed fairly significantly since March such that I would guess that the previous issue is no longer relevant.
