### ISSUE TITLE
Speeding up medaka_variant / weird behaviour

### ISSUE THREAD

**Issue by oneillkza** [nanoporetech/medaka#39]
I'm trying running Medaka Variant on an Nvidia DGX box (8xTesla GPUs). I have a few queries:

1. Is there any way to get it to make better use of the GPUs (and to more finely control CUDA usage)? Based on gpustat, it's deployed processes to all 8, but is only really using the first one. Right now, it's not doing anything, but at peak it never seemed to use more than 25% of the processing power of the first GPU.

gpustat:
```
                 Tue Apr  2 13:04:00 2019  410.78
[0] Tesla V100-SXM2-32GB | 35'C,   0 % | 30932 / 32480 MB | koneill(30921M)
[1] Tesla V100-SXM2-32GB | 35'C,   0 % |   502 / 32480 MB | koneill(491M)
[2] Tesla V100-SXM2-32GB | 34'C,   0 % |   502 / 32480 MB | koneill(491M)
[3] Tesla V100-SXM2-32GB | 34'C,   0 % |   502 / 32480 MB | koneill(491M)
[4] Tesla V100-SXM2-32GB | 36'C,   0 % |   502 / 32480 MB | koneill(491M)
[5] Tesla V100-SXM2-32GB | 37'C,   0 % |   502 / 32480 MB | koneill(491M)
[6] Tesla V100-SXM2-32GB | 38'C,   0 % |   502 / 32480 MB | koneill(491M)
[7] Tesla V100-SXM2-32GB | 38'C,   0 % |   502 / 32480 MB | koneill(491M)

```

2. I'm also testing it on CPUs, and it seems to be using ~70-80 CPus. However, the servers I'm running it on are shared, and it would be best if I could control CPU usage so as to be a considerate co-user of these resources. Is there a parameter that can be passed to medaka_variant to limit the maximum number of CPUs/threads?

3. For the GPU run, it seems to have gotten stuck. It ran for 14 hours to do the "long regions", then had a 4:45 hour gap before processing the short regions (with no logging during this time). It's now another four hours later after doing the short regions, and it's been sitting in a single CPU thread, not using the GPU or other CPUs for that entire time.

Is this normal/expected behaviour?

Would it be possible to get more granular logging during these long delays?

Would it be possible to parallelise better during these times?

Logs below (snipped)
```
medaka_variant -r GRCh37-lite.fa \
        -b promethion_NA19240.bam.dup.bam \
        -o medaka_variant_gpu \
        -t 4
+ medaka_variant -r GRCh37-lite.fa -b promethion_NA19240.bam.dup.bam -o medaka_variant_gpu -t 4
Checking program versions
Program    Version    Required   Pass     
bgzip      1.9        1.9        True     
minimap2   2.11       2.11       True     
samtools   1.9        1.9        True     
tabix      1.9        1.9        True     

======================================
Running medaka consensus /projects/koneill_prj/promethion/promethion_NA19240.bam.dup.bam 
======================================

Using TensorFlow backend.
[15:11:30 - Predict] Processing region(s): 1:0-249250621 2:0-243199373 3:0-198022430 4:0-191154276 5:0-180915260 6:0-171115067 7:0-159138663 8:0-146364022 9:0-141213431 10:0-135534747 11:0-135006516 12:0-133851895 13:0-115169878 14:0-107349540 15:0-102531392 16:0-90354753 17:0-81195210 18:0-78077248 19:0-59128983 20:0-63025520 21:0-48129895 22:0-51304566 X:0-155270560 Y:0-59373566 MT:0-16569 GL000207.1:0-4262 GL000226.1:0-15008 GL000229.1:0-19913 GL000231.1:0-27386 GL000210.1:0-27682 GL000239.1:0-33824 GL000235.1:0-34474 GL000201.1:0-36148 GL000247.1:0-36422 GL000245.1:0-36651 GL000197.1:0-37175 GL000203.1:0-37498 GL000246.1:0-38154 GL000249.1:0-38502 GL000196.1:0-38914 GL000248.1:0-39786 GL000244.1:0-39929 GL000238.1:0-39939 GL000202.1:0-40103 GL000234.1:0-40531 GL000232.1:0-40652 GL000206.1:0-41001 GL000240.1:0-41933 GL000236.1:0-41934 GL000241.1:0-42152 GL000243.1:0-43341 GL000242.1:0-43523 GL000230.1:0-43691 GL000237.1:0-45867 GL000233.1:0-45941 GL000204.1:0-81310 GL000198.1:0-90085 GL000208.1:0-92689 GL000191.1:0-106433 GL000227.1:0-128374 GL000228.1:0-129120 GL000214.1:0-137718 GL000221.1:0-155397 GL000209.1:0-159169 GL000218.1:0-161147 GL000220.1:0-161802 GL000213.1:0-164239 GL000211.1:0-166566 GL000199.1:0-169874 GL000217.1:0-172149 GL000216.1:0-172294 GL000215.1:0-172545 GL000205.1:0-174588 GL000219.1:0-179198 GL000224.1:0-179693 GL000223.1:0-180455 GL000195.1:0-182896 GL000212.1:0-186858 GL000222.1:0-186861 GL000200.1:0-187035 GL000193.1:0-189789 GL000194.1:0-191469 GL000225.1:0-211173 GL000192.1:0-547496
[15:11:30 - Predict] Setting tensorflow threads to 4.
[15:11:36 - Predict] Found 3171 long and 2 short regions.
[15:11:36 - Predict] Processing long regions.
[15:11:36 - ModelLoad] Building model (steps, features, classes): (10000, 10, 5)
[15:11:37 - ModelLoad] Loading weights from /projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/medaka/data/r941_trans_model.hdf5
[15:11:38 - PWorker] Running inference for 3104.9M draft bases.
[15:11:38 - Sampler] Initializing sampler for consensus or region 1:0-1000000.
[15:11:39 - Feature] Pileup counts do not span requested region, requested 1:0-1000000, received 10000-999999.
[15:11:40 - Feature] Processed 1:10000.0-1000000.1 (median depth 64.0)
[15:11:40 - Sampler] Took 2.13s to make features.

<<<snip>>>

[05:05:09 - Sampler] Initializing sampler for consensus or region GL000225.1:0-211173.
[05:05:13 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50015.4s
[05:05:18 - Feature] Processed GL000225.1:0.0-211173.0 (median depth 709.0)
[05:05:18 - Sampler] Took 8.14s to make features.
[05:05:18 - Sampler] Initializing sampler for consensus or region GL000192.1:0-547496.
[05:05:19 - Feature] Pileup counts do not span requested region, requested GL000192.1:0-547496, received 3095-547495.
[05:05:19 - Feature] Processed GL000192.1:3095.0-547496.0 (median depth 59.0)
[05:05:19 - Sampler] Took 1.37s to make features.
[05:05:25 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50027.6s
[05:05:42 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50044.4s
[05:05:55 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50057.1s
[05:06:10 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50072.5s
[05:06:22 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50084.6s
[05:06:38 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50100.7s
[05:06:50 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50112.8s
[05:07:03 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50125.6s
[05:07:19 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50141.0s
[05:07:30 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50152.9s
[05:07:44 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50166.1s
[05:07:57 - PWorker] 100.0% Done (3104.9/3104.9 Mbases) in 50179.3s
[09:43:38 - PWorker] All done
[09:43:38 - Predict] Processing short regions
[09:43:38 - ModelLoad] Building model (steps, features, classes): (None, 10, 5)
[09:43:39 - ModelLoad] Loading weights from /projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/medaka/data/r941_trans_model.hdf5
[09:43:39 - PWorker] Running inference for 0.0M draft bases.
[09:43:40 - Sampler] Initializing sampler for consensus or region 11:134999000-135006516.
[09:43:40 - Feature] Pileup-feature is zero-length for 11:134999000-135006516 indicating no reads in this region.
[09:43:40 - Sampler] Took 0.12s to make features.
[09:43:41 - PWorker] All done
[09:43:41 - PWorker] Running inference for 0.0M draft bases.
[09:43:41 - Sampler] Initializing sampler for consensus or region GL000207.1:0-4262.
[09:43:41 - Feature] Pileup counts do not span requested region, requested GL000207.1:0-4262, received 0-4254.
[09:43:41 - Feature] Processed GL000207.1:0.0-4255.0 (median depth 18.0)
[09:43:41 - Sampler] Took 0.09s to make features.
```

**Comment by mwykes** [comment]
Thank you for your query.

With respect to your first question, medaka currently makes use of a single GPU at a time to run the network. Setting the environmental variable CUDA_VISIBLE_DEVICES=0 will tell TensorFlow to use the first GPU, and also prevent any memory being used on the other GPUs.

If you wish to make use of more than one GPU at a time, you could use GNU parallel to run 8 tasks concurrently processing different genomic regions. The simplest way to do this would be to process a single chromosome at a time.

`for i in {1..22}; do echo ${i}; done | parallel --jobs 8 --results medaka_variant_logs CUDA_VISIBLE_DEVICES={%} medaka_variant -R {} -b $bam  -r $ref  -o medaka_variant_{} -t $threads_per_region`

For your second question, if you use the `-t` option to `medaka_variant` to tell it to use N threads, medaka will use a maximum of N+4 threads. The extra 4 threads are used for reading the bam, and the number of threads used by tensorflow is also limited to N. I’ve just run a test with 8 threads and never saw the CPU usage exceed 12 (as measured by htop). What is your value of 70-80 based on? 

For your third question, we have not seen such long delays between processing long and short regions. It’s hard to know from your log file if the first stage of `medaka_variant` (running `medaka consensus` on all reads) has finished. Normally there would be a `[timestamp - Predict] Finished processing all regions.` message once it was done. However, if you are redirecting stdout to a file and your operating system is buffering the stdout, it could be that that part of the log has not yet been written. Can you see the name of the process still running? Do you have any vcf files in your output directory? The next step after medaka consensus is to call SNPs from the consensus probabilities, and then run WhatsHap to phase the SNPs and tag reads by haplotype. Both of these processes are serial, which might explain why you see it using just 1 thread. 

Regarding improved parallelisation, a future release of [katuali](https://github.com/nanoporetech/katuali) will pull apart the tasks serially executed with `medaka_variant` such that each task can be run using appropriate resources. This would allow one to be running the medaka consensus network on multiple genomic regions each using a single GPU while concurrently calling and  phasing variants on CPU for genomic regions already processed by GPU. This would also allow tasks to be distributed across a grid, so you could use GPUs on your DGX box just to run the network, and use any other CPU resource you have available for the other tasks.

**Comment by oneillkza** [comment]
Thanks for the response @mwykes.

Yes, my next thought had been to use parallel over genomic regions. One slight concern I have with this is that at present, medaka_variant seems to make copies of the entire bam even when a small region is specified. (See below for the work directory for running over 21:21300000-22305000, the region mentioned in the docs):


```
$ ls -lh
total 425G
-rw-r--r-- 1 koneill users  87M Apr  2 14:24 round_0_hap_mixed_probs.hdf
-rw-r--r-- 1 koneill users 212G Apr  2 16:54 round_0_hap_mixed_thresh_0.04_phased.bam
-rw-r--r-- 1 koneill users  72M Apr  2 17:23 round_0_hap_mixed_thresh_0.04_phased.bam.bai
-rw-r--r-- 1 koneill users 834K Apr  2 14:25 round_0_hap_mixed_thresh_0.04_phased.vcf
-rw-r--r-- 1 koneill users 193K Apr  2 14:25 round_0_hap_mixed_thresh_0.04_phased.vcf.gz
-rw-r--r-- 1 koneill users  706 Apr  2 14:25 round_0_hap_mixed_thresh_0.04_phased.vcf.gz.tbi
-rw-r--r-- 1 koneill users 795K Apr  2 14:24 round_0_hap_mixed_thresh_0.04_unphased.vcf
-rw-r--r-- 1 koneill users 248K Apr  2 17:25 round_1_final_rephased.vcf
-rw-r--r-- 1 koneill users  62K Apr  2 17:25 round_1_final_rephased.vcf.gz
-rw-r--r-- 1 koneill users  687 Apr  2 17:25 round_1_final_rephased.vcf.gz.tbi
-rw-r--r-- 1 koneill users 219K Apr  2 17:24 round_1_final.vcf
-rw-r--r-- 1 koneill users  70M Apr  2 17:23 round_1_hap_1_probs.hdf
-rw-r--r-- 1 koneill users 399K Apr  2 17:24 round_1_hap_1.vcf
-rw-r--r-- 1 koneill users  68M Apr  2 17:24 round_1_hap_2_probs.hdf
-rw-r--r-- 1 koneill users 397K Apr  2 17:24 round_1_hap_2.vcf
-rw-r--r-- 1 koneill users 212G Apr  2 20:07 round_1_phased.bam
-rw-r--r-- 1 koneill users  72M Apr  2 20:35 round_1_phased.bam.bai
-rw-r--r-- 1 koneill users 295K Apr  2 20:37 round_2_final_phased.vcf
-rw-r--r-- 1 koneill users 259K Apr  2 20:36 round_2_final_unphased.vcf
-rw-r--r-- 1 koneill users  70M Apr  2 20:36 round_2_hap_1_probs.hdf
-rw-r--r-- 1 koneill users 450K Apr  2 20:36 round_2_hap_1.vcf
-rw-r--r-- 1 koneill users 834K Apr  2 20:36 round_2_hap_1_with_hap2.vcf
-rw-r--r-- 1 koneill users  68M Apr  2 20:36 round_2_hap_2_probs.hdf
-rw-r--r-- 1 koneill users 461K Apr  2 20:36 round_2_hap_2.vcf
-rw-r--r-- 1 koneill users 833K Apr  2 20:36 round_2_hap_2_with_hap1.vcf
```
So each working directory is around 425G. Splitting the genome into 23 chunks would need about 10TB of workspace. This isn't impossible (we have petabytes kicking around), but would require a chat with our Systems team to get that much carved out for one run.

It also seems like this is a time bottleneck -- going by timestamps it's taking 2.5 hours to generate each BAM, while the rest of the workflow is taking minutes. 

Digging into the code, it seems like this is an issue with whatshap, which does not seem to have an option to only work with a region of interest in the bam, so always processes the whole bam. Probably the solution would be to add a step to medaka_variant to use samtools to subset the bam before passing it to whatshap, so whatshap only operates on the region of interest.


Re: CPU usage, I'm testing medaka_variant separately on a 144-core server (with no GPUs / no tensorflow backend). My estimate of 70-80 CPUs used is based on what I saw in top (registering around 6,000-7,000% CPU).

**Comment by oneillkza** [comment]
Incidentally, the whole-genome GPU run crashed:

```
=============================================
Running whatshap tag using round_0_hap_mixed_thresh_0.04_phased.vcf.gz.
=============================================

Traceback (most recent call last):
  File "/projects/koneill_prj/conda/envs/medaka_gpu/bin/whatshap", line 12, in <module>
    sys.exit(main())
  File "/projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/whatshap/haplotag.py", line 310, in main
    run_haplotag(**vars(args))
  File "/projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/whatshap/haplotag.py", line 120, in run_haplotag
    vcf_reader = VcfReader(variant_file, indels=True, phases=True)
  File "/projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/whatshap/vcf.py", line 291, in __init__
    self._vcf_reader = vcf.Reader(filename=path)
  File "/projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/projects/koneill_prj/conda/envs/medaka_gpu/lib/python3.6/site-packages/vcf/parser.py", line 317, in _parse_metainfo
    line = next(self.reader)
StopIteration
Failed to partition reads in round 0.
```

Contents of work directory:

```
$ ls -l
total 260751512
-rw-r--r-- 1 koneill users 263613326936 Apr  2 13:43 round_0_hap_mixed_probs.hdf
-rw-r--r-- 1 koneill users            0 Apr  2 14:22 round_0_hap_mixed_thresh_0.04_phased.vcf
-rw-r--r-- 1 koneill users           28 Apr  3 09:48 round_0_hap_mixed_thresh_0.04_phased.vcf.gz
-rw-r--r-- 1 koneill users           72 Apr  3 09:48 round_0_hap_mixed_thresh_0.04_phased.vcf.gz.tbi
-rw-r--r-- 1 koneill users   2349102801 Apr  3 09:48 round_0_hap_mixed_thresh_0.04_unphased.vcf
```
The complete log is here: 
[run_medaka_variant_gpu.sh_2019-04-01_15:11:25.log](https://github.com/nanoporetech/medaka/files/3040649/run_medaka_variant_gpu.sh_2019-04-01_15.11.25.log)

**Comment by mwykes** [comment]
Thanks for the update and log file. 

We’re preparing for the next medaka release which will avoid entire bam duplication by extracting the region of interest from the bam using samtools. 

Looking at your failed whole-genome run, line 13794 of the log file suggests that medaka_variant found an existing file `medaka_variant_gpu/round_0_hap_mixed_thresh_0.04_phased.vcf` and hence skipped running `whatshap phase`. 

`medaka_variant` checks for existing output so that it is easy to restart a job which has been interrupted without rerunning anything which has already been run. Did you restart `medaka_variant`, or use the same output directory for two running instances? 

The error message reports that `whatshap haplotag` could not partition reads. This is probably because its input file (the existing output file medaka_variant found, ` round_0_hap_mixed_thresh_0.04_phased.vcf`) is empty, as can be seen from the contents of your working directory.  If you remove that file and it’s associated .gz and .gz.tbi files and rerun medaka_variant, it will start by running whatshap phase; as round_0_hap_mixed_probs.hdf and round_0_hap_mixed_thresh_0.04_unphased.vcf are already present, it will skip rerunning these. 

The CPU usage is still a mystery; when I run top, I see a single process consuming significant CPU resource at a time – this either medaka, which varies between 800% and 1200% when using -t 8, and 100% when running whatshap. Do you see the 6000-7000 in a single medaka process, or is this over several processes? 

The number of threads used by tensorflow is controlled by intra_op_parallelism_threads and inter_op_parallelism_threads, which are both set to the number of threads specified on the command line. Perhaps your higher usage is something to do with MKL - could you try setting the environmental variable [OMP_NUM_THREADS](https://www.tensorflow.org/guide/performance/overview#tuning_mkl_for_the_best_performance) to 1 and see if this has an impact on CPU usage?

**Comment by mwykes** [comment]
By the way, its worth noting that `medaka_variant` has only been tested and benchmarked with flip-flop basecalls and medaka models and not the default `r941_trans` model you are using (see the [documentation](https://nanoporetech.github.io/medaka/snp.html#) for details).

**Comment by oneillkza** [comment]
Thanks @mwykes, that makes sense re: the error. On my first try doing the additional run on a subset, I forgot to change the working directory. I did cancel it, but did not clean up any files, so I'm pretty sure that instance started making the empty phased vcf.

That's great to hear re: including the bam subsetting in the tool. Do you have a rough timeline for when you expect that release?

**Comment by oneillkza** [comment]
Re: transducer vs flipflop, I did note that in the docs, but in practice the only data available for testing is transducer-called, so I'm benchmarking and testing on that (specifically [Wouter De Coster's NA19240 PromethION data](https://gigabaseorgigabyte.wordpress.com/2018/05/24/promethion-human-genome-na19240/) ). We don't actually have a PromethION yet ourselves, although we do have some MinION runs I could pool for internal testing (and which I have called with flip-flop). 

Is using transducer-called data likely to cause major issues?

**Comment by cjw85** [comment]
Basecalls from the flip-flop algorithm are typically more accurate than those from the older transducer algorithm. Results from medaka's variant calling derived from transducer basecalls will not be indicative of the performance which could be obtained with flip-flop basecalls.

**Comment by oneillkza** [comment]
Thanks -- good to know!

**Comment by mwykes** [comment]
> 
> 
> Thanks @mwykes, that makes sense re: the error. On my first try doing the additional run on a subset, I forgot to change the working directory. I did cancel it, but did not clean up any files, so I'm pretty sure that instance started making the empty phased vcf.
> 
> That's great to hear re: including the bam subsetting in the tool. Do you have a rough timeline for when you expect that release?

[`v0.6.5`](https://github.com/nanoporetech/medaka/releases/tag/v0.6.5) of medaka_variant now avoids entire bam duplication by extracting the region of interest from the bam using samtools.

**Comment by oneillkza** [comment]
@mwykes thanks, that's very exciting! I've just got back from vacation, and have given it a try. The time for the 21:21300000-22305000 test region is now around 7 minutes, which is much faster than the 6+ hours it was taking before!

That's still not ideal -- I can reasonably only take about four GPUs on our GPU server, so the best speedup I could get would be fourfold, meaning it would still take around 90 hours to do a genome. It is getting there, though! I definitely look forward to seeing medaka_variant better packaged up in katuali and having its computation better marshalled.

I'll give it a try on the CPU server and see if a broader parallelisation can overcome the slowdown in Medaka from not having the GPUs.

(Note: I am also aware that I'm slightly pushing the limits on the software by using a fairly high coverage run put together from five PromethION flow cells. I do feel that this should be doable, however.)

**Comment by cjw85** [comment]
@oneillkza The latest release of medaka streamlines the variant calling workflow. A whole genome will still take a fairly considerable amount of time however. We are primarily concerned with accuracy over speed in our development; though realise that a useful variant caller is not a slow variant caller.

Please start an new feature request issue if you feel performance is something which needs to be improved further.
