### ISSUE TITLE
medaka_haploid_variant: failed to run medaka consensus

### ISSUE THREAD

**Issue by katefgit** [nanoporetech/medaka#401]
**Describe the bug**
I run `medaka_haploid_variant` using R10.4 reads as input and it stops before a vcf file is created with the following

**Logging**
```
Running medaka consensus
[22:55:42 - Predict] Setting tensorflow inter/intra-op threads to 1/1.
[22:55:42 - Predict] Processing region(s): contig_1_polypolish:0-4394637
[22:55:42 - Predict] Using model: /software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/data/r941_min_hac_variant_g507_model.tar.gz.
[22:55:42 - Predict] Found a GPU.
[22:55:42 - Predict] If cuDNN errors are observed, try setting the environment variable `TF_FORCE_GPU_ALLOW_GROWTH=true`. To explicitely disable use of cuDNN use the commandline option `--disable_cudnn. If OOM (out of memory) errors are found please reduce batch size.
[22:55:42 - Predict] Processing 5 long region(s) with batching.
[22:55:42 - ModelLoad] GPU available: building model with cudnn optimization
[22:55:43 - MdlStrTF] Model <keras.engine.sequential.Sequential object at 0x7f372b80ffd0>
[22:55:43 - MdlStrTF] loading weights from /tmp/tmpfd6lni6k/model/variables/variables
[22:55:43 - BAMFile] Creating pool of 16 BAM file sets.
[22:55:43 - Sampler] Initializing sampler for consensus of region contig_1_polypolish:0-1000000.
[22:55:43 - Sampler] Initializing sampler for consensus of region contig_1_polypolish:999000-1999000.
[22:55:43 - PWorker] Running inference for 4.4M draft bases.
[22:55:47 - Feature] Processed contig_1_polypolish:0.0-999999.0 (median depth 121.0)
[22:55:47 - Sampler] Took 3.72s to make features.
[22:55:47 - Sampler] Initializing sampler for consensus of region contig_1_polypolish:1998000-2998000.
[22:55:47 - Feature] Processed contig_1_polypolish:999000.0-1998999.0 (median depth 89.0)
[22:55:47 - Sampler] Took 3.83s to make features.
[22:55:47 - Sampler] Initializing sampler for consensus of region contig_1_polypolish:2997000-3997000.
[22:55:48 - Feature] Processed contig_1_polypolish:1998000.0-2997999.1 (median depth 82.0)
[22:55:48 - Sampler] Took 1.51s to make features.
[22:55:48 - Sampler] Initializing sampler for consensus of region contig_1_polypolish:3996000-4394637.
[22:55:49 - Feature] Processed contig_1_polypolish:2997000.0-3996999.0 (median depth 105.0)
[22:55:49 - Sampler] Took 1.74s to make features.
[22:55:49 - Feature] Processed contig_1_polypolish:3996000.0-4394636.0 (median depth 136.0)
[22:55:49 - Sampler] Took 0.74s to make features.
2022-11-30 22:56:00.538828: E tensorflow/stream_executor/dnn.cc:764] OOM when allocating tensor with shape[1032651776] and type uint8 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[22:56:00 - MdlStrTF] ModelStoreTF exception <class 'tensorflow.python.framework.errors_impl.InternalError'>
Traceback (most recent call last):
  File "/software/anaconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/medaka.py", line 724, in main
    args.func(args)
  File "/software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/prediction.py", line 166, in predict
    remainder_regions = run_prediction(
  File "/software/anaconda3/envs/medaka/lib/python3.8/site-packages/medaka/prediction.py", line 48, in run_prediction
    class_probs = model.predict_on_batch(x_data)
  File "/software/anaconda3/envs/medaka/lib/python3.8/site-packages/keras/engine/training.py", line 1986, in predict_on_batch
    outputs = self.predict_function(iterator)
  File "/software/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/software/anaconda3/envs/medaka/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError:    Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 3, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 10, 128, 1, 10000, 100, 0] 
	 [[{{node CudnnRNN}}]]
	 [[sequential/bidirectional/backward_gru1/PartitionedCall]] [Op:__inference_predict_function_3261]

Function call stack:
predict_function -> predict_function -> predict_function

Failed to run medaka consensus.
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: mamba in a separate environment
 - OS: Ubuntu 18.04
 - medaka version 1.7.2
 - GPU model NVIDIA
 - Nvidia driver version  470.141.03   
 - CUDA version 11.4
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
It appears you are using a GPU. Can you provide details of the model of GPU you have. From the error it appears that your GPU ran out of memory.

A fix may be to do as is instructed at the top of the logging and reduce the `--batch_size` parameter from the default value and set the environment variable `TF_FORCE_GPU_ALLOW_GROWTH=true`.

If that fails you can convince yourself that the code can run on your data be disabling use of the GPU by setting the environment variable `CUDA_VISIBLE_DEVICES=''`

**Comment by katefgit** [comment]
could it be also related to the model used? I can see in the logging is mentioned ´´´r941_min_hac_variant_g507_model´´´

**Comment by cjw85** [comment]
The error is not caused by using at R9.4.1 model for R10.4 data. But you should definitely change the model to get thr best results for your data.

**Comment by katefgit** [comment]
OK. I am sorry but I cannot find all the info on how to change these parameters. Do you have some input? When using the -help, I don't get any info on how to adjust e.g. ```--batch_size``` for instance or how to change the model. In the new version.

**Comment by katefgit** [comment]
OK. I am sorry but I cannot find all the info on how to change these parameters and clearly I am a newbie. Do you have some input? When using the -help, I don't get any info on how to adjust e.g. --batch_size for instance (I can see in read.me is mentioned as ```-b```, in the ```--help``` is not mentioned) or how to change the model.

**Comment by katefgit** [comment]
could you please advice me on how to change the environment variable?

**Comment by katefgit** [comment]
It work by reducing the ´´´ batch size ´´´ to 30, although my ram could support it e.g. 50. ´´´-b 30 ´´´
