### ISSUE TITLE
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by EllistonV** [nanoporetech/medaka#403]
Hello,

 I am having troubles while trying to run the following command:

`medaka_consensus -i sample.fastq -d assembly.fasta -o clean -m r941_min_fast_g303
`
I get the following result:

```
Checking program versions
Program    Version    Required   Pass     
minimap2   2.11       2.11       True     
samtools   1.3.1      1.3.1      True     
Aligning basecalls to draft
Constructing minimap index.
[M::mm_idx_gen::0.083*1.01] collected minimizers
[M::mm_idx_gen::0.098*1.29] sorted minimizers
[M::main::0.129*1.22] loaded/built the index for 1 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.135*1.21] distinct minimizers: 623917 (98.43% are singletons); average occurrences: 1.032; average spacing: 5.347
[M::main] Version: 2.11-r797
[M::main] CMD: minimap2 -I 16G -x map-ont --MD -d /home/ExtraDrive/PhdStudent4/medaka/assembly.fasta.mmi /home/ExtraDrive/PhdStudent4/medaka/assembly.fasta
[M::main] Real time: 0.139 sec; CPU: 0.167 sec
[samfaipath] build FASTA index...
[M::main::0.030*1.03] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.038*1.02] mid_occ = 12
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.044*1.02] distinct minimizers: 623917 (98.43% are singletons); average occurrences: 1.032; average spacing: 5.347
[M::worker_pipeline::131.994*0.65] mapped 79732 sequences
[M::main] Version: 2.11-r797
[M::main] CMD: minimap2 -x map-ont --MD -t 1 -a /home/ExtraDrive/PhdStudent4/medaka/assembly.fasta.mmi /home/ExtraDrive/PhdStudent4/medaka/sample.fastq
[M::main] Real time: 132.001 sec; CPU: 85.680 sec
[bam_sort_core] merging from 2 files...
Running medaka consensus
Traceback (most recent call last):
  File "/home/phdstudent4/.conda/envs/maria2/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/medaka.py", line 10, in <module>
    from medaka.inference import train, predict
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/inference.py", line 22, in <module>
    from medaka.features import SampleGenerator
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/features.py", line 23, in <module>
    import libmedaka
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

I do not know what it means by `ImportError`. Am I missing a package or something?
In advance, thanks!

**Comment by cjw85** [comment]
Hi @EllistonV,

Please open a new issue and fill out the template, this will help us to assist you.
