### ISSUE TITLE
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory #406

### ISSUE THREAD

**Issue by marianajeeb** [nanoporetech/medaka#406]
Hi,

I am running medaka v1.7.2 under conda environment and getting the following error;

Traceback (most recent call last):
  File "/home/phdstudent4/.conda/envs/maria2/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/medaka.py", line 10, in <module>
    from medaka.inference import train, predict
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/inference.py", line 22, in <module>
    from medaka.features import SampleGenerator
  File "/home/phdstudent4/.conda/envs/maria2/lib/python3.6/site-packages/medaka/features.py", line 23, in <module>
    import libmedaka
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Failed to run medaka consensus.

**Comment by cjw85** [comment]
Hi @marianajeeb,

Could you please open a new issue and use the issue template to provide all the requested information.
