### ISSUE TITLE
medaka GPU

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/medaka#41]
Hi, 

I am currently testing medaka 0.6.2 on GPUs using the promethion machine with its Tensor V100 socket. 

I subset the origina file for testing to a single contig to polish, only working with data from a single contig: ctg55_21516

hdf production seemed so run through, but i got an error thrown after it reached the last contig: 

```
Checking program versions
Program    Version    Required   Pass
bgzip      1.9        1.9        True
minimap2   2.11       2.11       True
samtools   1.9        1.9        True
tabix      1.9        1.9        True
Warning: Output ctg already exists, may use old results.
Not aligning basecalls to draft, calls_to_draft.bam exists.
Running medaka consensus
Using TensorFlow backend.
[14:25:43 - Predict] Processing region(s): ctg1000_107:0-12339 ctg1002_24:0-14544 ctg1004.....
[14:25:43 - Predict] Setting tensorflow threads to 1.
[14:25:43 - Predict] Found 1557 long and 256 short regions.
[14:25:43 - Predict] Processing long regions.
[14:25:43 - ModelLoad] Building model (steps, features, classes): (10000, 10, 5)
[14:25:43 - ModelLoad] With cudnn: True
[14:25:43 - ModelLoad] Loading weights from /home/prom/.conda/envs/medaka/lib/python3.6/site-packages/medaka/data/r941_flip235_model.hdf5
[14:25:43 - PWorker] Running inference for 673.1M draft bases.
[14:25:43 - Sampler] Initializing sampler for consensus or region ctg1000_107:0-12339.
[14:25:43 - Feature] Pileup-feature is zero-length for ctg1000_107:0-12339 indicating no reads in this region.
[14:25:43 - Sampler] Took 0.01s to make features.....


2019-04-09 13:39:55.779570: E tensorflow/stream_executor/cuda/cuda_dnn.cc:82] OOM when allocating tensor with shape[1536000000] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/prom/.conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 261, in main
    args.func(args)
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/medaka/inference.py", line 560, in predict
    tag_name=args.tag_name, tag_value=args.tag_value, tag_keep_missing=args.tag_keep_missing
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/medaka/inference.py", line 489, in run_prediction
    class_probs = model.predict_on_batch(x_data)
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/prom/.conda/envs/medaka/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 3, 0, 0 , [num_layers, input_size, num_units, dir_count, seq_length, batch_size]: [1, 256, 128, 1, 10000, 200]
         [[{{node bidirectional_2/CudnnRNN}} = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="gru", seed=87654321, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bidirectional_2/transpose, bidirectional_2/ExpandDims_1, bidirectional_2/Const, bidirectional_2/concat)]]
Failed to run medaka consensus.

```

I wonder if its subsetting related or if there is some issue with the tensorflow-gpu installation as `tensorflow.python.framework.errors_impl.InternalError: Failed to call ThenRnnForward with model config: ` is indicating? 

Stdout for ctg55: 
```
[13:39:26 - Sampler] Initializing sampler for consensus or region ctg54_1:999000-2000000.
[13:39:26 - Feature] Pileup-feature is zero-length for ctg54_1:999000-2000000 indicating no reads in this region.
[13:39:26 - Sampler] Took 0.02s to make features.
[13:39:26 - Sampler] Initializing sampler for consensus or region ctg54_1:1999000-2207334.
[13:39:26 - Feature] Pileup-feature is zero-length for ctg54_1:1999000-2207334 indicating no reads in this region.
[13:39:26 - Sampler] Took 0.00s to make features.
[13:39:26 - Sampler] Initializing sampler for consensus or region ctg55_21516:0-1000000.
[13:39:32 - Feature] Processed ctg55_21516:0.0-1000000.3 (median depth 59.0)
[13:39:32 - Sampler] Took 5.60s to make features.
[13:39:32 - Sampler] Initializing sampler for consensus or region ctg55_21516:999000-2000000.
[13:39:37 - Feature] Processed ctg55_21516:999000.0-2000000.1 (median depth 56.0)
[13:39:37 - Sampler] Took 5.21s to make features.
[13:39:37 - Sampler] Initializing sampler for consensus or region ctg55_21516:1999000-3000000.
[13:39:39 - Feature] Pileup counts do not span requested region, requested ctg55_21516:1999000-3000000, received 1999000-2207333.
[13:39:39 - Feature] Processed ctg55_21516:1999000.0-2207334.0 (median depth 57.0)
[13:39:39 - Sampler] Took 1.56s to make features.
[13:39:39 - Sampler] Initializing sampler for consensus or region ctg55_21516:2999000-4000000.
[13:39:39 - Feature] Pileup-feature is zero-length for ctg55_21516:2999000-4000000 indicating no reads in this region.
[13:39:39 - Sampler] Took 0.37s to make features.
[13:39:39 - Sampler] Initializing sampler for consensus or region ctg55_21516:3999000-5000000.
[13:39:40 - Feature] Pileup-feature is zero-length for ctg55_21516:3999000-5000000 indicating no reads in this region.
[13:39:40 - Sampler] Took 0.34s to make features.
[13:39:40 - Sampler] Initializing sampler for consensus or region ctg55_21516:4999000-6000000.
[13:39:40 - Feature] Pileup-feature is zero-length for ctg55_21516:4999000-6000000 indicating no reads in this region.
[13:39:40 - Sampler] Took 0.43s to make features.
[13:39:40 - Sampler] Initializing sampler for consensus or region ctg55_21516:5999000-7000000.
[13:39:41 - Feature] Pileup-feature is zero-length for ctg55_21516:5999000-7000000 indicating no reads in this region.
[13:39:41 - Sampler] Took 0.42s to make features.
[13:39:41 - Sampler] Initializing sampler for consensus or region ctg55_21516:6999000-8000000.
[13:39:41 - Feature] Pileup-feature is zero-length for ctg55_21516:6999000-8000000 indicating no reads in this region.
[13:39:41 - Sampler] Took 0.40s to make features.
[13:39:41 - Sampler] Initializing sampler for consensus or region ctg55_21516:7999000-9000000.
[13:39:41 - Feature] Pileup-feature is zero-length for ctg55_21516:7999000-9000000 indicating no reads in this region.
[13:39:41 - Sampler] Took 0.17s to make features.
[13:39:41 - Sampler] Initializing sampler for consensus or region ctg55_21516:8999000-10000000.
[13:39:41 - Feature] Pileup-feature is zero-length for ctg55_21516:8999000-10000000 indicating no reads in this region.
[13:39:41 - Sampler] Took 0.02s to make features.
[13:39:41 - Sampler] Initializing sampler for consensus or region ctg55_21516:9999000-11000000.
[13:39:41 - Feature] Pileup-feature is zero-length for ctg55_21516:9999000-11000000 indicating no reads in this region.
[13:39:41 - Sampler] Took 0.01s to make features.
[13:39:41 - Sampler] Initializing sampler for consensus or region ctg55_21516:10999000-12000000.
[13:39:41 - Feature] Pileup-feature is zero-length for ctg55_21516:10999000-12000000 indicating no reads in this region.
[13:39:41 - Sampler] Took 0.02s to make features.
[13:39:41 - Sampler] Initializing sampler for consensus or region ctg55_21516:11999000-13000000.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg55_21516:11999000-13000000 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.02s to make features.
[13:39:42 - Sampler] Initializing sampler for consensus or region ctg55_21516:12999000-14000000.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg55_21516:12999000-14000000 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.03s to make features.
[13:39:42 - Sampler] Initializing sampler for consensus or region ctg55_21516:13999000-14035920.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg55_21516:13999000-14035920 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.01s to make features.
[13:39:42 - Sampler] Initializing sampler for consensus or region ctg57_1:0-1000000.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg57_1:0-1000000 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.02s to make features.
[13:39:42 - Sampler] Initializing sampler for consensus or region ctg57_1:999000-2000000.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg57_1:999000-2000000 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.01s to make features.
[13:39:42 - Sampler] Initializing sampler for consensus or region ctg57_1:1999000-3000000.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg57_1:1999000-3000000 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.02s to make features.
[13:39:42 - Sampler] Initializing sampler for consensus or region ctg57_1:2999000-4000000.
[13:39:42 - Feature] Pileup-feature is zero-length for ctg57_1:2999000-4000000 indicating no reads in this region.
[13:39:42 - Sampler] Took 0.03s to make features.

```

**Comment by MichelMoser** [comment]
Thanks for the suggestion. Indeed, guppy_basecall_server is occupying the GPUs. Should have stopped it first.
