### ISSUE TITLE
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ZON-ZONG-MIN** [nanoporetech/medaka#420]
I installed medaka on conda `conda install -c bioconda medaka`
but when i use `medaka` instruction, I get the following error :

Traceback (most recent call last):
  File "/bip7_disk/zhongmin111/miniconda3/envs/env_2_25/bin/medaka", line 7, in <module>
    from medaka.medaka import main
  File "/bip7_disk/zhongmin111/miniconda3/envs/env_2_25/lib/python3.6/site-packages/medaka/medaka.py", line 10, in <module>
    from medaka.inference import train, predict
  File "/bip7_disk/zhongmin111/miniconda3/envs/env_2_25/lib/python3.6/site-packages/medaka/inference.py", line 22, in <module>
    from medaka.features import SampleGenerator
  File "/bip7_disk/zhongmin111/miniconda3/envs/env_2_25/lib/python3.6/site-packages/medaka/features.py", line 23, in <module>
    import libmedaka
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Does anyone have the same problem?

My OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

**Comment by cjw85** [comment]
This is related to https://github.com/bioconda/bioconda-recipes/issues/39356, not really something we can control.

You can work around this by running:

```
conda install -c conda-forge -c bioconda htslib==1.16
```

In your conda environment.

**Comment by ZON-ZONG-MIN** [comment]
Thank you!

Do you have a recommended python version?
Or other suggestions for installing medaka

**Comment by cjw85** [comment]
Python versions 3.7-3.10 are supported. Information regarding installation methods can be found in that README.
