### ISSUE TITLE
How to pre-install models in docker container for medaka to run without internet connection?

### ISSUE THREAD

**Issue by ElderMedic** [nanoporetech/medaka#530]
**Describe the bug**
I am trying to pack models into docker container for medaka to run in internet-free environment. This is my dockerfile (btw, where is medaka's official dockerfile? There seems used to be one but deleted? Can you just share it even if deprecated as a reference?):

```Dockerfile
FROM mambaorg/micromamba:latest

USER root

ENV PATH=/opt/conda/bin:$PATH

COPY environment.yml /tmp/environment.yml

RUN micromamba install -y -n base -f /tmp/environment.yml && \
    micromamba clean --all --yes

RUN apt-get update && \
    apt-get install --yes wget && \
    wget https://gitlab.com/m-unlock/scripts/-/raw/master/medaka/medaka.py -O /usr/bin/medaka.py && \
    chmod +x /usr/bin/medaka.py

# download the medaka model
RUN medaka tools download_models

USER $MAMBA_USER

```

docker build went ok and I run the container to check for the models, they are in the expected location:
```sh
(base) mambauser@dd53e84b64f8:/tmp$ ls -l /opt/conda/lib/python3.10/site-packages/medaka/data/
total 308704
-rw-r--r-- 1 root root 1868992 Sep 18 06:07 r103_fast_g507_model.tar.gz
-rw-r--r-- 1 root root 1873132 Sep 18 06:07 r103_fast_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1865026 Sep 18 06:07 r103_fast_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 1862993 Sep 18 06:07 r103_hac_g507_model.tar.gz
-rw-r--r-- 1 root root 1875908 Sep 18 06:07 r103_hac_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1861856 Sep 18 06:07 r103_hac_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 3299554 Sep 18 06:07 r103_min_high_g345_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:07 r103_min_high_g360_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:07 r103_prom_high_g360_model.hdf5
-rw-r--r-- 1 root root 3320034 Sep 18 06:07 r103_prom_snp_g3210_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:07 r103_prom_variant_g3210_model.hdf5
-rw-r--r-- 1 root root 1865674 Sep 18 06:07 r103_sup_g507_model.tar.gz
-rw-r--r-- 1 root root 1872474 Sep 18 06:07 r103_sup_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1862159 Sep 18 06:07 r103_sup_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 2981791 Sep 18 06:07 r1041_e82_260bps_fast_g632_model.tar.gz
-rw-r--r-- 1 root root 3372100 Sep 18 06:07 r1041_e82_260bps_fast_variant_g632_model.tar.gz
-rw-r--r-- 1 root root 3366101 Sep 18 06:07 r1041_e82_260bps_hac_g632_model.tar.gz
-rw-r--r-- 1 root root 3300732 Sep 18 06:07 r1041_e82_260bps_hac_v4.0.0_model.tar.gz
-rw-r--r-- 1 root root 3328856 Sep 18 06:07 r1041_e82_260bps_hac_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 3397383 Sep 18 06:07 r1041_e82_260bps_hac_variant_g632_model.tar.gz
-rw-r--r-- 1 root root 3351219 Sep 18 06:07 r1041_e82_260bps_hac_variant_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 2436433 Sep 18 06:07 r1041_e82_260bps_sup_g632_model.tar.gz
-rw-r--r-- 1 root root 3323063 Sep 18 06:07 r1041_e82_260bps_sup_v4.0.0_model.tar.gz
-rw-r--r-- 1 root root 3344790 Sep 18 06:07 r1041_e82_260bps_sup_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 3410256 Sep 18 06:07 r1041_e82_260bps_sup_variant_g632_model.tar.gz
-rw-r--r-- 1 root root 3333643 Sep 18 06:07 r1041_e82_260bps_sup_variant_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 2437904 Sep 18 06:07 r1041_e82_400bps_fast_g615_model.tar.gz
-rw-r--r-- 1 root root 3177212 Sep 18 06:07 r1041_e82_400bps_fast_g632_model.tar.gz
-rw-r--r-- 1 root root 3365746 Sep 18 06:07 r1041_e82_400bps_fast_variant_g615_model.tar.gz
-rw-r--r-- 1 root root 3395887 Sep 18 06:07 r1041_e82_400bps_fast_variant_g632_model.tar.gz
-rw-r--r-- 1 root root 3338167 Sep 18 06:07 r1041_e82_400bps_hac_g615_model.tar.gz
-rw-r--r-- 1 root root 3386723 Sep 18 06:07 r1041_e82_400bps_hac_g632_model.tar.gz
-rw-r--r-- 1 root root 2370374 Sep 18 06:07 r1041_e82_400bps_hac_v4.0.0_model.tar.gz
-rw-r--r-- 1 root root 3361085 Sep 18 06:07 r1041_e82_400bps_hac_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 3294837 Sep 18 06:07 r1041_e82_400bps_hac_v4.2.0_model.tar.gz
-rwxrwxr-x 2 root root 3316419 Dec 10  2023 r1041_e82_400bps_hac_v4.3.0_model.tar.gz
-rw-r--r-- 1 root root 3386237 Sep 18 06:07 r1041_e82_400bps_hac_variant_g615_model.tar.gz
-rw-r--r-- 1 root root 3404984 Sep 18 06:07 r1041_e82_400bps_hac_variant_g632_model.tar.gz
-rw-r--r-- 1 root root 3337121 Sep 18 06:07 r1041_e82_400bps_hac_variant_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 3344978 Sep 18 06:07 r1041_e82_400bps_hac_variant_v4.2.0_model.tar.gz
-rwxrwxr-x 2 root root 3334828 Dec 10  2023 r1041_e82_400bps_hac_variant_v4.3.0_model.tar.gz
-rw-r--r-- 1 root root 3373001 Sep 18 06:07 r1041_e82_400bps_sup_g615_model.tar.gz
-rw-r--r-- 1 root root 3328291 Sep 18 06:07 r1041_e82_400bps_sup_v4.0.0_model.tar.gz
-rw-r--r-- 1 root root 3343204 Sep 18 06:07 r1041_e82_400bps_sup_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 3320889 Sep 18 06:07 r1041_e82_400bps_sup_v4.2.0_model.tar.gz
-rwxrwxr-x 2 root root 3331823 Dec 10  2023 r1041_e82_400bps_sup_v4.3.0_model.tar.gz
-rw-r--r-- 1 root root 3376463 Sep 18 06:07 r1041_e82_400bps_sup_variant_g615_model.tar.gz
-rw-r--r-- 1 root root 3329015 Sep 18 06:07 r1041_e82_400bps_sup_variant_v4.1.0_model.tar.gz
-rw-r--r-- 1 root root 3327875 Sep 18 06:07 r1041_e82_400bps_sup_variant_v4.2.0_model.tar.gz
-rwxrwxr-x 2 root root 3338143 Dec 10  2023 r1041_e82_400bps_sup_variant_v4.3.0_model.tar.gz
-rw-r--r-- 1 root root 3372276 Sep 18 06:08 r104_e81_fast_g5015_model.tar.gz
-rw-r--r-- 1 root root 3364613 Sep 18 06:08 r104_e81_fast_variant_g5015_model.tar.gz
-rw-r--r-- 1 root root 3370262 Sep 18 06:08 r104_e81_hac_g5015_model.tar.gz
-rw-r--r-- 1 root root 3394457 Sep 18 06:08 r104_e81_hac_variant_g5015_model.tar.gz
-rw-r--r-- 1 root root 3373622 Sep 18 06:08 r104_e81_sup_g5015_model.tar.gz
-rw-r--r-- 1 root root 3405520 Sep 18 06:08 r104_e81_sup_g610_model.tar.gz
-rw-r--r-- 1 root root 3410306 Sep 18 06:08 r104_e81_sup_variant_g610_model.tar.gz
-rw-r--r-- 1 root root 4982296 Sep 18 06:08 r10_min_high_g303_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r10_min_high_g340_model.hdf5
-rw-r--r-- 1 root root 3360260 Sep 18 06:08 r941_e81_fast_g514_model.tar.gz
-rw-r--r-- 1 root root 3395067 Sep 18 06:08 r941_e81_fast_variant_g514_model.tar.gz
-rw-r--r-- 1 root root 3384215 Sep 18 06:08 r941_e81_hac_g514_model.tar.gz
-rw-r--r-- 1 root root 3402671 Sep 18 06:08 r941_e81_hac_variant_g514_model.tar.gz
-rw-r--r-- 1 root root 2430549 Sep 18 06:08 r941_e81_sup_g514_model.tar.gz
-rw-r--r-- 1 root root 3397238 Sep 18 06:08 r941_e81_sup_variant_g514_model.tar.gz
-rw-r--r-- 1 root root 4984574 Sep 18 06:08 r941_min_fast_g303_model.hdf5
-rw-r--r-- 1 root root 1865357 Sep 18 06:08 r941_min_fast_g507_model.tar.gz
-rw-r--r-- 1 root root 1872634 Sep 18 06:08 r941_min_fast_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1862155 Sep 18 06:08 r941_min_fast_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 1860199 Sep 18 06:08 r941_min_hac_g507_model.tar.gz
-rw-r--r-- 1 root root 1872903 Sep 18 06:08 r941_min_hac_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1861342 Sep 18 06:08 r941_min_hac_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 4982440 Sep 18 06:08 r941_min_high_g303_model.hdf5
-rw-r--r-- 1 root root 4981589 Sep 18 06:08 r941_min_high_g330_model.hdf5
-rw-r--r-- 1 root root 4065763 Sep 18 06:08 r941_min_high_g340_rle_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_min_high_g344_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_min_high_g351_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_min_high_g360_model.hdf5
-rw-r--r-- 1 root root 1859510 Sep 18 06:08 r941_min_sup_g507_model.tar.gz
-rw-r--r-- 1 root root 1873249 Sep 18 06:08 r941_min_sup_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1862250 Sep 18 06:08 r941_min_sup_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 4982296 Sep 18 06:08 r941_prom_fast_g303_model.hdf5
-rw-r--r-- 1 root root 1862564 Sep 18 06:08 r941_prom_fast_g507_model.tar.gz
-rw-r--r-- 1 root root 1874556 Sep 18 06:08 r941_prom_fast_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1861254 Sep 18 06:08 r941_prom_fast_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 1864375 Sep 18 06:08 r941_prom_hac_g507_model.tar.gz
-rw-r--r-- 1 root root 1874685 Sep 18 06:08 r941_prom_hac_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1861959 Sep 18 06:08 r941_prom_hac_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 4982296 Sep 18 06:08 r941_prom_high_g303_model.hdf5
-rw-r--r-- 1 root root 4981589 Sep 18 06:08 r941_prom_high_g330_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_prom_high_g344_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_prom_high_g360_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_prom_high_g4011_model.hdf5
-rw-r--r-- 1 root root 3320034 Sep 18 06:08 r941_prom_snp_g303_model.hdf5
-rw-r--r-- 1 root root 3320034 Sep 18 06:08 r941_prom_snp_g322_model.hdf5
-rw-r--r-- 1 root root 3320052 Sep 18 06:08 r941_prom_snp_g360_model.hdf5
-rw-r--r-- 1 root root 1860823 Sep 18 06:08 r941_prom_sup_g507_model.tar.gz
-rw-r--r-- 1 root root 1870843 Sep 18 06:08 r941_prom_sup_snp_g507_model.tar.gz
-rw-r--r-- 1 root root 1862145 Sep 18 06:08 r941_prom_sup_variant_g507_model.tar.gz
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_prom_variant_g303_model.hdf5
-rw-r--r-- 1 root root 3299554 Sep 18 06:08 r941_prom_variant_g322_model.hdf5
-rw-r--r-- 1 root root 3299572 Sep 18 06:08 r941_prom_variant_g360_model.hdf5
-rw-r--r-- 1 root root 3386858 Sep 18 06:08 r941_sup_plant_g610_model.tar.gz
-rw-r--r-- 1 root root 3391630 Sep 18 06:08 r941_sup_plant_variant_g610_model.tar.gz
```

Just to make sure I went into container's default python to check if the models location are where they would be read in by medaka: (using same code as in options.py)

```sh
(base) mambauser@33ccad71b920:/tmp$ /opt/conda/bin/python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
<stdin>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>>> import os
>>> import pathlib
>>>
>>> model_subdir = 'data'
>>> model_stores = (
...     pkg_resources.resource_filename('medaka', model_subdir),
...     os.path.join(
...         str(pathlib.Path.home()), '.{}'.format('medaka'), model_subdir)
... )
>>>
>>> for path in model_stores:
...     print(path)
...
/opt/conda/lib/python3.10/site-packages/medaka/data
/home/mambauser/.medaka/data
>>>
>>> exit()
```

but still when I run this container with `--model r941_min_hac_g507` (should be using downloaded local model, right?), I got error: **medaka.models.DownloadError: The model file for r941_min_hac_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.**

```sh
2024-09-17T18:51:21.865472160+02:00 [1;30mINFO[0m [step medaka] start
2024-09-17T18:51:22.427996475+02:00 [1;30mINFO[0m [job medaka] /unlock/tmp/bb9bd2d9-8b9f-4492-94ed-8a47891fa4c4lb7d100n$ docker \
2024-09-17T18:51:22.428012405+02:00     run \
2024-09-17T18:51:22.428016623+02:00     -i \
2024-09-17T18:51:22.428021362+02:00     --mount=type=bind,source=/unlock/tmp/bb9bd2d9-8b9f-4492-94ed-8a47891fa4c4lb7d100n,target=/rkxOXE \
2024-09-17T18:51:22.428025560+02:00     --mount=type=bind,source=/unlock/tmp/bb9bd2d9-8b9f-4492-94ed-8a47891fa4c4t9ppqsqq,target=/tmp \
2024-09-17T18:51:22.428030078+02:00     --mount=type=bind,source=/unlock/tmp/bb9bd2d9-8b9f-4492-94ed-8a47891fa4c4883eth4c/BMOCK12_subset_5_run_3_spades-medaka_Nanopore_filtered.fastq.gz,target=/var/lib/cwl/stgdf529e4d-049c-47fc-8045-e2dfccd83c8e/BMOCK12_subset_5_run_3_spades-medaka_Nanopore_filtered.fastq.gz,readonly \
2024-09-17T18:51:22.428034156+02:00     --mount=type=bind,source=/unlock/tmp/bb9bd2d9-8b9f-4492-94ed-8a47891fa4c4i9kq7fdb/output/scaffolds.fasta,target=/rkxOXE/scaffolds.fasta,readonly \
2024-09-17T18:51:22.428038214+02:00     --workdir=/rkxOXE \
2024-09-17T18:51:22.428041700+02:00     --read-only=true \
2024-09-17T18:51:22.428045347+02:00     --user=0:0 \
2024-09-17T18:51:22.428051449+02:00     --rm \
2024-09-17T18:51:22.428054995+02:00     --cidfile=/unlock/tmp/bb9bd2d9-8b9f-4492-94ed-8a47891fa4c483uwigc7/20240917165122-427792.cid \
2024-09-17T18:51:22.428058552+02:00     --env=TMPDIR=/tmp \
2024-09-17T18:51:22.428061969+02:00     --env=HOME=/rkxOXE \
2024-09-17T18:51:22.428065936+02:00     docker-registry.wur.nl/m-unlock/docker/medaka:1.11.3 \
2024-09-17T18:51:22.428069503+02:00     medaka.py \
2024-09-17T18:51:22.428073110+02:00     --model \
2024-09-17T18:51:22.428076536+02:00     r941_min_hac_g507 \
2024-09-17T18:51:22.428079993+02:00     -r \
2024-09-17T18:51:22.428085914+02:00     /rkxOXE/scaffolds.fasta \
2024-09-17T18:51:22.428089350+02:00     -i \
2024-09-17T18:51:22.428093318+02:00     /var/lib/cwl/stgdf529e4d-049c-47fc-8045-e2dfccd83c8e/BMOCK12_subset_5_run_3_spades-medaka_Nanopore_filtered.fastq.gz \
2024-09-17T18:51:22.428097005+02:00     -t \
2024-09-17T18:51:22.428100732+02:00     16
2024-09-17T18:51:23.448364750+02:00 Creating fai index file /rkxOXE/scaffolds.fasta.fai
2024-09-17T18:51:23.685936326+02:00 Creating mmi index file /rkxOXE/scaffolds.fasta.map-ont.mmi
2024-09-17T18:51:25.169296574+02:00 [M::mm_idx_gen::1.477*1.01] collected minimizers
2024-09-17T18:51:25.504616797+02:00 [M::mm_idx_gen::1.813*1.37] sorted minimizers
2024-09-17T18:51:25.938023414+02:00 [M::main::2.246*1.30] loaded/built the index for 1551 target sequence(s)
2024-09-17T18:51:25.938037611+02:00 [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1551
2024-09-17T18:51:26.041330629+02:00 [M::mm_idx_stat::2.349*1.29] distinct minimizers: 7432838 (85.86% are singletons); average occurrences: 1.242; average spacing: 5.496
2024-09-17T18:51:26.057319530+02:00 [M::main] Version: 2.17-r941
2024-09-17T18:51:26.057327495+02:00 [M::main] CMD: minimap2 -I 16G -x map-ont -d /rkxOXE/scaffolds.fasta.map-ont.mmi /rkxOXE/scaffolds.fasta
2024-09-17T18:51:26.057332034+02:00 [M::main] Real time: 2.365 sec; CPU: 3.044 sec; Peak RSS: 0.455 GB
2024-09-17T18:51:26.685160235+02:00 [M::main::0.566*1.00] loaded/built the index for 1551 target sequence(s)
2024-09-17T18:51:26.837806741+02:00 [M::mm_mapopt_update::0.718*1.00] mid_occ = 20
2024-09-17T18:51:26.837839563+02:00 [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1551
2024-09-17T18:51:26.936705919+02:00 [M::mm_idx_stat::0.817*1.00] distinct minimizers: 7432838 (85.86% are singletons); average occurrences: 1.242; average spacing: 5.496
2024-09-17T18:51:51.621801435+02:00 [M::worker_pipeline::25.502*11.43] mapped 21524 sequences
2024-09-17T18:51:56.921684935+02:00 [M::worker_pipeline::30.802*9.63] mapped 14389 sequences
2024-09-17T18:51:57.256238161+02:00 [M::main] Version: 2.17-r941
2024-09-17T18:51:57.256248070+02:00 [M::main] CMD: minimap2 -x map-ont --secondary=no -L --MD -t 16 -a /rkxOXE/scaffolds.fasta.map-ont.mmi /var/lib/cwl/stgdf529e4d-049c-47fc-8045-e2dfccd83c8e/BMOCK12_subset_5_run_3_spades-medaka_Nanopore_filtered.fastq.gz
2024-09-17T18:51:57.256253340+02:00 [M::main] Real time: 31.137 sec; CPU: 296.868 sec; Peak RSS: 4.357 GB
2024-09-17T18:51:57.518573265+02:00 [bam_sort_core] merging from 0 files and 16 in-memory blocks...
2024-09-17T18:52:31.907920601+02:00 Traceback (most recent call last):
2024-09-17T18:52:31.907945268+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/medaka.py", line 36, in __call__
2024-09-17T18:52:31.911327021+02:00     model_fp = medaka.models.resolve_model(val)
2024-09-17T18:52:31.911370934+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/models.py", line 81, in resolve_model
2024-09-17T18:52:31.913178606+02:00     raise DownloadError(
2024-09-17T18:52:31.913193694+02:00 medaka.models.DownloadError: The model file for r941_min_hac_g507  Check you are connected to the internet and try again.
2024-09-17T18:52:31.913197742+02:00 
2024-09-17T18:52:31.913201739+02:00 During handling of the above exception, another exception occurred:
2024-09-17T18:52:31.913205586+02:00 
2024-09-17T18:52:31.913209794+02:00 Traceback (most recent call last):
2024-09-17T18:52:31.913214223+02:00   File "/opt/conda/bin/medaka", line 11, in <module>
2024-09-17T18:52:31.913229291+02:00     sys.exit(main())
2024-09-17T18:52:31.913233820+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/medaka.py", line 801, in main
2024-09-17T18:52:31.913397158+02:00     args = parser.parse_args()
2024-09-17T18:52:31.913408119+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1826, in parse_args
2024-09-17T18:52:31.917732180+02:00     args, argv = self.parse_known_args(args, namespace)
2024-09-17T18:52:31.917744473+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1859, in parse_known_args
2024-09-17T18:52:31.918008531+02:00     namespace, args = self._parse_known_args(args, namespace)
2024-09-17T18:52:31.918040692+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 2050, in _parse_known_args
2024-09-17T18:52:31.918289612+02:00     positionals_end_index = consume_positionals(start_index)
2024-09-17T18:52:31.918294691+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 2027, in consume_positionals
2024-09-17T18:52:31.918578327+02:00     take_action(action, args)
2024-09-17T18:52:31.918583246+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1936, in take_action
2024-09-17T18:52:31.918848977+02:00     action(self, namespace, argument_values, option_string)
2024-09-17T18:52:31.918854077+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1214, in __call__
2024-09-17T18:52:31.919056950+02:00     subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
2024-09-17T18:52:31.919066558+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1859, in parse_known_args
2024-09-17T18:52:31.919330416+02:00     namespace, args = self._parse_known_args(args, namespace)
2024-09-17T18:52:31.919350073+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 2068, in _parse_known_args
2024-09-17T18:52:31.919610224+02:00     start_index = consume_optional(start_index)
2024-09-17T18:52:31.919620323+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 2008, in consume_optional
2024-09-17T18:52:31.919894861+02:00     take_action(action, args, option_string)
2024-09-17T18:52:31.919903287+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1936, in take_action
2024-09-17T18:52:31.920167195+02:00     action(self, namespace, argument_values, option_string)
2024-09-17T18:52:31.920172465+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/medaka.py", line 39, in __call__
2024-09-17T18:52:31.920210407+02:00     raise RuntimeError(msg.format(self.dest, str(e)))
2024-09-17T18:52:31.920216428+02:00 RuntimeError: Error validating model from '--model' argument: The model file for r941_min_hac_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again..
2024-09-17T18:52:37.913585370+02:00 Traceback (most recent call last):
2024-09-17T18:52:37.913620236+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/medaka.py", line 36, in __call__
2024-09-17T18:52:37.913630315+02:00     model_fp = medaka.models.resolve_model(val)
2024-09-17T18:52:37.913634373+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/models.py", line 81, in resolve_model
2024-09-17T18:52:37.913640975+02:00     raise DownloadError(
2024-09-17T18:52:37.913652187+02:00 medaka.models.DownloadError: The model file for r941_min_hac_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.
2024-09-17T18:52:37.913656465+02:00 
2024-09-17T18:52:37.913661143+02:00 During handling of the above exception, another exception occurred:
2024-09-17T18:52:37.913665201+02:00 
2024-09-17T18:52:37.913669910+02:00 Traceback (most recent call last):
2024-09-17T18:52:37.913675230+02:00   File "/opt/conda/bin/medaka", line 11, in <module>
2024-09-17T18:52:37.913680300+02:00 Traceback (most recent call last):
2024-09-17T18:52:37.913684568+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/medaka.py", line 36, in __call__
2024-09-17T18:52:37.916865511+02:00     sys.exit(main())
2024-09-17T18:52:37.916878255+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/medaka.py", line 801, in main
2024-09-17T18:52:37.916882864+02:00     model_fp = medaka.models.resolve_model(val)
2024-09-17T18:52:37.916888074+02:00   File "/opt/conda/lib/python3.10/site-packages/medaka/models.py", line 81, in resolve_model
2024-09-17T18:52:37.916893354+02:00     args = parser.parse_args()
2024-09-17T18:52:37.916898083+02:00   File "/opt/conda/lib/python3.10/argparse.py", line 1826, in parse_args
2024-09-17T18:52:37.916902371+02:00     raise DownloadError(
2024-09-17T18:52:37.916906719+02:00 medaka.models.DownloadError: The model file for r941_min_hac_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.
```

so question is:
1. How can I correctly pre-install models in docker image?
2. I noticed that the `model_suffixes = ["_model_pt.tar.gz", ]` in `models.py` has **_pt** in it, but none of the files downloaded with `medaka tools download_models` has **_pt** in its suffix, does it matter? 
3. Can I specify absolute path of a local model file downloaded to be used by medaka? If so, should I include the .tar.gz extension? because I also tried using `--model abs_path` but medaka give me error saying it's not valid model name. 

Thanks!

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method conda
 - OS: Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-112-generic x86_64)
 - medaka version 1.11.3
 - No GPU

**Comment by ElderMedic** [comment]
the environment.yml for building the docker is:
```yaml
channels:
- conda-forge
- bioconda
dependencies:
- medaka=1.11.3
- minimap2=2.17
- htslib=1.17
- samtools=1.17
```

**Comment by cjw85** [comment]
You are running the medaka model download as root but then change the container to be running as `USER $MAMBA_USER`, I suspect this is therefore a permissions error.
