### ISSUE TITLE
Medaka consensus Error: medaka.common.OverlapException

### ISSUE THREAD

**Issue by kishwarshafin** [nanoporetech/medaka#54]
Hello,

We are getting an error at the stitch.py step of `medaka 0.7.0` trying to run on CHM13 sample.

These are the two commands we are running:
```bash
medaka consensus \
--model r941_flip213 \
--threads 64 \
<path_to>/CHM13.shasta.racon4x.hg38_chrX.bam \
<path_to>/CHM13_medaka_consensus_prob.hdf 2>&1 | tee <path_to>/consensus.log
```

Which ends successfully. And we run:
```bash
medaka stitch \
<path_to>/CHM13_medaka_consensus_prob.hdf \ 
<path_to>/CHM13_shasta_racon_medaka_consensus.fasta
```

The Log:
```bash
[14:52:39 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
[14:52:40 - Stitch] Processing 1022.
[14:52:40 - Stitch] Processing 1096.
[14:52:40 - Stitch] Processing 138.
[14:52:47 - Stitch] Processing 156.
[14:53:12 - Stitch] Processing 1562.
[14:53:12 - Stitch] Processing 1564.
[14:53:12 - Stitch] Processing 1622.
[14:53:13 - Stitch] Processing 164.
[14:54:24 - Stitch] Processing 180.
[14:54:39 - Stitch] Processing 280.
[14:54:41 - Stitch] Processing 342.
[14:54:41 - Stitch] Processing 358.
[14:54:41 - Stitch] Processing 36.
[14:57:42 - Stitch] Processing 360.
[14:57:43 - Stitch] Processing 40.
[15:01:08 - Stitch] Processing 44.
Traceback (most recent call last):
  File "/home/kishwar/software/medaka/venv/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.7.0', 'console_scripts', 'medaka')()
  File "/home/kishwar/software/medaka/venv/lib/python3.6/site-packages/medaka-0.7.0-py3.6-linux-x86_64.egg/medaka/medaka.py", line 350, in main
    args.func(args)
  File "/home/kishwar/software/medaka/venv/lib/python3.6/site-packages/medaka-0.7.0-py3.6-linux-x86_64.egg/medaka/stitch.py", line 85, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/home/kishwar/software/medaka/venv/lib/python3.6/site-packages/medaka-0.7.0-py3.6-linux-x86_64.egg/medaka/stitch.py", line 66, in stitch_from_probs
    end_1_ind, start_2_ind = medaka.common.Sample.overlap_indices(s1, s2)
  File "/home/kishwar/software/medaka/venv/lib/python3.6/site-packages/medaka-0.7.0-py3.6-linux-x86_64.egg/medaka/common.py", line 256, in overlap_indices
    raise OverlapException(msg.format(s1.name, s2.name, repr(rel)))
medaka.common.OverlapException: Cannot overlap samples 44:54257964.0-54264156.0 and 44:54264162.0-54265439.6 with relationhip <Relationship.forward_gapped: 's2 follows s1 with a gab inbetween.'>
```

Things we have tried:
* Different builds (on different machines)
* Different thread size
* Different models
* Whole genome execution of CHM13

I have made these two files available for you if you want to look into this.
```bash
wget https://storage.googleapis.com/kishwar-helen/medaka_error_issue/CHM13.shasta.racon4x.hg38_chrX.bam
wget https://storage.googleapis.com/kishwar-helen/medaka_error_issue/CHM13.shasta.racon_4x.hg38_chrX.fa
```
Please let me know if you can help in this regard.

**Comment by cjw85** [comment]
Hi @kishwarshafin,

We have noticed this ourselves this afternoon, there is a simple fix we will try to issue a patched release later tonight.

**Comment by cjw85** [comment]
There is now a v0.7.1 available on pypi and github

**Comment by kishwarshafin** [comment]
Thank you for being so helpful!

I am running the stitch now and looks like the error isn't happening anymore. 

I'll close this issue.
