### ISSUE TITLE
`medaka tools download_models` fails Medaka v2.0.1

### ISSUE THREAD

**Issue by gbouras13** [nanoporetech/medaka#545]
Crossposting from https://github.com/gbouras13/hybracter/issues/111

**Describe the bug**

`medaka tools download_models` fails - only on specific computer (Linux, Intel i9-13900, no gpu, installed via bioconda). It worked fine on the user's other computers, which suggests a specific library is missing.

**Logging**

```
Traceback (most recent call last):
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 35, in __call__
    model_fp = medaka.models.resolve_model(val)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/models.py", line 104, in resolve_model
    raise DownloadError(
medaka.models.DownloadError: The model file for r103_fast_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/bin/medaka", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 836, in main
    args.func(args)
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 366, in download_models
    fp = ResolveModel('--model', 'model')(None, ns, [model], 'model')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.snakemake/conda/b7468e6ab56026e57a2316f2b83f226a_/lib/python3.11/site-packages/medaka/medaka.py", line 38, in __call__
    raise RuntimeError(msg.format(self.dest, str(e)))
RuntimeError: Error validating model from '--model' argument: The model file for r103_fast_g507 is not already installed and could not be downloaded. Check you are connected to the internet and try again.


```

**Comment by gbouras13** [comment]
Closing as user reported it was caused by network connectivity issues.
