### ISSUE TITLE
Medaka stitch fails

### ISSUE THREAD

**Issue by lstevens17** [nanoporetech/medaka#55]
Hello, 

I'm trying to run medaka on my assembly. It seems to work until the stitch step, but then fails with the following error: 

```
Running medaka stitch
[20:25:55 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
[20:25:56 - Stitch] Processing ctg1.
Traceback (most recent call last):
  File "/ceph/users/lstevens/.conda/envs/medaka_env/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/ceph/users/lstevens/.conda/envs/medaka_env/lib/python3.6/site-packages/medaka/medaka.py", line 350, in main
    args.func(args)
  File "/ceph/users/lstevens/.conda/envs/medaka_env/lib/python3.6/site-packages/medaka/stitch.py", line 85, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/ceph/users/lstevens/.conda/envs/medaka_env/lib/python3.6/site-packages/medaka/stitch.py", line 66, in stitch_from_probs
    end_1_ind, start_2_ind = medaka.common.Sample.overlap_indices(s1, s2)
  File "/ceph/users/lstevens/.conda/envs/medaka_env/lib/python3.6/site-packages/medaka/common.py", line 256, in overlap_indices
    raise OverlapException(msg.format(s1.name, s2.name, repr(rel)))
medaka.common.OverlapException: Cannot overlap samples ctg1:0.0-260.0 and ctg1:266.0-3840.0 with relationhip <Relationship.forward_gapped: 's2 follows s1 with a gab inbetween.'>
Failed to stitch consensus chunks.
```

The other steps appear to have completed properly (ie there is no error output and the files `calls_to_draft.bam`, `calls_to_draft.bam.bai`, and `consensus_probs.hdf` exist and are not empty). 

I'm running medaka with the following command: 

`medaka_consensus -i [gzipped_read_fastq] -d [raconpolished_fasta] -o medaka -t 32`

The assembly is from **wtdbg2** and **polished 4x** with racon using the command suggested in your README.

Medaka version is **0.7.0** and installed using **conda**. 

Any ideas what might be wrong? 

Thanks for your help, 

Lewis

**Comment by lstevens17** [comment]
Closing this issue as I noticed you'd responded to/fixed a similar issue today. 

I pulled the latest version to stitch.py into my conda install dir and stitch seems to be working fine now. 

Thanks for your help! 

Lewis
