### ISSUE TITLE
v0.7.0-alpha.1: IndexError tuple index out of range

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/medaka#56]
A medaka_variant process which was running under version v0.7.0-alpha.1 just crashed, error message below.
Let me know if there are any (intermediate) files you would like. This is NA19240 at 20x coverage, full genome. I will restart it but parallelized in windows of 1Mb using the -r option, so I'm not sure if I'll reproduce this issue. I don't know if this bug will still be there be in the most recent version, so feel free to close this if you believe it is already solved.

```
======================================
Running medaka variant with threshold 1
======================================

[09:50:44 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
Traceback (most recent call last):
  File "/home/wdecoster/anaconda3/envs/medaka/bin/medaka", line 10, in <module>
    sys.exit(main())
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 350, in main
    args.func(args)
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/variant.py", line 460, in variants_from_hdf
    decoder = decoder_cls(index.meta, ref_vcf=args.ref_vcf)
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/variant.py", line 160, in __init__
    self.feature_row_names = [fmt_feat(x) for x in meta['medaka_feature_decoding']]
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/variant.py", line 160, in <listcomp>
    self.feature_row_names = [fmt_feat(x) for x in meta['medaka_feature_decoding']]
  File "/home/wdecoster/anaconda3/envs/medaka/lib/python3.6/site-packages/medaka/variant.py", line 159, in <lambda>
    fmt_feat = lambda x: '{}{}{}'.format(x[0], 'rev' if x[1] else 'fwd', x[3] * (x[2] if x[2] is not None else '-'))
IndexError: tuple index out of range
```

**Comment by cjw85** [comment]
Hi again @wdecoster,

I cannot reproduce this with the v0.7.1 release. I think this is again something we fixed before you spotted it. There was an issue with some meta data recorded in some of the model files. I have added a test for the specific property that has failed above so we should catch it testing in future when new models appear.

**Comment by wdecoster** [comment]
Okay, that's great! Thanks for letting me know.
