### ISSUE TITLE
Cannot complete consensus - unclear error

### ISSUE THREAD

**Issue by SRooke** [nanoporetech/medaka#67]
I am trying to run medaka (with GPU) on a test dataset and cannot get past consensus. It throws an exception 'in thread Thread-1' - however I cannot figure out what this means - or what is causing it.

Below is the output from the program:

`Not aligning basecalls to draft, calls_to_draft.bam exists.
Running medaka consensus
[18:22:43 - Predict] Processing region(s): utg000001c:0-4703280
[18:22:43 - Predict] Setting tensorflow threads to 16.
[18:22:43 - Predict] Processing 5 long region(s) with batching.
[18:22:43 - ModelLoad] Building model (steps, features, classes): (10000, 10, 5)
[18:22:43 - ModelLoad] With cudnn: True
[18:22:44 - ModelLoad] Loading weights from /mnt/DataStorage/LinuxProgs/medaka/venv/lib/python3.7/site-packages/medaka-0.8.1-py3.7-linux-x86_64.egg/medaka/data/r941_min_high_model.hdf5
[18:22:44 - PWorker] Running inference for 4.7M draft bases.
[18:22:44 - Sampler] Initializing sampler for consensus of region utg000001c:0-1000000.
[18:22:46 - Feature] Processed utg000001c:0.0-999999.1 (median depth 76.0)
[18:22:46 - Sampler] Took 1.61s to make features.
[18:22:46 - Sampler] Pileup for utg000001c:0.0-999999.1 is of width 2073349
[18:22:53 - Sampler] Initializing sampler for consensus of region utg000001c:999000-2000000.
[18:22:54 - PWorker] 13.8% Done (0.7/4.7 Mbases) in 10.0s
[18:22:55 - Feature] Processed utg000001c:999000.0-1999999.0 (median depth 85.0)
[18:22:55 - Sampler] Took 1.82s to make features.
[18:22:55 - Sampler] Pileup for utg000001c:999000.0-1999999.0 is of width 2190799
[18:23:04 - Sampler] Initializing sampler for consensus of region utg000001c:1999000-3000000.
[18:23:05 - PWorker] 33.4% Done (1.6/4.7 Mbases) in 20.5s
[18:23:06 - Feature] Processed utg000001c:1999000.0-2999999.1 (median depth 89.0)
[18:23:06 - Sampler] Took 1.83s to make features.
[18:23:06 - Sampler] Pileup for utg000001c:1999000.0-2999999.1 is of width 2203455
[18:23:15 - PWorker] 52.7% Done (2.5/4.7 Mbases) in 30.8s
[18:23:16 - Sampler] Initializing sampler for consensus of region utg000001c:2999000-4000000.
[18:23:18 - Feature] Processed utg000001c:2999000.0-3999999.1 (median depth 89.0)
[18:23:18 - Sampler] Took 1.87s to make features.
[18:23:18 - Sampler] Pileup for utg000001c:2999000.0-3999999.1 is of width 2208176
[18:23:25 - PWorker] 70.7% Done (3.3/4.7 Mbases) in 40.8s
[18:23:28 - Sampler] Initializing sampler for consensus of region utg000001c:3999000-4703280.
[18:23:29 - Feature] Processed utg000001c:3999000.0-4703279.0 (median depth 80.0)
[18:23:29 - Sampler] Took 1.52s to make features.
[18:23:29 - Sampler] Pileup for utg000001c:3999000.0-4703279.0 is of width 1488424
[18:23:35 - PWorker] 89.2% Done (4.2/4.7 Mbases) in 51.1s
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/DataStorage/LinuxProgs/medaka/venv/lib/python3.7/site-packages/medaka-0.8.1-py3.7-linux-x86_64.egg/medaka/common.py", line 687, in grouper
    batch.append(next(gen))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/DataStorage/LinuxProgs/medaka/venv/lib/python3.7/site-packages/medaka-0.8.1-py3.7-linux-x86_64.egg/medaka/common.py", line 691, in grouper
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/DataStorage/LinuxProgs/miniconda/envs/medaka/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/mnt/DataStorage/LinuxProgs/miniconda/envs/medaka/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/DataStorage/LinuxProgs/medaka/venv/lib/python3.7/site-packages/medaka-0.8.1-py3.7-linux-x86_64.egg/medaka/common.py", line 656, in gen_to_queue
    for item in generator:
RuntimeError: generator raised StopIteration
`

**Comment by cjw85** [comment]
I suspect that this may be to do with a change to how generators behave in python 3.7. We do not test medaka with python 3.7. Can you try using python 3.6 or 3.5?

**Comment by SRooke** [comment]
Perfect - switched to py3.6 and it worked perfectly!
