### ISSUE TITLE
issue with yaml load_unsafe

### ISSUE THREAD

**Issue by MichelMoser** [nanoporetech/medaka#73]
Hi, 
I run into a yaml error when running medaka 0.8.1. 
function load_unsafe seems to be non-existent: 

should i downgrade pyaml?

```
Running medaka consensus
[10:37:26 - Predict] Processing region(s): contig_29201_35488-43809:.:0-8322
Traceback (most recent call last):
  File "/mnt/users/michelmo/.conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/mnt/users/michelmo/.conda/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 363, in main
    args.func(args)
  File "/mnt/users/michelmo/.conda/envs/medaka/lib/python3.6/site-packages/medaka/inference.py", line 432, in predict
    meta = ds.meta
  File "/mnt/users/michelmo/.conda/envs/medaka/lib/python3.6/site-packages/medaka/datastore.py", line 85, in meta
    self._meta = self._load_metadata()
  File "/mnt/users/michelmo/.conda/envs/medaka/lib/python3.6/site-packages/medaka/datastore.py", line 173, in _load_metadata
    return {g: yaml.unsafe_load(self.fh[g][()]) for g in groups if g in self.fh}
  File "/mnt/users/michelmo/.conda/envs/medaka/lib/python3.6/site-packages/medaka/datastore.py", line 173, in <dictcomp>
    return {g: yaml.unsafe_load(self.fh[g][()]) for g in groups if g in self.fh}
AttributeError: module 'yaml' has no attribute 'unsafe_load'
Failed to run medaka consensus.

```

```
medaka                    0.8.1            py36hda2845c_0    bioconda
pyyaml                    5.1              py36h14c3975_0    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
```

**Comment by cjw85** [comment]
Hi @MichelMoser,

We've had previous issues with the `pyyaml` module, though this is a curious case, the `yaml` module function `unsafe_load` was [added in version 5.1](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).

Within your conda environment can you run:

    python -c "import yaml; print(yaml.__version__)"

and report what is written? For me this prints `5.1` as expected; my suspicion is that within your conda environment, medaka is not for some reason importing the correct version.

**Comment by MichelMoser** [comment]
you are correct. its 3.12

```
python -c "import yaml; print(yaml.__version__)"
3.12
```
conda list shows my pyymal 5.1. 

should i reinstall pyyml with conda and force 5.1?

**Comment by cjw85** [comment]
I would certainly give that a go.

We don't routinely use the conda packages (or associated biocontainers) so did not notice this. We're not really conda users or experts so I'm not sure why `conda list` would be reporting a different version than that which medaka can import.

**Comment by cjw85** [comment]
@MichelMoser

Did you manage to resolve this?

**Comment by MichelMoser** [comment]
No, downgrading to medaka 0.7.1 is my solution so far.
Could you maybe update the conda package to require pyyaml 5.1.2? maybe that would resolve the issue

**Comment by cjw85** [comment]
Curious, the conda packages already require pyyaml==5.1 (see [recipes/medaka/README.html](https://bioconda.github.io/recipes/medaka/README.html) and [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/medaka/meta.yaml#L45) . I'm at a loss as to why 0.7.1 would work but not 0.8.1.

Are you using a conda environment that has other software installed? Perhaps it was simply the act of reinstalling medaka (not installing 0.7.1 per se) that forced an update to pyyaml?

The 0.8.x series adds models to R10, but is otherwise identical in feature to 0.7.1.

**Comment by cjw85** [comment]
`pyyaml` is no longer required in version `v0.9.0` so should avoid this issue.
