### ISSUE TITLE
generator raised StopIteration

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/medaka#74]
**Describe the bug**
I used medaka to polish e.coli assembly. Medaka reported errors when running on cpus. However running on gpus it didn't report errors.

**Logging**
Please attach any relevant logging messages.
[10:26:46 - Sampler] Initializing sampler for consensus of region contig_1:3999000-4629735.
[10:26:48 - Feature] Processed contig_1:3999000.0-4629734.0 (median depth 48.0)
[10:26:48 - Sampler] Took 2.19s to make features.
[10:26:48 - Sampler] Pileup for contig_1:3999000.0-4629734.0 is of width 1734133
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/huangneng/tools/medaka/venv/lib/python3.7/site-packages/medaka-0.8.2-py3.7-linux-x86_64.egg/medaka/common.py", line 687, in grouper
    batch.append(next(gen))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huangneng/tools/medaka/venv/lib/python3.7/site-packages/medaka-0.8.2-py3.7-linux-x86_64.egg/medaka/common.py", line 691, in grouper
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/huangneng/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/huangneng/miniconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/huangneng/tools/medaka/venv/lib/python3.7/site-packages/medaka-0.8.2-py3.7-linux-x86_64.egg/medaka/common.py", line 656, in gen_to_queue
    for item in generator:
RuntimeError: generator raised StopIteration

**Environment (if you do not have a GPU, write No GPU):**
 - OS: Ubuntu 16.04
 - No GPU

**Additional context**

**Comment by cjw85** [comment]
You log from above indicates that you are using python 3.7; medaka does not support this version of python. You will need to use either python 3.5 or python python 3.6.
