### ISSUE TITLE
Medaka train error

### ISSUE THREAD

**Issue by caonimademimi** [nanoporetech/medaka#80]
```
[11:26:39 - root] The path CK1.training exists. Results will be overwritten.
[11:26:43 - DataIndex] Loaded sample-index from 1/1 (100.00%) of feature files.
[11:26:47 - TrainBatcher] Sample features have shape (1000, 10)
[11:26:47 - TrainBatcher] Randomly selected 2920 (20.00%) of features for validation (seed None)
[11:26:47 - TrainBatcher] Got 11677 samples in 58 batches (11677000 labels) for training
[11:26:47 - TrainBatcher] Got 2920 samples in 14 batches (2920000 labels) for validation
[11:26:47 - TrainBatcher] Max label length: 1
[11:26:47 - Labelling] Label encoding dict is:
(0, 1): 0
(5, 1): 1
(6, 1): 2
(7, 1): 3
(8, 1): 4
[11:26:47 - Labelling] New label counts Counter({0: 9595218, 1: 1561632, 4: 1557873, 2: 944511, 3: 937766})
[11:26:47 - Training] Label statistics are:
0 (*) 9595218 (w.  1.000000)
1 (A) 1561632 (w.  1.000000)
2 (C) 944511 (w.  1.000000)
3 (G) 937766 (w.  1.000000)
4 (T) 1557873 (w.  1.000000)
[11:26:47 - RunTraining] Building two_layer_bidirectional_CuDNNGRU model with: 
gru_size: 128
classify_activation: softmax
[11:26:47 - tensorflow] From /export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/medaka/models.py:78: The name tf.keras.layers.CuDNNGRU is deprecated. Please use tf.compat.v1.keras.layers.CuDNNGRU instead.

2019-09-17 11:26:47.920285: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-09-17 11:26:47.925288: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2019-09-17 11:26:47.925899: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558379c63270 executing computations on platform Host. Devices:
2019-09-17 11:26:47.925926: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
[11:26:47 - ModelLoad] With cudnn: False
[11:26:47 - tensorflow] From /export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[11:26:47 - tensorflow] From /export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[11:26:47 - tensorflow] From /export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:97: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[11:26:47 - tensorflow] From /export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[11:26:48 - RunTraining] feat_dim: 10, timesteps: 1000, num_classes: 5
[11:26:48 - RunTraining] Using sparse_categorical_crossentropy loss function
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
bidirectional (Bidirectional (None, 1000, 256)         107520    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 1000, 256)         296448    
_________________________________________________________________
classify (Dense)             (None, 1000, 5)           1285      
=================================================================
Total params: 405,253
Trainable params: 405,253
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/bin/medaka", line 10, in <module>
    sys.exit(main())
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/medaka/medaka.py", line 363, in main
    args.func(args)
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/medaka/inference.py", line 564, in train
    threads_io=args.threads_io, multi_label=args.multi_label)
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/medaka/inference.py", line 135, in run_training
    metrics=metrics,
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 320, in compile
    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1968, in _cache_output_metric_attributes
    metrics, self.output_names, output_shapes, self.loss_functions)
  File "/export/personal1/wangn/softwares/conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 613, in collect_per_output_metric_info
    'Expected a list or dictionary, found: ' + str(metrics))
TypeError: Type of `metrics` argument not understood. Expected a list or dictionary, found: ([<function cat_acc at 0x2ab466536620>, <function qscore at 0x2ab466536598>],)
```

**Comment by cjw85** [comment]
Could you please try updating to the latest release and rerun both `medaka features` and `medaka train`.

Incidentally I note from your logs that `medaka` is running without use of a GPU; this may lead to the training taking a fairly long time.

**Comment by cjw85** [comment]
@caonimademimi Have you managed to get training to run with an updated version of medaka?

**Comment by cjw85** [comment]
Closing due to inactivity, and on the understanding this issue is fixed in later releases.
