### ISSUE TITLE
Lower case letters break haploid2diploid step

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/medaka#84]
Hello,

Getting this error while looking for variants on hg19.fa
where it doesn't like lower case letters

(N=wildcard)
```
- Running medaka variant
[16:26:30 - DataIndex] Loaded 1/1 (100.00%) sample files.
[16:26:30 - Variants] Processing chrN:NNNNNN-NNNNNN.
VCF written to medaka_variant/round_1_hap_2.vcf.

- Running medaka haploid2diploid 
[16:26:39 - VCFMERGE] Merging variants in chrom chrN
Traceback (most recent call last):
  File "/home/jamfer/work/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/jamfer/work/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 431, in main
    args.func(args)
  File "/home/jamfer/work/medaka/lib/python3.6/site-packages/medaka/vcf.py", line 809, in haploid2diploid
    for v in convertor.variants():
  File "/home/jamfer/work/medaka/lib/python3.6/site-packages/medaka/vcf.py", line 766, in variants
    discard_phase=self.discard_phase))
  File "/home/jamfer/work/medaka/lib/python3.6/site-packages/medaka/vcf.py", line 658, in _merge_variants
    msg.format(v.ref, ref[start_i:end_i], v.chrom, v.pos))
ValueError: Variant ref G does not match ref g at chrN:NNNNNN
Failed to run medaka haploid2diploid.
```

**Comment by cjw85** [comment]
Thanks for reporting this. There's a simple fix; I will create a new release today.

**Comment by Psy-Fer** [comment]
Absolute legend!

**Comment by cjw85** [comment]
The updated source is now on github (tag v0.9.2), binaries will make their way to pypi and conda shortly.

**Comment by Psy-Fer** [comment]
Fantastic! Thank you very much for that
