### ISSUE TITLE
medaka_consensus: medaka_stitch: ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by macieksk** [nanoporetech/medaka#87]
Hi, we have a regression in medaka_consensus, medaka stitch part. The below command works ok in 0.8.0, however in 0.9.1 and 0.9.2 the following error is issued:

```
+ medaka_consensus -i debarcoded.none/none_wtdbg2/none_edge_fastq/E0_ctg10/E0_ctg10.fastq.gz -d debarcoded.none/none_wtdbg2/none_edge_fastq/E0_ctg10/E0_ctg10.none_E0_ctg10_racon_n4.fa -o debarcoded.none/none_wtdbg2/none_edge_fastq/E0_ctg10/E0_ctg10.racon_n4.medaka_consensus/ -t 8 -m r941_min_high
Checking program versions
Program    Version    Required   Pass     
bgzip      1.9        1.9        True     
minimap2   2.17       2.11       True     
samtools   1.9        1.9        True     
tabix      1.9        1.9        True     
Aligning basecalls to draft
-P option is deprecated
Found minimap files.
[M::main::0.005*0.81] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*0.76] mid_occ = 2
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*0.73] distinct minimizers: 1269 (100.00% are singletons); average occurrences: 1.000; average spa
cing: 5.359
[M::worker_pipeline::0.075*4.61] mapped 70 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont --MD -t 8 -a /data/debarcoded.none/none_wtdbg2/none_edge_fastq/E0_ctg10/E0_ctg10.none
_E0_ctg10_racon_n4.fa.mmi /data/debarcoded.none/none_wtdbg2/none_edge_fastq/E0_ctg10/E0_ctg10.fastq.gz
[M::main] Real time: 0.076 sec; CPU: 0.344 sec; Peak RSS: 0.018 GB
Running medaka consensus
[21:47:36 - Predict] Processing region(s): @38919f42-e619-4825-a066-57e2dabe1b9c:4865-12032(+):x70:0-6800
[21:47:36 - Predict] Setting tensorflow threads to 8.
[21:47:37 - Predict] Processing 1 long region(s) with batching.
[21:47:37 - Predict] Using model: /usr/local/lib/python3.5/site-packages/medaka/data/r941_min_high_model.hdf5.
[21:47:37 - ModelLoad] Building model with cudnn optimization: False
[21:47:38 - DLoader] Initializing data loader
[21:47:38 - PWorker] Running inference for 0.0M draft bases.
[21:47:38 - Sampler] Initializing sampler for consensus of region @38919f42-e619-4825-a066-57e2dabe1b9c:4865-12032(+):x7
0:0-6800.
[21:47:38 - Feature] Processed @38919f42-e619-4825-a066-57e2dabe1b9c:4865-12032(+):x70:0.0-6799.0 (median depth 70.0)
[21:47:38 - Sampler] Took 0.04s to make features.
[21:47:40 - PWorker] All done, 0 remainder regions.
[21:47:40 - Predict] Finished processing all regions.
Running medaka stitch
[21:47:42 - DataIndex] Loaded 1/1 (100.00%) sample files.
Traceback (most recent call last):
  File "/usr/local/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.9.2', 'console_scripts', 'medaka')()
  File "/usr/local/lib/python3.5/site-packages/medaka/medaka.py", line 428, in main
    args.func(args)
  File "/usr/local/lib/python3.5/site-packages/medaka/stitch.py", line 116, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/usr/local/lib/python3.5/site-packages/medaka/stitch.py", line 48, in stitch_from_probs
    for r in regions]
  File "/usr/local/lib/python3.5/site-packages/medaka/stitch.py", line 48, in <listcomp>
    for r in regions]
  File "/usr/local/lib/python3.5/site-packages/medaka/common.py", line 408, in from_string
    ref_name, bounds = region.split(':')
ValueError: too many values to unpack (expected 2)
Failed to stitch consensus chunks.
+ exit 1
```

**Comment by macieksk** [comment]
A possible clue is that the assembled region is short and may very well consist of only one chunk.

**Comment by cjw85** [comment]
The issue appears to be in the name of the contigs:

```@38919f42-e619-4825-a066-57e2dabe1b9c:4865-12032(+):x70:0.0-6799.0```.

`medaka`'s parsing of this is failing. You could work around this by cleaning `:` characters from the sequence names before giving to `medaka`.

**Comment by macieksk** [comment]
Yes indeed, renaming to @38919f42-e619-4825-a066-57e2dabe1b9c_4865-12032(+)_x70 solved the problem!

Can we hope for a fix supporting fasta contig names with ":" in the nearest future?

**Comment by cjw85** [comment]
A fix has been made already in our development code branch and will be part of the next release within the next two weeks.
