### ISSUE TITLE
Hi,  I have this bug problem with the newest version of medaka v0.9.2 installed with conda:  [02:22:00 - Stitch] Processing tig00001220:0-. [02:22:01 - Stitch] Processing tig00001224:0-. [02:22:02 - Stitch] Processing tig00001233:0-. Traceback (most recent call last): File "/user/wupf2892/miniconda2/envs/medaka/bin/medaka", line 11, in sys.exit(main()) File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 428, in main args.func(args) File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 116, in stitch joined = stitch_from_probs(args.inputs, regions=args.regions) File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 87, in stitch_from_probs s1, s2) File "/user/wupf2892/miniconda2/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 275, in overlap_indices assert len(pos1_ovl) == len(pos2_ovl) AssertionError Failed to stitch consensus chunks.  

### ISSUE THREAD

**Issue by Siadjeu** [nanoporetech/medaka#88]
**Describe the bug**

**Logging**
Please attach any relevant logging messages.

**Environment (if you do not have a GPU, write No GPU):**
 - OS: [e.g. Ubuntu 16.04]
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Duplicates https://github.com/nanoporetech/medaka/issues/89
