### ISSUE TITLE
Polishing "short" references

### ISSUE THREAD

**Issue by SorenKarst** [nanoporetech/medaka#9]
I would like to perform polishing using medaka on "short" references, which are approximately 1400 bp long. Medaka breaks when I attempt to do this and the error seems to be connected to the length of my references/sequences:

---
...
[13:20:48 - root] Creating consensus features.
[13:20:48 - root] Got regions:
            NODE_1_length_1395_cov_24.495757:0-1395
[13:20:48 - root] Got read fraction None
[13:20:48 - root] Writing samples to features.hdf
[13:20:48 - root] Processed NODE_1_length_1395_cov_24.495757:1.0-1394.0 (median depth 86.0)
[13:20:48 - medaka.compress] Skipping sample NODE_1_length_1395_cov_24.495757:1.0-1394.0 which has 3412 columns < min 10000.
[13:20:48 - root] Label counts:
...
---

The reference data set in this case only has one sequence, and it seems to be skipped here.

Would it be possible to change the < min 10000 setting, with out breaking downstream processing?

Thanks for developing and making medaka available to us!

Best regards
Søren

**Comment by SorenKarst** [comment]
Thank you. I will have a go at it.

**Comment by ziels** [comment]
In a similar application, I am trying to train a consensus network for "short" references. I added the above text (`--chunk_len 3000 --chunk_ovl 500`) to the medaka_consensus script on line 69. But, I am wondering if a similar modification needs to be done for training with short references? The reason I ask is that currently, I do not get any 'labels' in my train_features.hdf file: 

`hp_compress features ${CALLS2DRAFT}.bam ${TRAINFEATURES} -T ${TRUTH2DRAFT}.bam -t ${NUM_THREADS} -r ${REFNAME}:-${TRAINEND} --batch_size ${BATCHSIZE} --read_fraction ${FRACTION} --chunk_len 1000 --chunk_ovlp 0 -m ${MODEL_FEAT_OPT} --max_label_len 1`

> Using TensorFlow backend.
{'consensus_as_ref': False, 'is_compressed': False, 'log_min': None, 'max_hp_len': 1, 'normalise': 'total', 'ref_mode': None, 'with_depth': False}
[12:15:22 - root] FeatureEncoder options: 
consensus_as_ref: False
is_compressed: False
log_min: None
max_hp_len: 1
normalise: total
ref_mode: None
with_depth: False
[12:15:22 - root] Got regions:
			NODE:0-1388
[12:15:23 - root] Processed NODE:1.0-1362.0 (median depth 106.0)
/home/virtual-envs/medaka/lib/python3.6/site-packages/medaka/common.py:476: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  yield a[slicee]
/home/virtual-envs/medaka/lib/python3.6/site-packages/medaka/common.py:481: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  yield a[slicee]

`medaka train ${TRAINFEATURES} --train_name ${TRAINNAME} --epochs 10`

> Using TensorFlow backend.
[12:17:01 - root] The path training.16S exists. Results will be overwritten.
[12:17:01 - root] Loading datasets:
train_features.hdf
[12:17:01 - root] Total labels 0
[12:17:01 - root] No batches in train_features.hdf.
Traceback (most recent call last):
  File "/home/virtual-envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/virtual-envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 76, in main
    args.func(args)
  File "/home/virtual-envs/medaka/lib/python3.6/site-packages/medaka/inference.py", line 411, in train
    sample_index = get_sample_index_from_files(args.features, max_samples=args.max_samples)
  File "/home/virtual-envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 395, in get_sample_index_from_files
    keys = (k for k in fh[_sample_path_]) if filetype == 'hdf' else (k for k in fh)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ziels/virtual-envs/medaka/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'samples' doesn't exist)"

**Comment by cjw85** [comment]
Version 0.4.0 supports correction of short sequences.
