### ISSUE TITLE
Build from source: HDF5 model reading error

### ISSUE THREAD

**Issue by kishwarshafin** [nanoporetech/medaka#90]
**Describe the bug**
Hello, `medaka consensus` don't seem to work with all the new changes. I am trying the walkthrough and getting the following error.

**Logging**
`[21:34:21 - Predict] Processing region(s): utg000001c:0-4702069
Traceback (most recent call last):
  File "/home/kishwar/medaka/venv/bin/medaka", line 11, in <module>
    load_entry_point('medaka==0.9.2', 'console_scripts', 'medaka')()
  File "/home/kishwar/medaka/venv/lib/python3.6/site-packages/medaka-0.9.2-py3.6-linux-x86_64.egg/medaka/medaka.py", line 428, in main
    args.func(args)
  File "/home/kishwar/medaka/venv/lib/python3.6/site-packages/medaka-0.9.2-py3.6-linux-x86_64.egg/medaka/prediction.py", line 97, in predict
    with medaka.datastore.DataStore(args.model) as ds:
  File "/home/kishwar/medaka/venv/lib/python3.6/site-packages/medaka-0.9.2-py3.6-linux-x86_64.egg/medaka/datastore.py", line 39, in __init__
    self.fh = h5py.File(self.filename, self.mode)
  File "/home/kishwar/medaka/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/kishwar/medaka/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`

**Environment (if you do not have a GPU, write No GPU):**
 - OS: Ubuntu 18.0
 - GPU model: Tesla P100
 - Nvidia driver version N/A
 - CUDA version N/A
 - cuDNN version N/A

**Additional context**

**Comment by cjw85** [comment]
Hi,

When building from source you will need to ensure you have git LFS installed before cloning, I suspect medaka has picked up the LFS stub and tried to feed that to the HDF5 library. We can add a more informative warning here on installation.

**Comment by kishwarshafin** [comment]
auch, my bad. Fixed now.
