### ISSUE TITLE
Failed to stitch consensus chunks

### ISSUE THREAD

**Issue by Siadjeu** [nanoporetech/medaka#93]
**Describe the bug**

Hi @cjw85 
Sorry to disturb you again, thanks for the new version of Medaka 0.10.0.  However, when I do the first run with medaka, it works well but when I want to do the second run on the consensus.fasta file generated by the first medaka run, I got this error message:

**Logging**
[00:32:18 - PWorker] All done, 0 remainder regions.
[00:32:18 - Predict] Finished processing all regions.
Running medaka stitch
[00:32:25 - DataIndex] Loaded 1/1 (100.00%) sample files.
Traceback (most recent call last):
  File "/user/wupf2892/miniconda3/envs/medaka/bin/medaka", line 10, in <module>
    sys.exit(main())
  File "/user/wupf2892/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 434, in main
    args.func(args)
  File "/user/wupf2892/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 120, in stitch
    joined = stitch_from_probs(args.inputs, regions=args.regions)
  File "/user/wupf2892/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 48, in stitch_from_probs
    for r in regions]
  File "/user/wupf2892/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 48, in <listcomp>
    for r in regions]
  File "/user/wupf2892/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 463, in from_string
    start, end = [int(b) for b in bounds.split('-')]
  File "/user/wupf2892/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 463, in <listcomp>
    start, end = [int(b) for b in bounds.split('-')]
ValueError: invalid literal for int() with base 10: '1.0'
Failed to stitch consensus chunks.

**Environment (No GPU):**
 - OS: [e.g. Ubuntu 16.04]
 - GPU model
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Additional context**

**Comment by cjw85** [comment]
Hi @Siadjeu,

I believe I know why this is occurring, it will require a fix from us.

Note that running medaka a second time generally does not improve the results further, @rrwick has an example of this in his [assembly-accuracy](https://github.com/rrwick/August-2019-consensus-accuracy-update#assembly-accuracy) comparisons.

**Comment by cjw85** [comment]
@Siadjeu 

We will make a change in the next release that will reformat the sequence identifiers in the output `.fasta` which will ameliorate the above issue.

Currently if you do wish to attempt to iterate the application of `medaka` you will have to run:

    sed "s/[:,-]/_/g" consensus.fasta > consensus.mod.fasta

and give `consensus.mod.fasta` to `medaka_consensus` the second time around.

**Comment by Siadjeu** [comment]
@cjw85 
ok, thanks for all these information and I will give a try to your script and let you know.

**Comment by Siadjeu** [comment]
@cjw85 

I just finished with the second run of medaka and it was successful, thanks.

**Comment by cjw85** [comment]
We have just released `v0.10.1` which will appear on pypi and bioconda shortly. It resolves this issue by using a different formatting of the output sequence names.
